function k(J){throw J;}var m=void 0,q=null;function U(J){return function(V){this[J]=V}}
var cb=new function(){function J(e,a){return new g(function(){var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return z(b(e)(c),J(e,d))}if(b(a)===q)return D(q);k(["unhandled case in mapM_",[e,a]])})}function V(e,a){return new g(function(){return b(b(r)(e))(V(F(e,a),a))})}function W(e,a){return new g(function(){var d=a,c=b(e);if(c instanceof p){var f=c.c,c=c.d;return b(b(r)(f))(W(c,d))}d=a;if(b(e)===q)return d;k(["unhandled case in conc",[e,a]])})}function fa(e,a){return new g(function(){if(b(a)===q)return q;
var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(b(r)(e))(b(b(r)(c))(fa(e,d)))}k(["unhandled case in prependToAll",[e,a]])})}function db(e,a){return new g(function(){if(b(a)===q)return q;var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(b(r)(c))(fa(e,d))}k(["unhandled case in intersperse",[e,a]])})}function eb(e,a,d){return new g(function(){for(;;){if(b(d)===q){var c=a;return c}c=b(d);if(c instanceof p){var f=c.c,g=c.d,c=a,h=e;e=h;a=b(b(h)(c))(f);d=g}else k(["unhandled case in foldl",[e,
a,d]])}})}function fb(e,a,b){return new g(function(){return new w(n(["user","Node",[]],l(["user","Node",[]],b).setAttributeNS(q,A(e),A(a))&&q||l(["user","Node",[]],b)))})}function gb(e,a){return new g(function(){return new w(n(["user","Node",[]],document.createElementNS(A(e),A(a))))})}function hb(e){return new g(function(){return new w(n(["user","Node",[]],l(["user","Node",[]],e).parentNode))})}function ib(e){return new g(function(){return new w(n(["user","Node",[]],document.createTextNode(A(e))))})}
function na(e,a,d){return new g(function(){if(b(d)===q){var c=a;return D(c)}var f=b(d);if(f instanceof p){var c=f.c,g=f.d;return u(b(b(e)(a))(c),function(a){return na(e,a,g)})}k(["unhandled case in foldM",[e,a,d]])})}function jb(e){return new g(function(){return b(e)})}function X(e,a){return new g(function(){if(0===b(e)||b(a)===q)return q;var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(oa(e))?R(h("take: negative length")):b(b(r)(c))(X(x(e,1),d))}k(["unhandled case in take",[e,a]])})}function kb(e){return new g(function(){return b(e)===
q?R(h("cycle: empty list")):function(){var a=new g(function(){return S(e,a)});return a}()})}function ga(e,a){return new g(function(){return b(b(r)(a))(ga(e,b(e)(a)))})}function pa(e,a,d,c,f){return new g(function(){return function(){return b(b(t)(b(b(K)(b(b(t)(G))(b(b(function(a){return function(c){return new g(function(){return E(qa,E(lb,b(b(r)(0))(S(X(L(c,2),ra(x(1,a),F(x(1,a),b(b(mb)(a))(jb(L(2,c)))))),h([1])))))})}})(a))(d))))(b(function(a){return new g(function(){return E(nb,E(ha,b(b(r)(h("0 0 1 1")))(ia(a,
h("0 .75 .25 1; 1 .75 .25 0")))))})})(d))))(b(ob)(S(b(b(b(b(e)(a))(d))(c))(f),h([f]))))}()})}function ra(e,a){return new g(function(){return V(e,x(a,e))})}function pb(e){return new g(function(){return function(){var a=new g(function(){return Y(sa,0,e)});return b(qb(a))?S(ia(a,Z),e):R(h("Markup has more close elements than open"))}()})}function ta(e){return new g(function(){return new B(e)})}function Y(e,a,d){return new g(function(){if(b(d)===q){var c=a;return c}c=b(d);if(c instanceof p){var f=c.c,
g=c.d,c=a;return b(b(e)(f))(Y(e,c,g))}k(["unhandled case in foldr",[e,a,d]])})}function R(e){return new g(function(){k(A(e))})}function rb(e,a){return new g(function(){return new C(e,a)})}function ua(e){return new g(function(){var a=JSON.stringify(l(["automatic"],e));return h(a)})}function va(e){return new g(function(){var a=b(e);if(a instanceof p)return S(va(a.d),h([a.c]));if(b(e)===q)return q;k(["unhandled case in reverse",[e]])})}function ia(e,a){return new g(function(){return 0===b(e)?q:b(oa(e))?
R(h("replicate: negative length")):b(b(r)(a))(ia(x(e,1),a))})}function S(e,a){return new g(function(){return W(e,a)})}function E(e,a){return new g(function(){return b(e)(a)})}function $(e,a){return new g(function(){if(b(a)===q)return q;var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(b(r)(b(e)(c)))($(e,d))}k(["unhandled case in map",[e,a]])})}function sb(e,a){return new g(function(){if(b(a)instanceof y){var d=e;return pb(d)}d=e;return b(b(t)(b(b(t)(d))(Z)))(a)})}function tb(){return new g(function(){return b(b(t)(b(b(t)(b(ub)(25)))(b(vb)(50))))(b(wb)(100))})}
function aa(e,a,d){return new g(function(){var c=b(d);if(c instanceof p){var f=c.c,g=c.d,c=b(a);if(c instanceof p){var h=c.c,c=c.d;return b(b(r)(b(b(e)(h))(f)))(aa(e,c,g))}}return q})}function wa(e){return new g(function(){return b(b(r)(e))(wa(e))})}function ba(e,a,b,c){return new g(function(){return function(){return pa(function(a){return function(c){return function(e){return function(b){return new g(function(){return E(xb(b),X(F(c,1),E(ja(function(a){return x(b,a)}),ga(function(c){return L(c,a)},
x(b,e)))))})}}}},e,a,b,c)}()})}function ca(e,a,d,c){return new g(function(){return function(){return pa(function(a){return function(c){return function(e){return function(d){return new g(function(){return b(b(r)(e))(X(L(c,2),aa(yb,kb(h([function(a){return F(d,a)},function(a){return x(d,a)}])),ga(function(c){return L(c,a)},L(a,x(d,e))))))})}}}},e,a,d,c)}()})}function ka(e,a,d){return new g(function(){return function(){return E(la,$(function(a){return new g(function(){return b(b(t)(G))(rb(e,ua(a)))})},
ra(a,F(a,d))))}()})}function zb(e,a){return new g(function(){return new w(n(["unknown"],window.addEventListener(A(e),l(["action",[["unknown"]]],a),b(!1))))})}function Ab(e){return new g(function(){return new w(n(["unknown"],setTimeout(l(["action",[["unknown"]]],e),b(8500))))})}function ma(e,a){var d=b(a),c=e[2];if(d instanceof M){var f={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a);m!==c&&(f.slot1=c);return f}return d instanceof H?f={instance:"Null"}:d instanceof
N?(f={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof I?f={instance:"Undefined"}:d instanceof xa?(f={instance:"Just"},c=l(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof ya?f={instance:"Nothing"}:d instanceof za?(f={instance:"Left"},c=l(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof Aa?(f={instance:"Right"},c=l(c&&c[0]?c[0]:
"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof Ba?(f={instance:"Ratio"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),f):d instanceof Ca?f={instance:"GT"}:d instanceof Da?f={instance:"LT"}:d instanceof Ea?f={instance:"EQ"}:d instanceof M?(f={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof H?f={instance:"Null"}:d instanceof N?(f={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===
e[0]?["automatic"]:["unknown"],d.a),m!==c&&(f.slot1=c),f):d instanceof I?f={instance:"Undefined"}:d instanceof O?(f={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),f):d instanceof B?(f={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),f):d instanceof C?(f={instance:"Attribute"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(f.slot2=c),f):d instanceof y?f={instance:"Complete"}:d instanceof Fa?(f={instance:"M"},c=
b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),f):d instanceof Ga?(f={instance:"L"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),f):d instanceof Ha?(f={instance:"H"},c=b(d.a),m!==c&&(f.slot1=c),f):d instanceof Ia?(f={instance:"V"},c=b(d.a),m!==c&&(f.slot1=c),f):d instanceof Ja?(f={instance:"A"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),c=b(d.e),m!==c&&(f.slot3=c),c=b(d.f),m!==c&&(f.slot4=c),c=b(d.g),m!==c&&(f.slot5=c),c=b(d.h),m!==c&&(f.slot6=c),d=b(d.m),m!==d&&(f.slot7=
d),f):d instanceof Ka?(f={instance:"C"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),c=b(d.e),m!==c&&(f.slot3=c),c=b(d.f),m!==c&&(f.slot4=c),c=b(d.g),m!==c&&(f.slot5=c),c=b(d.h),m!==c&&(f.slot6=c),f):d instanceof La?(f={instance:"S"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),c=b(d.e),m!==c&&(f.slot3=c),c=b(d.f),m!==c&&(f.slot4=c),f):d instanceof Ma?(f={instance:"Q"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),c=b(d.e),m!==c&&(f.slot3=c),c=b(d.f),m!==c&&(f.slot4=
c),f):d instanceof Na?(f={instance:"T"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),f):d instanceof Oa?f={instance:"Z"}:d instanceof Pa?(f={instance:"Translate"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),f):d instanceof Qa?(f={instance:"Rotate"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),m!==c&&(f.slot2=c),c=b(d.e),m!==c&&(f.slot3=c),f):d instanceof Ra?(f={instance:"Scale"},c=b(d.a),m!==c&&(f.slot1=c),f):d instanceof Sa?(f={instance:"Scale2d"},c=b(d.a),m!==c&&(f.slot1=c),c=b(d.b),
m!==c&&(f.slot2=c),f):d instanceof O?(f={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),f):d instanceof B?(f={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),f):d instanceof C?(f={instance:"Attribute"},c=l(["user","DString",[]],d.a),m!==c&&(f.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(f.slot2=c),f):d instanceof y?f={instance:"Complete"}:a}function Sa(e,a){this.a=e;this.b=a}function Ra(e){this.a=e}function Qa(e,a,b){this.a=e;this.b=a;this.e=b}function Pa(b,
a){this.a=b;this.b=a}function Oa(){}function Na(b,a){this.a=b;this.b=a}function Ma(b,a,d,c){this.a=b;this.b=a;this.e=d;this.f=c}function La(b,a,d,c){this.a=b;this.b=a;this.e=d;this.f=c}function Ka(b,a,d,c,f,g){this.a=b;this.b=a;this.e=d;this.f=c;this.g=f;this.h=g}function Ja(b,a,d,c,f,g,h){this.a=b;this.b=a;this.e=d;this.f=c;this.g=f;this.h=g;this.m=h}function Ia(b){this.a=b}function Ha(b){this.a=b}function Ga(b,a){this.a=b;this.b=a}function Fa(b,a){this.a=b;this.b=a}function y(){}function C(b,a){this.a=
b;this.b=a}function B(b){this.a=b}function O(b){this.a=b}function Ea(){}function Da(){}function Ca(){}function Ba(b,a){this.a=b;this.b=a}function Aa(b){this.a=b}function za(b){this.a=b}function ya(){}function xa(b){this.a=b}function I(){}function N(b){this.a=b}function H(){}function M(b){this.a=b}function Bb(e){return function(a){return function(d){return new g(function(){return function(){return b(b(t)(b(b(t)(b(b(t)(G))(b(Ta)(e))))(b(Cb)(a))))(b(Ua)(b(function(a){return new g(function(){return b(Db(a))?
ua(a):h("indefinite")})})(d)))}()})}}}function Eb(e){return function(a){return function(d){return new g(function(){return function(){return na(function(a){return function(d){return new g(function(){if(b(d)instanceof C){var g=b(d).a,h=b(d).b,l=a;return fb(g,h,l)}if(b(d)instanceof B)return g=b(d).a,l=a,u(gb(e,g),Va(l));if(b(d)instanceof y)return l=a,hb(l);if(b(d)instanceof O)return h=b(d).a,l=a,z(u(ib(h),Va(l)),D(l));k(["unhandled case in go",[a,d]])})}},d,va(a))}()})}}}function T(b){return function(a){return new g(function(){return new w(n(["list",
[["user","Node",[]]]],l(["user","Node",[]],a).getElementsByTagName(A(b))))})}}function Fb(b){return new g(function(){return new w(n(["unknown"],l(["user","Node",[]],b).parentNode.removeChild(l(["user","Node",[]],b))))})}function Va(b){return function(a){return new g(function(){return new w(n(["user","Node",[]],l(["user","Node",[]],b).appendChild(l(["user","Node",[]],a))&&q||l(["user","Node",[]],a)))})}}function sa(e){return function(a){return new g(function(){var d=a;if(b(e)instanceof B)return F(d,
1);d=a;return b(e)instanceof y?x(d,1):d=a})}}function s(b){return function(a){return new g(function(){return new C(b,a)})}}function Gb(e){return function(a){return new g(function(){return b(Hb)(db(e,a))})}}function xb(e){return function(a){return new g(function(){if(b(a)===q)return q;var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(b(r)(c))(fa(e,d))}k(["unhandled case in intersperse",[e,a]])})}}function Ib(e){return function(a){return function(d){return new g(function(){var c=b(d);if(c instanceof
p){var f=c.c,g=c.d,c=b(a);if(c instanceof p){var h=c.c,c=c.d;return b(b(r)(b(b(e)(h))(f)))(aa(e,c,g))}}return q})}}}function Wa(b){return function(a){return new g(function(){return W(b,a)})}}function Jb(e){return function(a){return new g(function(){var d=b(a);if(d instanceof p)return eb(e,d.c,d.d);if(b(a)===q)return R(h("foldl1: empty list"));k(["unhandled case in foldl1",[e,a]])})}}function Kb(e){return function(a){return function(d){return new g(function(){if(b(d)===q){var c=a;return c}c=b(d);if(c instanceof
p){var f=c.c,g=c.d,c=a;return b(b(e)(f))(Y(e,c,g))}k(["unhandled case in foldr",[e,a,d]])})}}}function Lb(e){return function(a){return new g(function(){var d=a,c=b(e);if(c instanceof p){var f=c.c,c=c.d;return b(b(r)(f))(W(c,d))}d=a;if(b(e)===q)return d;k(["unhandled case in conc",[e,a]])})}}function ja(e){return function(a){return new g(function(){if(b(a)===q)return q;var d=b(a);if(d instanceof p){var c=d.c,d=d.d;return b(b(r)(b(e)(c)))($(e,d))}k(["unhandled case in map",[e,a]])})}}function da(e){return function(a){return function(d){return new g(function(){return b(b(e)(d))(a)})}}}
function yb(e){return function(a){return new g(function(){return b(e)(a)})}}function v(e){return function(a){return function(d){return new g(function(){return b(e)(b(a)(d))})}}}function P(b){return new g(function(){var a=JSON.stringify(l(["automatic"],b));return h(a)})}function Mb(e){return new g(function(){return function(){return Y(function(a){return function(d){return new g(function(){return u(a,function(a){return u(d,function(d){return D(b(b(r)(a))(d))})})})}},D(q),e)}()})}function Nb(e){return function(a){return new g(function(){var d=
b(a);if(d instanceof p){var c=d.c,d=d.d;return z(b(e)(c),J(e,d))}if(b(a)===q)return D(q);k(["unhandled case in mapM_",[e,a]])})}}function b(b,a){for(;b instanceof g;)b=b.l(a);return b}function g(b){this.i=!1;this.value=b}function w(b){this.value=b}function z(b,a){return u(b,function(){return a})}function u(e,a){return new g(function(){var d=b(e,!0);return b(a)(d.value)})}function D(b){return new w(b)}function l(e,a){var d=e[0],c=e[1],f;if("action"==d)f=function(){return l(c[0],b(a,!0).value)};else if("function"==
d)f=function(){var d=a,e=c[c.length-1],f=c.length;if(1<f){for(var d=b(d,!0),g=0;g<f-1&&d instanceof Function;g++)d=b(d(n(c[g],arguments[g])),!0);f=e[1];return"action"==e[0]?l(f[0],d.value):l(e,d)}k(Error("Nullary function?"))};else if("string"==d)f=A(a);else if("list"==d){d=[];for(a=b(a);a instanceof p;)d.push(l(c[0],a.c)),a=b(a.d);f=d}else if("tuple"==d){d=[];a=b(a);for(f=0;a instanceof p;)d.push(l(c[f++],a.c)),a=b(a.d);f=d}else if("defined"==d)a=b(a),f=a instanceof I?m:ma(c[0],a.slot1);else if("nullable"==
d)a=b(a),f=a instanceof H?q:ma(c[0],a.slot1);else if("double"==d||"int"==d||"bool"==d)f=b(a);else{if("ptr"==d||"unknown"==d)return a;"automatic"==d||"user"==d?(a instanceof g&&(a=b(a)),f=ma(e,a)):k(Error("Unhandled Fay->JS translation type: "+d))}return f}function A(e){var a="";for(e=b(e);e instanceof p;)a+=e.c,e=b(e.d);return a}function n(b,a){var d=b[0],c=b[1],f;if("action"==d)f=new w(n(c[0],a));else if("string"==d)f=h(a);else if("list"==d){var g=[],d=0;for(f=a.length;d<f;d++)g.push(n(c[0],a[d]));
f=h(g)}else if("tuple"==d){g=[];d=0;for(f=a.length;d<f;d++)g.push(n(c[d],a[d]));f=h(g)}else if("defined"==d)f=a===m?new I:new N(n(c[0],a));else if("nullable"==d)f=a===q?new H:new M(n(c[0],a));else if("int"==d)f=Math.round(a),f!==a&&k("Argument "+a+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return a;"automatic"==d||"user"==d?(a&&a.instance?(c=b[2],c="Nullable"===a.instance?new M(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?
new H:"Defined"===a.instance?new N(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new I:"Just"===a.instance?new xa(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ya:"Left"===a.instance?new za(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new Aa(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new Ba(a.slot1,a.slot2):
"GT"===a.instance?new Ca:"LT"===a.instance?new Da:"EQ"===a.instance?new Ea:"Nullable"===a.instance?new M(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new H:"Defined"===a.instance?new N(n(c&&c[0]?c[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new I:"Content"===a.instance?new O(n(["user","DString",[]],a.slot1)):"Element"===a.instance?new B(n(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new C(n(["user","DString",
[]],a.slot1),n(["user","DString",[]],a.slot2)):"Complete"===a.instance?new y:"M"===a.instance?new Fa(a.slot1,a.slot2):"L"===a.instance?new Ga(a.slot1,a.slot2):"H"===a.instance?new Ha(a.slot1):"V"===a.instance?new Ia(a.slot1):"A"===a.instance?new Ja(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6,a.slot7):"C"===a.instance?new Ka(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6):"S"===a.instance?new La(a.slot1,a.slot2,a.slot3,a.slot4):"Q"===a.instance?new Ma(a.slot1,a.slot2,a.slot3,a.slot4):"T"===a.instance?
new Na(a.slot1,a.slot2):"Z"===a.instance?new Oa:"Translate"===a.instance?new Pa(a.slot1,a.slot2):"Rotate"===a.instance?new Qa(a.slot1,a.slot2,a.slot3):"Scale"===a.instance?new Ra(a.slot1):"Scale2d"===a.instance?new Sa(a.slot1,a.slot2):"Content"===a.instance?new O(n(["user","DString",[]],a.slot1)):"Element"===a.instance?new B(n(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new C(n(["user","DString",[]],a.slot1),n(["user","DString",[]],a.slot2)):"Complete"===a.instance?new y:a):c=a,f=c):
k(Error("Unhandled JS->Fay translation type: "+d))}return f}function p(b,a){this.c=b;this.d=a}function h(b){for(var a=q,d=b.length-1;0<=d;d--)a=new p(b[d],a);return a}function r(b){return function(a){return new p(b,a)}}function L(e,a){return new g(function(){return b(e)*b(a)})}function F(e,a){return new g(function(){return b(e)+b(a)})}function x(e,a){return new g(function(){return b(e)-b(a)})}function mb(e){return function(a){return new g(function(){return b(e)/b(a)})}}function Db(e){return new g(function(){return b(e)>
b(0)})}function oa(e){return new g(function(){return b(e)<b(0)})}function qb(e){return new g(function(){return b(e)>=b(0)})}g.prototype.l=function(b){return b?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var Hb=new g(function(){return b(Kb(Lb))(q)}),Ob=new g(function(){return b(v(function(e){return b(v(function(a){return b(v(Mb))(a)}))(e)}))(Ib)}),Z=new g(function(){return new y}),G=new g(function(){return q}),t=new g(function(){return da(r)}),K=new g(function(){return da(Wa)}),
Q=new g(function(){return new w(n(["user","Node",[]],document.documentElement))}),Ta=new g(function(){return s(h("attributeName"))}),Xa=new g(function(){return s(h("begin"))}),Ya=new g(function(){return s(h("calcMode"))}),ea=new g(function(){return s(h("fill"))}),Za=new g(function(){return s(h("keySplines"))}),qa=new g(function(){return s(h("keyTimes"))}),Ua=new g(function(){return s(h("repeatCount"))}),$a=new g(function(){return s(h("values"))}),Pb=new g(function(){return ta(h("animate"))}),Qb=new g(function(){return ta(h("circle"))}),
Rb=new g(function(){return h("http://www.w3.org/2000/svg")}),ub=new g(function(){return b(v(function(e){return b(b(t)(b(b(t)(G))(Qb)))(e)}))(Sb)}),ab=new g(function(){return b(v(function(e){return b(v(function(a){return b(v(function(a){return b(b(K)(b(b(t)(G))(Pb)))(a)}))(a)}))(e)}))(Bb)}),Tb=new g(function(){return b(v($a))(ha)}),ob=new g(function(){return b(v(Tb))(ja(P))}),nb=new g(function(){return b(v(function(e){return b(b(t)(b(b(t)(G))(b(Ya)(h("spline")))))(e)}))(Za)}),ha=new g(function(){return Gb(h(";"))}),
lb=new g(function(){return b(v(ha))(ja(P))}),bb=new g(function(){return Eb(Rb)}),la=new g(function(){return b(Ob)(bb)}),vb=new g(function(){return b(v(s(h("cx"))))(P)}),wb=new g(function(){return b(v(s(h("cy"))))(P)}),Cb=new g(function(){return b(v(s(h("dur"))))(P)}),Sb=new g(function(){return b(v(s(h("r"))))(P)}),s=function(b){return function(a){return new g(function(){return new C(b,a)})}},Z=new g(function(){return new y}),G=new g(function(){return q}),t=new g(function(){return da(r)}),K=new g(function(){return da(Wa)}),
sa=function(e){return function(a){return new g(function(){var d=a;if(b(e)instanceof B)return F(d,1);d=a;return b(e)instanceof y?x(d,1):d=a})}},Ta=new g(function(){return s(h("attributeName"))}),Xa=new g(function(){return s(h("begin"))}),Ya=new g(function(){return s(h("calcMode"))}),ea=new g(function(){return s(h("fill"))}),Za=new g(function(){return s(h("keySplines"))}),qa=new g(function(){return s(h("keyTimes"))}),Ua=new g(function(){return s(h("repeatCount"))}),$a=new g(function(){return s(h("values"))}),
Ub=new g(function(){function e(a){return new g(function(){return sb(b(b(t)(b(b(t)(b(b(K)(b(b(t)(tb()))(b(ea)(a))))(b(b(b(ab)(h("cy")))(2))(1))))(b(ea)(h("freeze")))))(b(Xa)(h("indefinite"))),Z)})}var a=new g(function(){return E(Jb(K),$(e,c))}),d=new g(function(){return h([ba(0.4,3,100,400),ca(0.35,3,100,400),ba(0.75,4,100,400),ca(0.65,4,100,400)])}),c=new g(function(){return h([h("lightpink"),h("lightblue"),h("lightsalmon"),h("lightgreen")])});return z(u(Q,b(bb)(a)),z(u(u(Q,T(h("circle"))),ka(h("cx"),
50,100)),z(u(u(u(Q,T(h("animate"))),b(la)(d)),ka(h("begin"),0,2)),D(q))))}),Vb=new g(function(){var e=new g(function(){return aa(K,wa(b(b(t)(b(b(b(ab)(h("r")))(0.75))(1)))(b(ea)(h("freeze")))),h([ba(0.5,5,25,50),ca(0.45,5,25,50),ba(0.85,6,25,50),ca(0.75,6,25,50)]))});return z(u(u(Q,T(h("animate"))),Nb(Fb)),z(u(u(Q,T(h("circle"))),b(la)(e)),z(u(u(Q,T(h("animate"))),ka(h("begin"),9,0.75)),D(q))))}),Wb=new g(function(){return z(zb(h("load"),Ub),Ab(Vb))}),M=U("a"),H=function(){},N=U("a"),I=function(){},
O=U("a"),B=U("a"),C=function(b,a){this.a=b;this.b=a},y=function(){};this.j=Wb;this.k=b};cb.k(cb.j);
