function k(H){throw H;}var m=void 0,r=null;function U(H){return function(I){this[H]=I}}
var ab=new function(){function H(f,b){return new g(function(){return a(a(s)(f))(H(D(f,b),b))})}function I(f,b){return new g(function(){var d=b,c=a(f);if(c instanceof p){var e=c.c,c=c.d;return a(a(s)(e))(I(c,d))}d=b;if(a(f)===r)return d;k(["unhandled case in conc",[f,b]])})}function ba(f,b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(f))(a(a(s)(c))(ba(f,d)))}k(["unhandled case in prependToAll",[f,b]])})}function bb(f,b){return new g(function(){if(a(b)===
r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(c))(ba(f,d))}k(["unhandled case in intersperse",[f,b]])})}function cb(f,b,d){return new g(function(){for(;;){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=b,h=f;f=h;b=a(a(h)(c))(e);d=g}else k(["unhandled case in foldl",[f,b,d]])}})}function db(a,b,d){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],d).setAttributeNS(r,w(a),w(b))&&r||l(["user","Node",[]],d)))})}function eb(a,
b){return new g(function(){return new u(n(["user","Node",[]],document.createElementNS(w(a),w(b))))})}function fb(a){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],a).parentNode))})}function gb(a,b,d){return new g(function(){return new u(n(["user","Node",[]],(l(["user","Node",[]],d)[w(a)]=w(b))&&r||l(["user","Node",[]],d)))})}function hb(a){return new g(function(){return new u(n(["user","Node",[]],document.createTextNode(w(a))))})}function ka(f,b,d){return new g(function(){if(a(d)===
r){var c=b;return new u(c)}var e=a(d);if(e instanceof p){var c=e.c,g=e.d;return x(a(a(f)(b))(c),function(b){return ka(f,b,g)})}k(["unhandled case in foldM",[f,b,d]])})}function ib(f){return new g(function(){return a(f)})}function V(f,b){return new g(function(){if(0===a(f)||a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(la(f))?Q(h("take: negative length")):a(a(s)(c))(V(y(f,1),d))}k(["unhandled case in take",[f,b]])})}function jb(f){return new g(function(){return a(f)===r?
Q(h("cycle: empty list")):function(){var b=new g(function(){return R(f,b)});return b}()})}function ca(f,b){return new g(function(){return a(a(s)(b))(ca(f,a(f)(b)))})}function ma(f,b,d,c,e){return new g(function(){return function(){return a(a(q)(a(a(J)(a(a(q)(E))(a(a(function(b){return function(c){return new g(function(){return C(na,C(kb,a(a(s)(0))(R(V(K(c,2),oa(y(1,b),D(y(1,b),a(a(lb)(b))(ib(K(2,c)))))),h([1])))))})}})(b))(d))))(a(function(b){return new g(function(){return C(mb,C(da,a(a(s)(h("0 0 1 1")))(ea(b,
h("0 .75 .25 1; 1 .75 .25 0")))))})})(d))))(a(nb)(R(a(a(a(a(f)(b))(d))(c))(e),h([e]))))}()})}function oa(a,b){return new g(function(){return H(a,y(b,a))})}function ob(f){return new g(function(){return function(){var b=new g(function(){return W(pa,0,f)});return a(pb(b))?R(ea(b,S),f):Q(h("Markup has more close elements than open"))}()})}function qa(a){return new g(function(){return new A(a)})}function W(f,b,d){return new g(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,
g=c.d,c=b;return a(a(f)(e))(W(f,c,g))}k(["unhandled case in foldr",[f,b,d]])})}function Q(a){return new g(function(){k(w(a))})}function qb(a,b){return new g(function(){return new B(a,b)})}function ra(a){return new g(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function sa(f){return new g(function(){var b=a(f);if(b instanceof p)return R(sa(b.d),h([b.c]));if(a(f)===r)return r;k(["unhandled case in reverse",[f]])})}function ea(f,b){return new g(function(){return 0===a(f)?r:a(la(f))?
Q(h("replicate: negative length")):a(a(s)(b))(ea(y(f,1),b))})}function R(a,b){return new g(function(){return I(a,b)})}function fa(f,b,d){return new g(function(){var c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=a(b);if(c instanceof p){var h=c.c,c=c.d;return a(a(s)(a(a(f)(h))(e)))(fa(f,c,g))}}return r})}function C(f,b){return new g(function(){return a(f)(b)})}function X(f,b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(a(f)(c)))(X(f,d))}k(["unhandled case in map",
[f,b]])})}function rb(f,b){return new g(function(){if(a(b)instanceof z){var d=f;return ob(d)}d=f;return a(a(q)(a(a(q)(d))(S)))(b)})}function sb(f,b){return new g(function(){return a(a(J)(a(a(q)(f))(S)))(b)})}function tb(){return new g(function(){return a(a(q)(a(a(q)(a(ub)(25)))(a(vb)(50))))(a(wb)(100))})}function Y(a,b,d,c){return new g(function(){return function(){return ma(function(b){return function(c){return function(a){return function(d){return new g(function(){return C(xb(d),V(D(c,1),C(ga(function(b){return y(d,
b)}),ca(function(c){return K(c,b)},y(d,a)))))})}}}},a,b,d,c)}()})}function Z(f,b,d,c){return new g(function(){return function(){return ma(function(b){return function(c){return function(d){return function(f){return new g(function(){return a(a(s)(d))(V(K(c,2),fa(yb,jb(h([function(b){return D(f,b)},function(b){return y(f,b)}])),ca(function(c){return K(c,b)},K(b,y(f,d))))))})}}}},f,b,d,c)}()})}function zb(a,b){return new g(function(){return new u(n(["list",[["user","Node",[]]]],l(["user","Node",[]],b).getElementsByTagName(w(a))))})}
function ta(a,b){return new g(function(){return new u(n(["list",[["user","Node",[]]]],l(["user","Node",[]],b).getElementsByClassName(w(a))))})}function ha(f,b,d){return new g(function(){return function(){return C(ia,X(function(b){return new g(function(){return a(a(q)(E))(qb(f,ra(b)))})},oa(b,D(b,d))))}()})}function Ab(f,b){return new g(function(){return new u(n(["unknown"],window.addEventListener(w(f),l(["action",[["unknown"]]],b),a(!1))))})}function ja(f,b){var d=a(b),c=f[2];if(d instanceof L){var e=
{instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a);m!==c&&(e.slot1=c);return e}return d instanceof F?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof G?e={instance:"Undefined"}:d instanceof ua?(e={instance:"Just"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof va?e={instance:"Nothing"}:d instanceof
wa?(e={instance:"Left"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof xa?(e={instance:"Right"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof ya?(e={instance:"Ratio"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof za?e={instance:"GT"}:d instanceof Aa?e={instance:"LT"}:d instanceof Ba?e={instance:"EQ"}:d instanceof L?(e={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===
f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof F?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof G?e={instance:"Undefined"}:d instanceof N?(e={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof A?(e={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof B?(e={instance:"Attribute"},c=l(["user","DString",
[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof O?(e={instance:"Property"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof z?e={instance:"Complete"}:d instanceof Ca?(e={instance:"M"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof Da?(e={instance:"L"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof Ea?(e={instance:"H"},c=a(d.a),m!==c&&(e.slot1=
c),e):d instanceof Fa?(e={instance:"V"},c=a(d.a),m!==c&&(e.slot1=c),e):d instanceof Ga?(e={instance:"A"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),c=a(d.g),m!==c&&(e.slot5=c),c=a(d.h),m!==c&&(e.slot6=c),d=a(d.m),m!==d&&(e.slot7=d),e):d instanceof Ha?(e={instance:"C"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),c=a(d.g),m!==c&&(e.slot5=c),c=a(d.h),m!==c&&(e.slot6=
c),e):d instanceof Ia?(e={instance:"S"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),e):d instanceof Ja?(e={instance:"Q"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),e):d instanceof Ka?(e={instance:"T"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof La?e={instance:"Z"}:d instanceof Ma?(e={instance:"Translate"},c=a(d.a),m!==c&&(e.slot1=c),c=
a(d.b),m!==c&&(e.slot2=c),e):d instanceof Na?(e={instance:"Rotate"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),e):d instanceof Oa?(e={instance:"Scale"},c=a(d.a),m!==c&&(e.slot1=c),e):d instanceof Pa?(e={instance:"Scale2d"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof N?(e={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof A?(e={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=
c),e):d instanceof B?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof O?(e={instance:"Property"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof z?e={instance:"Complete"}:b}function Pa(a,b){this.a=a;this.b=b}function Oa(a){this.a=a}function Na(a,b,d){this.a=a;this.b=b;this.e=d}function Ma(a,b){this.a=a;this.b=b}function La(){}function Ka(a,
b){this.a=a;this.b=b}function Ja(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function Ia(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function Ha(a,b,d,c,e,g){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=g}function Ga(a,b,d,c,e,g,h){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=g;this.m=h}function Fa(a){this.a=a}function Ea(a){this.a=a}function Da(a,b){this.a=a;this.b=b}function Ca(a,b){this.a=a;this.b=b}function z(){}function O(a,b){this.a=a;this.b=b}function B(a,b){this.a=a;this.b=
b}function A(a){this.a=a}function N(a){this.a=a}function Ba(){}function Aa(){}function za(){}function ya(a,b){this.a=a;this.b=b}function xa(a){this.a=a}function wa(a){this.a=a}function va(){}function ua(a){this.a=a}function G(){}function M(a){this.a=a}function F(){}function L(a){this.a=a}function Bb(f){return function(b){return function(d){return new g(function(){return function(){return a(a(q)(a(a(q)(a(a(q)(E))(a(Qa)(f))))(a(Cb)(b))))(a(Ra)(a(function(b){return new g(function(){return a(Db(b))?ra(b):
h("indefinite")})})(d)))}()})}}}function Eb(f){return function(b){return function(d){return new g(function(){return function(){return ka(function(b){return function(d){return new g(function(){if(a(d)instanceof B){var g=a(d).a,h=a(d).b,l=b;return db(g,h,l)}if(a(d)instanceof A)return g=a(d).a,l=b,x(eb(f,g),Sa(l));if(a(d)instanceof z)return l=b,fb(l);if(a(d)instanceof O)return g=a(d).a,h=a(d).b,l=b,gb(g,h,l);if(a(d)instanceof N)return h=a(d).a,l=b,T(x(hb(h),Sa(l)),new u(l));k(["unhandled case in go",
[b,d]])})}},d,sa(b))}()})}}}function Sa(a){return function(b){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],a).appendChild(l(["user","Node",[]],b))&&r||l(["user","Node",[]],b)))})}}function Fb(a){return function(b){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],b).appendChild(l(["user","Node",[]],a))&&r||l(["user","Node",[]],b)))})}}function Gb(a){return function(b){return new g(function(){return new u(n(["user","Node",[]],document.createElementNS(w(a),
w(b))))})}}function pa(f){return function(b){return new g(function(){var d=b;if(a(f)instanceof A)return D(d,1);d=b;return a(f)instanceof z?y(d,1):d=b})}}function t(a){return function(b){return new g(function(){return new B(a,b)})}}function Hb(f){return function(b){return new g(function(){return a(Ib)(bb(f,b))})}}function xb(f){return function(b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(c))(ba(f,d))}k(["unhandled case in intersperse",
[f,b]])})}}function Jb(f){return function(b){return function(d){return new g(function(){var c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=a(b);if(c instanceof p){var h=c.c,c=c.d;return a(a(s)(a(a(f)(h))(e)))(fa(f,c,g))}}return r})}}}function Ta(a){return function(b){return new g(function(){return I(a,b)})}}function Kb(f){return function(b){return new g(function(){var d=a(b);if(d instanceof p)return cb(f,d.c,d.d);if(a(b)===r)return Q(h("foldl1: empty list"));k(["unhandled case in foldl1",[f,b]])})}}
function Lb(f){return function(b){return function(d){return new g(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=b;return a(a(f)(e))(W(f,c,g))}k(["unhandled case in foldr",[f,b,d]])})}}}function Mb(f){return function(b){return new g(function(){var d=b,c=a(f);if(c instanceof p){var e=c.c,c=c.d;return a(a(s)(e))(I(c,d))}d=b;if(a(f)===r)return d;k(["unhandled case in conc",[f,b]])})}}function ga(f){return function(b){return new g(function(){if(a(b)===r)return r;
var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(a(f)(c)))(X(f,d))}k(["unhandled case in map",[f,b]])})}}function $(f){return function(b){return function(d){return new g(function(){return a(a(f)(d))(b)})}}}function yb(f){return function(b){return new g(function(){return a(f)(b)})}}function v(f){return function(b){return function(d){return new g(function(){return a(f)(a(b)(d))})}}}function P(a){return new g(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function Nb(f){return new g(function(){return function(){return W(function(b){return function(d){return new g(function(){return x(b,
function(b){return x(d,function(d){d=a(a(s)(b))(d);return new u(d)})})})}},new u(r),f)}()})}function a(a,b){for(;a instanceof g;)a=a.l(b);return a}function g(a){this.i=!1;this.value=a}function u(a){this.value=a}function T(a,b){return x(a,function(){return b})}function x(f,b){return new g(function(){var d=a(f,!0);return a(b)(d.value)})}function l(f,b){var d=f[0],c=f[1],e;if("action"==d)e=function(){return l(c[0],a(b,!0).value)};else if("function"==d)e=function(){var d=b,f=c[c.length-1],e=c.length;
if(1<e){for(var d=a(d,!0),g=0;g<e-1&&d instanceof Function;g++)d=a(d(n(c[g],arguments[g])),!0);e=f[1];return"action"==f[0]?l(e[0],d.value):l(f,d)}k(Error("Nullary function?"))};else if("string"==d)e=w(b);else if("list"==d){d=[];for(b=a(b);b instanceof p;)d.push(l(c[0],b.c)),b=a(b.d);e=d}else if("tuple"==d){d=[];b=a(b);for(e=0;b instanceof p;)d.push(l(c[e++],b.c)),b=a(b.d);e=d}else if("defined"==d)b=a(b),e=b instanceof G?m:ja(c[0],b.slot1);else if("nullable"==d)b=a(b),e=b instanceof F?r:ja(c[0],b.slot1);
else if("double"==d||"int"==d||"bool"==d)e=a(b);else{if("ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b instanceof g&&(b=a(b)),e=ja(f,b)):k(Error("Unhandled Fay->JS translation type: "+d))}return e}function w(f){var b="";for(f=a(f);f instanceof p;)b+=f.c,f=a(f.d);return b}function n(a,b){var d=a[0],c=a[1],e;if("action"==d)e=new u(n(c[0],b));else if("string"==d)e=h(b);else if("list"==d){var g=[],d=0;for(e=b.length;d<e;d++)g.push(n(c[0],b[d]));e=h(g)}else if("tuple"==d){g=[];d=0;for(e=
b.length;d<e;d++)g.push(n(c[d],b[d]));e=h(g)}else if("defined"==d)e=b===m?new G:new M(n(c[0],b));else if("nullable"==d)e=b===r?new F:new L(n(c[0],b));else if("int"==d)e=Math.round(b),e!==b&&k("Argument "+b+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b&&b.instance?(c=a[2],c="Nullable"===b.instance?new L(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new F:"Defined"===b.instance?new M(n(c&&
c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new G:"Just"===b.instance?new ua(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Nothing"===b.instance?new va:"Left"===b.instance?new wa(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Right"===b.instance?new xa(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Ratio"===b.instance?new ya(b.slot1,b.slot2):"GT"===b.instance?new za:"LT"===b.instance?
new Aa:"EQ"===b.instance?new Ba:"Nullable"===b.instance?new L(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new F:"Defined"===b.instance?new M(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new G:"Content"===b.instance?new N(n(["user","DString",[]],b.slot1)):"Element"===b.instance?new A(n(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new B(n(["user","DString",[]],b.slot1),n(["user","DString",[]],
b.slot2)):"Property"===b.instance?new O(n(["user","DString",[]],b.slot1),n(["user","DString",[]],b.slot2)):"Complete"===b.instance?new z:"M"===b.instance?new Ca(b.slot1,b.slot2):"L"===b.instance?new Da(b.slot1,b.slot2):"H"===b.instance?new Ea(b.slot1):"V"===b.instance?new Fa(b.slot1):"A"===b.instance?new Ga(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6,b.slot7):"C"===b.instance?new Ha(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6):"S"===b.instance?new Ia(b.slot1,b.slot2,b.slot3,b.slot4):"Q"===
b.instance?new Ja(b.slot1,b.slot2,b.slot3,b.slot4):"T"===b.instance?new Ka(b.slot1,b.slot2):"Z"===b.instance?new La:"Translate"===b.instance?new Ma(b.slot1,b.slot2):"Rotate"===b.instance?new Na(b.slot1,b.slot2,b.slot3):"Scale"===b.instance?new Oa(b.slot1):"Scale2d"===b.instance?new Pa(b.slot1,b.slot2):"Content"===b.instance?new N(n(["user","DString",[]],b.slot1)):"Element"===b.instance?new A(n(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new B(n(["user","DString",[]],b.slot1),n(["user",
"DString",[]],b.slot2)):"Property"===b.instance?new O(n(["user","DString",[]],b.slot1),n(["user","DString",[]],b.slot2)):"Complete"===b.instance?new z:b):c=b,e=c):k(Error("Unhandled JS->Fay translation type: "+d))}return e}function p(a,b){this.c=a;this.d=b}function h(a){for(var b=r,d=a.length-1;0<=d;d--)b=new p(a[d],b);return b}function s(a){return function(b){return new p(a,b)}}function K(f,b){return new g(function(){return a(f)*a(b)})}function D(f,b){return new g(function(){return a(f)+a(b)})}function y(f,
b){return new g(function(){return a(f)-a(b)})}function lb(f){return function(b){return new g(function(){return a(f)/a(b)})}}function Db(f){return new g(function(){return a(f)>a(0)})}function la(f){return new g(function(){return a(f)<a(0)})}function pb(f){return new g(function(){return a(f)>=a(0)})}g.prototype.l=function(a){return a?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var Ib=new g(function(){return a(Lb(Mb))(r)}),Ob=new g(function(){return a(v(function(f){return a(v(function(b){return a(v(Nb))(b)}))(f)}))(Jb)}),
S=new g(function(){return new z}),E=new g(function(){return r}),q=new g(function(){return $(s)}),J=new g(function(){return $(Ta)}),Pb=new g(function(){return new u(n(["user","Node",[]],document.documentElement))}),Qa=new g(function(){return t(h("attributeName"))}),Ua=new g(function(){return t(h("calcMode"))}),aa=new g(function(){return t(h("fill"))}),Va=new g(function(){return t(h("keySplines"))}),na=new g(function(){return t(h("keyTimes"))}),Ra=new g(function(){return t(h("repeatCount"))}),Wa=new g(function(){return t(h("values"))}),
Qb=new g(function(){return qa(h("animate"))}),Rb=new g(function(){return qa(h("circle"))}),Xa=new g(function(){return h("http://www.w3.org/2000/svg")}),ub=new g(function(){return a(v(function(f){return a(a(q)(a(a(q)(E))(Rb)))(f)}))(Sb)}),Ya=new g(function(){return a(v(function(f){return a(v(function(b){return a(v(function(b){return a(a(J)(a(a(q)(E))(Qb)))(b)}))(b)}))(f)}))(Bb)}),Tb=new g(function(){return a(v(Wa))(da)}),nb=new g(function(){return a(v(Tb))(ga(P))}),mb=new g(function(){return a(v(function(f){return a(a(q)(a(a(q)(E))(a(Ua)(h("spline")))))(f)}))(Va)}),
da=new g(function(){return Hb(h(";"))}),kb=new g(function(){return a(v(da))(ga(P))}),Za=new g(function(){return Eb(Xa)}),Ub=new g(function(){return Gb(Xa)}),ia=new g(function(){return a(Ob)(Za)}),$a=new g(function(){return t(h("class"))}),vb=new g(function(){return a(v(t(h("cx"))))(P)}),wb=new g(function(){return a(v(t(h("cy"))))(P)}),Cb=new g(function(){return a(v(t(h("dur"))))(P)}),Sb=new g(function(){return a(v(t(h("r"))))(P)}),t=function(a){return function(b){return new g(function(){return new B(a,
b)})}},S=new g(function(){return new z}),E=new g(function(){return r}),q=new g(function(){return $(s)}),J=new g(function(){return $(Ta)}),pa=function(f){return function(b){return new g(function(){var d=b;if(a(f)instanceof A)return D(d,1);d=b;return a(f)instanceof z?y(d,1):d=b})}},Qa=new g(function(){return t(h("attributeName"))}),Ua=new g(function(){return t(h("calcMode"))}),aa=new g(function(){return t(h("fill"))}),Va=new g(function(){return t(h("keySplines"))}),na=new g(function(){return t(h("keyTimes"))}),
Ra=new g(function(){return t(h("repeatCount"))}),Wa=new g(function(){return t(h("values"))}),Vb=new g(function(){function f(b){return new g(function(){return rb(a(a(q)(a(a(q)(sb(a(a(q)(a(a(q)(a(a(J)(a(a(q)(tb()))(a(aa)(b))))(a(a(a(Ya)(h("cy")))(2))(1))))(a(aa)(h("freeze")))))(a($a)(h("drop"))),a(a(a(Ya)(h("r")))(0.75))(1))))(a(aa)(h("freeze")))))(a($a)(h("grow"))),S)})}var b=new g(function(){return C(Kb(J),X(f,e))}),d=new g(function(){return h([Y(0.4,3,100,400),Z(0.35,3,100,400),Y(0.75,4,100,400),
Z(0.65,4,100,400)])}),c=new g(function(){return h([Y(0.5,5,25,50),Z(0.45,5,25,50),Y(0.85,6,25,50),Z(0.75,6,25,50)])}),e=new g(function(){return h([h("lightpink"),h("lightblue"),h("lightsalmon"),h("lightgreen")])});return x(x(a(Ub)(h("g")),a(Za)(b)),function(b){return T(x(zb(h("circle"),b),ha(h("cx"),50,100)),T(x(x(ta(h("drop"),b),a(ia)(d)),ha(h("begin"),0,2)),T(x(x(ta(h("grow"),b),a(ia)(c)),ha(h("begin"),9,0.75)),T(x(Pb,Fb(b)),new u(r)))))})}),Wb=new g(function(){return Ab(h("load"),Vb)}),L=U("a"),
F=function(){},M=U("a"),G=function(){},N=U("a"),A=U("a"),B=function(a,b){this.a=a;this.b=b},O=function(a,b){this.a=a;this.b=b},z=function(){};this.j=Wb;this.k=a};ab.k(ab.j);
