function k(H){throw H;}var m=void 0,r=null;function T(H){return function(I){this[H]=I}}
var $a=new function(){function H(f,b){return new g(function(){return a(a(s)(f))(H(D(f,b),b))})}function I(f,b){return new g(function(){var d=b,c=a(f);if(c instanceof p){var e=c.c,c=c.d;return a(a(s)(e))(I(c,d))}d=b;if(a(f)===r)return d;k(["unhandled case in conc",[f,b]])})}function aa(f,b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(f))(a(a(s)(c))(aa(f,d)))}k(["unhandled case in prependToAll",[f,b]])})}function ab(f,b){return new g(function(){if(a(b)===
r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(c))(aa(f,d))}k(["unhandled case in intersperse",[f,b]])})}function bb(f,b,d){return new g(function(){for(;;){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=b,h=f;f=h;b=a(a(h)(c))(e);d=g}else k(["unhandled case in foldl",[f,b,d]])}})}function cb(a,b,d){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],d).setAttributeNS(r,x(a),x(b))&&r||l(["user","Node",[]],d)))})}function db(a,
b){return new g(function(){return new u(n(["user","Node",[]],document.createElementNS(x(a),x(b))))})}function eb(a){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],a).parentNode))})}function fb(a){return new g(function(){return new u(n(["user","Node",[]],document.createTextNode(x(a))))})}function ja(f,b,d){return new g(function(){if(a(d)===r){var c=b;return new u(c)}var e=a(d);if(e instanceof p){var c=e.c,g=e.d;return w(a(a(f)(b))(c),function(b){return ja(f,b,g)})}k(["unhandled case in foldM",
[f,b,d]])})}function gb(f){return new g(function(){return a(f)})}function U(f,b){return new g(function(){if(0===a(f)||a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(ka(f))?P(h("take: negative length")):a(a(s)(c))(U(y(f,1),d))}k(["unhandled case in take",[f,b]])})}function hb(f){return new g(function(){return a(f)===r?P(h("cycle: empty list")):function(){var b=new g(function(){return Q(f,b)});return b}()})}function ba(f,b){return new g(function(){return a(a(s)(b))(ba(f,a(f)(b)))})}
function la(f,b,d,c,e){return new g(function(){return function(){return a(a(q)(a(a(J)(a(a(q)(E))(a(a(function(b){return function(c){return new g(function(){return C(ma,C(ib,a(a(s)(0))(Q(U(K(c,2),na(y(1,b),D(y(1,b),a(a(jb)(b))(gb(K(2,c)))))),h([1])))))})}})(b))(d))))(a(function(b){return new g(function(){return C(kb,C(ca,a(a(s)(h("0 0 1 1")))(da(b,h("0 .75 .25 1; 1 .75 .25 0")))))})})(d))))(a(lb)(Q(a(a(a(a(f)(b))(d))(c))(e),h([e]))))}()})}function na(a,b){return new g(function(){return H(a,y(b,a))})}
function mb(f){return new g(function(){return function(){var b=new g(function(){return V(oa,0,f)});return a(nb(b))?Q(da(b,R),f):P(h("Markup has more close elements than open"))}()})}function pa(a){return new g(function(){return new A(a)})}function V(f,b,d){return new g(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=b;return a(a(f)(e))(V(f,c,g))}k(["unhandled case in foldr",[f,b,d]])})}function P(a){return new g(function(){k(x(a))})}function ob(a,b){return new g(function(){return new B(a,
b)})}function qa(a){return new g(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function ra(f){return new g(function(){var b=a(f);if(b instanceof p)return Q(ra(b.d),h([b.c]));if(a(f)===r)return r;k(["unhandled case in reverse",[f]])})}function da(f,b){return new g(function(){return 0===a(f)?r:a(ka(f))?P(h("replicate: negative length")):a(a(s)(b))(da(y(f,1),b))})}function Q(a,b){return new g(function(){return I(a,b)})}function ea(f,b,d){return new g(function(){var c=a(d);if(c instanceof
p){var e=c.c,g=c.d,c=a(b);if(c instanceof p){var h=c.c,c=c.d;return a(a(s)(a(a(f)(h))(e)))(ea(f,c,g))}}return r})}function C(f,b){return new g(function(){return a(f)(b)})}function W(f,b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(a(f)(c)))(W(f,d))}k(["unhandled case in map",[f,b]])})}function pb(f,b){return new g(function(){if(a(b)instanceof z){var d=f;return mb(d)}d=f;return a(a(q)(a(a(q)(d))(R)))(b)})}function qb(f,b){return new g(function(){return a(a(J)(a(a(q)(f))(R)))(b)})}
function rb(){return new g(function(){return a(a(q)(a(a(q)(a(sb)(25)))(a(tb)(50))))(a(ub)(100))})}function X(a,b,d,c){return new g(function(){return function(){return la(function(b){return function(c){return function(a){return function(d){return new g(function(){return C(vb(d),U(D(c,1),C(fa(function(b){return y(d,b)}),ba(function(c){return K(c,b)},y(d,a)))))})}}}},a,b,d,c)}()})}function Y(f,b,d,c){return new g(function(){return function(){return la(function(b){return function(c){return function(d){return function(f){return new g(function(){return a(a(s)(d))(U(K(c,
2),ea(wb,hb(h([function(b){return D(f,b)},function(b){return y(f,b)}])),ba(function(c){return K(c,b)},K(b,y(f,d))))))})}}}},f,b,d,c)}()})}function xb(a,b){return new g(function(){return new u(n(["list",[["user","Node",[]]]],l(["user","Node",[]],b).getElementsByTagName(x(a))))})}function sa(a,b){return new g(function(){return new u(n(["list",[["user","Node",[]]]],l(["user","Node",[]],b).getElementsByClassName(x(a))))})}function ga(f,b,d){return new g(function(){return function(){return C(ha,W(function(b){return new g(function(){return a(a(q)(E))(ob(f,
qa(b)))})},na(b,D(b,d))))}()})}function yb(f,b){return new g(function(){return new u(n(["unknown"],window.addEventListener(x(f),l(["action",[["unknown"]]],b),a(!1))))})}function ia(f,b){var d=a(b),c=f[2];if(d instanceof L){var e={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a);m!==c&&(e.slot1=c);return e}return d instanceof F?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&
(e.slot1=c),e):d instanceof G?e={instance:"Undefined"}:d instanceof ta?(e={instance:"Just"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof ua?e={instance:"Nothing"}:d instanceof va?(e={instance:"Left"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof wa?(e={instance:"Right"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof xa?(e={instance:"Ratio"},
c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof ya?e={instance:"GT"}:d instanceof za?e={instance:"LT"}:d instanceof Aa?e={instance:"EQ"}:d instanceof L?(e={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof F?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===f[0]?["automatic"]:["unknown"],d.a),m!==c&&(e.slot1=c),e):d instanceof G?e={instance:"Undefined"}:d instanceof
N?(e={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof A?(e={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof B?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof z?e={instance:"Complete"}:d instanceof Ba?(e={instance:"M"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof Ca?(e={instance:"L"},c=a(d.a),m!==c&&(e.slot1=
c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof Da?(e={instance:"H"},c=a(d.a),m!==c&&(e.slot1=c),e):d instanceof Ea?(e={instance:"V"},c=a(d.a),m!==c&&(e.slot1=c),e):d instanceof Fa?(e={instance:"A"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),c=a(d.g),m!==c&&(e.slot5=c),c=a(d.h),m!==c&&(e.slot6=c),d=a(d.m),m!==d&&(e.slot7=d),e):d instanceof Ga?(e={instance:"C"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&
(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),c=a(d.g),m!==c&&(e.slot5=c),c=a(d.h),m!==c&&(e.slot6=c),e):d instanceof Ha?(e={instance:"S"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),e):d instanceof Ia?(e={instance:"Q"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),c=a(d.f),m!==c&&(e.slot4=c),e):d instanceof Ja?(e={instance:"T"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof
Ka?e={instance:"Z"}:d instanceof La?(e={instance:"Translate"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof Ma?(e={instance:"Rotate"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),c=a(d.e),m!==c&&(e.slot3=c),e):d instanceof Na?(e={instance:"Scale"},c=a(d.a),m!==c&&(e.slot1=c),e):d instanceof Oa?(e={instance:"Scale2d"},c=a(d.a),m!==c&&(e.slot1=c),c=a(d.b),m!==c&&(e.slot2=c),e):d instanceof N?(e={instance:"Content"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=
c),e):d instanceof A?(e={instance:"Element"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),e):d instanceof B?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),m!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),m!==c&&(e.slot2=c),e):d instanceof z?e={instance:"Complete"}:b}function Oa(a,b){this.a=a;this.b=b}function Na(a){this.a=a}function Ma(a,b,d){this.a=a;this.b=b;this.e=d}function La(a,b){this.a=a;this.b=b}function Ka(){}function Ja(a,b){this.a=a;this.b=b}function Ia(a,b,d,c){this.a=
a;this.b=b;this.e=d;this.f=c}function Ha(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function Ga(a,b,d,c,e,g){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=g}function Fa(a,b,d,c,e,g,h){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=g;this.m=h}function Ea(a){this.a=a}function Da(a){this.a=a}function Ca(a,b){this.a=a;this.b=b}function Ba(a,b){this.a=a;this.b=b}function z(){}function B(a,b){this.a=a;this.b=b}function A(a){this.a=a}function N(a){this.a=a}function Aa(){}function za(){}function ya(){}
function xa(a,b){this.a=a;this.b=b}function wa(a){this.a=a}function va(a){this.a=a}function ua(){}function ta(a){this.a=a}function G(){}function M(a){this.a=a}function F(){}function L(a){this.a=a}function zb(f){return function(b){return function(d){return new g(function(){return function(){return a(a(q)(a(a(q)(a(a(q)(E))(a(Pa)(f))))(a(Ab)(b))))(a(Qa)(a(function(b){return new g(function(){return a(Bb(b))?qa(b):h("indefinite")})})(d)))}()})}}}function Cb(f){return function(b){return function(d){return new g(function(){return function(){return ja(function(b){return function(d){return new g(function(){if(a(d)instanceof
B){var g=a(d).a,h=a(d).b,l=b;return cb(g,h,l)}if(a(d)instanceof A)return g=a(d).a,l=b,w(db(f,g),Ra(l));if(a(d)instanceof z)return l=b,eb(l);if(a(d)instanceof N)return h=a(d).a,l=b,S(w(fb(h),Ra(l)),new u(l));k(["unhandled case in go",[b,d]])})}},d,ra(b))}()})}}}function Ra(a){return function(b){return new g(function(){return new u(n(["user","Node",[]],l(["user","Node",[]],a).appendChild(l(["user","Node",[]],b))&&r||l(["user","Node",[]],b)))})}}function Db(a){return function(b){return new g(function(){return new u(n(["user",
"Node",[]],l(["user","Node",[]],b).appendChild(l(["user","Node",[]],a))&&r||l(["user","Node",[]],b)))})}}function Eb(a){return function(b){return new g(function(){return new u(n(["user","Node",[]],document.createElementNS(x(a),x(b))))})}}function oa(f){return function(b){return new g(function(){var d=b;if(a(f)instanceof A)return D(d,1);d=b;return a(f)instanceof z?y(d,1):d=b})}}function t(a){return function(b){return new g(function(){return new B(a,b)})}}function Fb(f){return function(b){return new g(function(){return a(Gb)(ab(f,
b))})}}function vb(f){return function(b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(c))(aa(f,d))}k(["unhandled case in intersperse",[f,b]])})}}function Hb(f){return function(b){return function(d){return new g(function(){var c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=a(b);if(c instanceof p){var h=c.c,c=c.d;return a(a(s)(a(a(f)(h))(e)))(ea(f,c,g))}}return r})}}}function Sa(a){return function(b){return new g(function(){return I(a,b)})}}function Ib(f){return function(b){return new g(function(){var d=
a(b);if(d instanceof p)return bb(f,d.c,d.d);if(a(b)===r)return P(h("foldl1: empty list"));k(["unhandled case in foldl1",[f,b]])})}}function Jb(f){return function(b){return function(d){return new g(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof p){var e=c.c,g=c.d,c=b;return a(a(f)(e))(V(f,c,g))}k(["unhandled case in foldr",[f,b,d]])})}}}function Kb(f){return function(b){return new g(function(){var d=b,c=a(f);if(c instanceof p){var e=c.c,c=c.d;return a(a(s)(e))(I(c,d))}d=b;if(a(f)===
r)return d;k(["unhandled case in conc",[f,b]])})}}function fa(f){return function(b){return new g(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof p){var c=d.c,d=d.d;return a(a(s)(a(f)(c)))(W(f,d))}k(["unhandled case in map",[f,b]])})}}function Z(f){return function(b){return function(d){return new g(function(){return a(a(f)(d))(b)})}}}function wb(f){return function(b){return new g(function(){return a(f)(b)})}}function v(f){return function(b){return function(d){return new g(function(){return a(f)(a(b)(d))})}}}
function O(a){return new g(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function Lb(f){return new g(function(){return function(){return V(function(b){return function(d){return new g(function(){return w(b,function(b){return w(d,function(d){d=a(a(s)(b))(d);return new u(d)})})})}},new u(r),f)}()})}function a(a,b){for(;a instanceof g;)a=a.l(b);return a}function g(a){this.i=!1;this.value=a}function u(a){this.value=a}function S(a,b){return w(a,function(){return b})}function w(f,b){return new g(function(){var d=
a(f,!0);return a(b)(d.value)})}function l(f,b){var d=f[0],c=f[1],e;if("action"==d)e=function(){return l(c[0],a(b,!0).value)};else if("function"==d)e=function(){var d=b,f=c[c.length-1],e=c.length;if(1<e){for(var d=a(d,!0),g=0;g<e-1&&d instanceof Function;g++)d=a(d(n(c[g],arguments[g])),!0);e=f[1];return"action"==f[0]?l(e[0],d.value):l(f,d)}k(Error("Nullary function?"))};else if("string"==d)e=x(b);else if("list"==d){d=[];for(b=a(b);b instanceof p;)d.push(l(c[0],b.c)),b=a(b.d);e=d}else if("tuple"==d){d=
[];b=a(b);for(e=0;b instanceof p;)d.push(l(c[e++],b.c)),b=a(b.d);e=d}else if("defined"==d)b=a(b),e=b instanceof G?m:ia(c[0],b.slot1);else if("nullable"==d)b=a(b),e=b instanceof F?r:ia(c[0],b.slot1);else if("double"==d||"int"==d||"bool"==d)e=a(b);else{if("ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b instanceof g&&(b=a(b)),e=ia(f,b)):k(Error("Unhandled Fay->JS translation type: "+d))}return e}function x(f){var b="";for(f=a(f);f instanceof p;)b+=f.c,f=a(f.d);return b}function n(a,b){var d=
a[0],c=a[1],e;if("action"==d)e=new u(n(c[0],b));else if("string"==d)e=h(b);else if("list"==d){var g=[],d=0;for(e=b.length;d<e;d++)g.push(n(c[0],b[d]));e=h(g)}else if("tuple"==d){g=[];d=0;for(e=b.length;d<e;d++)g.push(n(c[d],b[d]));e=h(g)}else if("defined"==d)e=b===m?new G:new M(n(c[0],b));else if("nullable"==d)e=b===r?new F:new L(n(c[0],b));else if("int"==d)e=Math.round(b),e!==b&&k("Argument "+b+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return b;"automatic"==d||
"user"==d?(b&&b.instance?(c=a[2],c="Nullable"===b.instance?new L(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new F:"Defined"===b.instance?new M(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new G:"Just"===b.instance?new ta(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Nothing"===b.instance?new ua:"Left"===b.instance?new va(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],
b.slot1)):"Right"===b.instance?new wa(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Ratio"===b.instance?new xa(b.slot1,b.slot2):"GT"===b.instance?new ya:"LT"===b.instance?new za:"EQ"===b.instance?new Aa:"Nullable"===b.instance?new L(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new F:"Defined"===b.instance?new M(n(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new G:"Content"===b.instance?
new N(n(["user","DString",[]],b.slot1)):"Element"===b.instance?new A(n(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new B(n(["user","DString",[]],b.slot1),n(["user","DString",[]],b.slot2)):"Complete"===b.instance?new z:"M"===b.instance?new Ba(b.slot1,b.slot2):"L"===b.instance?new Ca(b.slot1,b.slot2):"H"===b.instance?new Da(b.slot1):"V"===b.instance?new Ea(b.slot1):"A"===b.instance?new Fa(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6,b.slot7):"C"===b.instance?new Ga(b.slot1,b.slot2,b.slot3,
b.slot4,b.slot5,b.slot6):"S"===b.instance?new Ha(b.slot1,b.slot2,b.slot3,b.slot4):"Q"===b.instance?new Ia(b.slot1,b.slot2,b.slot3,b.slot4):"T"===b.instance?new Ja(b.slot1,b.slot2):"Z"===b.instance?new Ka:"Translate"===b.instance?new La(b.slot1,b.slot2):"Rotate"===b.instance?new Ma(b.slot1,b.slot2,b.slot3):"Scale"===b.instance?new Na(b.slot1):"Scale2d"===b.instance?new Oa(b.slot1,b.slot2):"Content"===b.instance?new N(n(["user","DString",[]],b.slot1)):"Element"===b.instance?new A(n(["user","DString",
[]],b.slot1)):"Attribute"===b.instance?new B(n(["user","DString",[]],b.slot1),n(["user","DString",[]],b.slot2)):"Complete"===b.instance?new z:b):c=b,e=c):k(Error("Unhandled JS->Fay translation type: "+d))}return e}function p(a,b){this.c=a;this.d=b}function h(a){for(var b=r,d=a.length-1;0<=d;d--)b=new p(a[d],b);return b}function s(a){return function(b){return new p(a,b)}}function K(f,b){return new g(function(){return a(f)*a(b)})}function D(f,b){return new g(function(){return a(f)+a(b)})}function y(f,
b){return new g(function(){return a(f)-a(b)})}function jb(f){return function(b){return new g(function(){return a(f)/a(b)})}}function Bb(f){return new g(function(){return a(f)>a(0)})}function ka(f){return new g(function(){return a(f)<a(0)})}function nb(f){return new g(function(){return a(f)>=a(0)})}g.prototype.l=function(a){return a?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var Gb=new g(function(){return a(Jb(Kb))(r)}),Mb=new g(function(){return a(v(function(f){return a(v(function(b){return a(v(Lb))(b)}))(f)}))(Hb)}),
R=new g(function(){return new z}),E=new g(function(){return r}),q=new g(function(){return Z(s)}),J=new g(function(){return Z(Sa)}),Nb=new g(function(){return new u(n(["user","Node",[]],document.documentElement))}),Pa=new g(function(){return t(h("attributeName"))}),Ta=new g(function(){return t(h("calcMode"))}),$=new g(function(){return t(h("fill"))}),Ua=new g(function(){return t(h("keySplines"))}),ma=new g(function(){return t(h("keyTimes"))}),Qa=new g(function(){return t(h("repeatCount"))}),Va=new g(function(){return t(h("values"))}),
Ob=new g(function(){return pa(h("animate"))}),Pb=new g(function(){return pa(h("circle"))}),Wa=new g(function(){return h("http://www.w3.org/2000/svg")}),sb=new g(function(){return a(v(function(f){return a(a(q)(a(a(q)(E))(Pb)))(f)}))(Qb)}),Xa=new g(function(){return a(v(function(f){return a(v(function(b){return a(v(function(b){return a(a(J)(a(a(q)(E))(Ob)))(b)}))(b)}))(f)}))(zb)}),Rb=new g(function(){return a(v(Va))(ca)}),lb=new g(function(){return a(v(Rb))(fa(O))}),kb=new g(function(){return a(v(function(f){return a(a(q)(a(a(q)(E))(a(Ta)(h("spline")))))(f)}))(Ua)}),
ca=new g(function(){return Fb(h(";"))}),ib=new g(function(){return a(v(ca))(fa(O))}),Ya=new g(function(){return Cb(Wa)}),Sb=new g(function(){return Eb(Wa)}),ha=new g(function(){return a(Mb)(Ya)}),Za=new g(function(){return t(h("class"))}),tb=new g(function(){return a(v(t(h("cx"))))(O)}),ub=new g(function(){return a(v(t(h("cy"))))(O)}),Ab=new g(function(){return a(v(t(h("dur"))))(O)}),Qb=new g(function(){return a(v(t(h("r"))))(O)}),t=function(a){return function(b){return new g(function(){return new B(a,
b)})}},R=new g(function(){return new z}),E=new g(function(){return r}),q=new g(function(){return Z(s)}),J=new g(function(){return Z(Sa)}),oa=function(f){return function(b){return new g(function(){var d=b;if(a(f)instanceof A)return D(d,1);d=b;return a(f)instanceof z?y(d,1):d=b})}},Pa=new g(function(){return t(h("attributeName"))}),Ta=new g(function(){return t(h("calcMode"))}),$=new g(function(){return t(h("fill"))}),Ua=new g(function(){return t(h("keySplines"))}),ma=new g(function(){return t(h("keyTimes"))}),
Qa=new g(function(){return t(h("repeatCount"))}),Va=new g(function(){return t(h("values"))}),Tb=new g(function(){function f(b){return new g(function(){return pb(a(a(q)(a(a(q)(qb(a(a(q)(a(a(q)(a(a(J)(a(a(q)(rb()))(a($)(b))))(a(a(a(Xa)(h("cy")))(2))(1))))(a($)(h("freeze")))))(a(Za)(h("drop"))),a(a(a(Xa)(h("r")))(0.75))(1))))(a($)(h("freeze")))))(a(Za)(h("grow"))),R)})}var b=new g(function(){return C(Ib(J),W(f,e))}),d=new g(function(){return h([X(0.4,3,100,400),Y(0.35,3,100,400),X(0.75,4,100,400),Y(0.65,
4,100,400)])}),c=new g(function(){return h([X(0.5,5,25,50),Y(0.45,5,25,50),X(0.85,6,25,50),Y(0.75,6,25,50)])}),e=new g(function(){return h([h("lightpink"),h("lightblue"),h("lightsalmon"),h("lightgreen")])});return w(w(a(Sb)(h("g")),a(Ya)(b)),function(b){return S(w(xb(h("circle"),b),ga(h("cx"),50,100)),S(w(w(sa(h("drop"),b),a(ha)(d)),ga(h("begin"),0,2)),S(w(w(sa(h("grow"),b),a(ha)(c)),ga(h("begin"),9,0.75)),S(w(Nb,Db(b)),new u(r)))))})}),Ub=new g(function(){return yb(h("load"),Tb)}),L=T("a"),F=function(){},
M=T("a"),G=function(){},N=T("a"),A=T("a"),B=function(a,b){this.a=a;this.b=b},z=function(){};this.j=Ub;this.k=a};$a.k($a.j);
