function k(D){throw D;}var n=void 0,r=null;function J(D){return function(P){this[D]=P}}
var Pa=new function(){function D(g,b){return new f(function(){var d=b,c=a(g);if(c instanceof s){var e=c.c,c=c.d;return a(a(w)(e))(D(c,d))}d=b;if(a(g)===r)return d;k(["unhandled case in conc",[g,b]])})}function P(g,b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(w)(g))(a(a(w)(c))(P(g,d)))}k(["unhandled case in prependToAll",[g,b]])})}function Qa(g,b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(w)(c))(P(g,
d))}k(["unhandled case in intersperse",[g,b]])})}function Ra(a,b,d){return new f(function(){return new y(l(["user","Node",[]],m(["user","Node",[]],d).setAttributeNS(r,B(a),B(b))&&r||m(["user","Node",[]],d)))})}function Sa(a,b){return new f(function(){return new y(l(["user","Node",[]],document.createElementNS(B(a),B(b))))})}function Ta(a){return new f(function(){return new y(l(["user","Node",[]],m(["user","Node",[]],a).parentNode))})}function Ua(a){return new f(function(){return new y(l(["user","Node",
[]],document.createTextNode(B(a))))})}function $(g,b,d){return new f(function(){if(a(d)===r){var c=b;return new y(c)}var e=a(d);if(e instanceof s){var c=e.c,f=e.d;return N(a(a(g)(b))(c),function(c){return $(g,c,f)})}k(["unhandled case in foldM",[g,b,d]])})}function Va(){return new f(function(){return a(a(p)(a(a(p)(a(a(p)(K))(aa)))(a(Wa)(50))))(a(Xa)(10))})}function Ya(){return new f(function(){return a(a(p)(a(a(p)(Va()))(a(ba)(20))))(a(ca)(20))})}function da(g,b){return new f(function(){if(a(b)===
r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(w)(a(g)(c)))(da(g,d))}k(["unhandled case in map",[g,b]])})}function Za(a){return new f(function(){return new z(a)})}function $a(g){return new f(function(){return function(){var b=new f(function(){return S(Q,0,g)});return a(ab(b))?A(T(b,F),g):ea(h("Markup has more close elements than open"))}()})}function S(g,b,d){return new f(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=b;return a(a(g)(e))(S(g,
c,f))}k(["unhandled case in foldr",[g,b,d]])})}function ea(a){return new f(function(){k(B(a))})}function bb(a){return new f(function(){var b=JSON.stringify(m(["automatic"],a));return h(b)})}function U(g){return new f(function(){var b=a(g);if(b instanceof s)return A(U(b.d),h([b.c]));if(a(g)===r)return r;k(["unhandled case in reverse",[g]])})}function fa(g,b,d){return new f(function(){var c=a(a(w)(b)),e;if(a(d)===r)e=r;else{var f=a(d);f instanceof s?(e=f.c,f=f.d,e=fa(g,a(a(g)(b))(e),f)):k(["unhandled case",
d])}return c(e)})}function T(g,b){return new f(function(){return 0===a(g)?r:a(cb(g))?ea(h("replicate: negative length")):a(a(w)(b))(T(R(g),b))})}function A(a,b){return new f(function(){return D(a,b)})}function ga(g,b,d){return new f(function(){var c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=a(b);if(c instanceof s){var h=c.c,c=c.d;return a(a(w)(a(a(g)(h))(e)))(ga(g,c,f))}}return r})}function E(a){return new f(function(){return new u(a)})}function db(g,b){return new f(function(){return new y(l(["unknown"],
window.addEventListener(B(g),m(["action",[["unknown"]]],b),a(!1))))})}function ha(g,b){return new f(function(){return a(a(p)(g))(Za(b))})}function ia(g,b){return new f(function(){if(a(b)instanceof t){var d=g;return $a(d)}d=g;return a(a(p)(a(a(p)(d))(F)))(b)})}function eb(g,b){return new f(function(){return a(a(O)(a(a(p)(g))(F)))(b)})}function fb(){return new f(function(){return a(a(p)(a(a(p)(a(gb)(40)))(a(hb)(100))))(a(ib)(100))})}function jb(){return new f(function(){return Ya()})}function ja(g,
b){return new f(function(){return a(g)(b)})}function kb(g){return new f(function(){return function(){function b(c){return new f(function(){if(a(c)instanceof u){var b=a(c).a;return A(h("<"),A(b,h(">")))}if(a(c)instanceof x){var b=a(c).a,d=a(c).b;return A(b,A(h('="'),A(d,h('"'))))}if(a(c)instanceof z)return b=a(c).a,A(h('"'),A(b,h('"')));if(a(c)instanceof t)return h("<--");k(["unhandled case in go",[c]])})}var d=new f(function(){return U(g)});return ja(ka,ga(function(c){return function(d){return new f(function(){return A(T(lb(c),
" "),A(a(b)(d),h("\n")))})}},new f(function(){return fa(G(Q),0,d)}),d))}()})}function V(g,b){var d=a(b),c=g[2];if(d instanceof L){var e={instance:"Nullable"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a);n!==c&&(e.slot1=c);return e}return d instanceof H?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof I?e={instance:"Undefined"}:d instanceof la?(e={instance:"Just"},c=
m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof ma?e={instance:"Nothing"}:d instanceof na?(e={instance:"Left"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof oa?(e={instance:"Right"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof pa?(e={instance:"Ratio"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof qa?e={instance:"GT"}:
d instanceof ra?e={instance:"LT"}:d instanceof sa?e={instance:"EQ"}:d instanceof L?(e={instance:"Nullable"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof H?e={instance:"Null"}:d instanceof M?(e={instance:"Defined"},c=m(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof I?e={instance:"Undefined"}:d instanceof z?(e={instance:"Content"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof
u?(e={instance:"Element"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof x?(e={instance:"Attribute"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=m(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:d instanceof ta?(e={instance:"M"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof ua?(e={instance:"L"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof va?(e={instance:"H"},c=a(d.a),n!==c&&(e.slot1=
c),e):d instanceof wa?(e={instance:"V"},c=a(d.a),n!==c&&(e.slot1=c),e):d instanceof xa?(e={instance:"A"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),c=a(d.g),n!==c&&(e.slot5=c),c=a(d.h),n!==c&&(e.slot6=c),d=a(d.m),n!==d&&(e.slot7=d),e):d instanceof ya?(e={instance:"C"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),c=a(d.g),n!==c&&(e.slot5=c),c=a(d.h),n!==c&&(e.slot6=
c),e):d instanceof za?(e={instance:"S"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),e):d instanceof Aa?(e={instance:"Q"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),e):d instanceof Ba?(e={instance:"T"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof Ca?e={instance:"Z"}:d instanceof Da?(e={instance:"Translate"},c=a(d.a),n!==c&&(e.slot1=c),c=
a(d.b),n!==c&&(e.slot2=c),e):d instanceof Ea?(e={instance:"Rotate"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),e):d instanceof Fa?(e={instance:"Scale"},c=a(d.a),n!==c&&(e.slot1=c),e):d instanceof Ga?(e={instance:"Scale2d"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof z?(e={instance:"Content"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof u?(e={instance:"Element"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=
c),e):d instanceof x?(e={instance:"Attribute"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=m(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:d instanceof z?(e={instance:"Content"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof u?(e={instance:"Element"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof x?(e={instance:"Attribute"},c=m(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=m(["user","DString",[]],d.b),n!==c&&
(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:b}function Ga(a,b){this.a=a;this.b=b}function Fa(a){this.a=a}function Ea(a,b,d){this.a=a;this.b=b;this.e=d}function Da(a,b){this.a=a;this.b=b}function Ca(){}function Ba(a,b){this.a=a;this.b=b}function Aa(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function za(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function ya(a,b,d,c,e,f){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=f}function xa(a,b,d,c,e,f,h){this.a=a;this.b=b;this.e=d;this.f=c;
this.g=e;this.h=f;this.m=h}function wa(a){this.a=a}function va(a){this.a=a}function ua(a,b){this.a=a;this.b=b}function ta(a,b){this.a=a;this.b=b}function t(){}function x(a,b){this.a=a;this.b=b}function u(a){this.a=a}function z(a){this.a=a}function sa(){}function ra(){}function qa(){}function pa(a,b){this.a=a;this.b=b}function oa(a){this.a=a}function na(a){this.a=a}function ma(){}function la(a){this.a=a}function I(){}function M(a){this.a=a}function H(){}function L(a){this.a=a}function mb(g){return function(b){return function(d){return new f(function(){return function(){return a(a(p)(a(a(p)(a(a(p)(K))(a(Ha)(g))))(a(nb)(b))))(a(Ia)(a(function(c){return new f(function(){return a(ob(c))?
bb(c):h("indefinite")})})(d)))}()})}}}function pb(g){return function(b){return function(d){return new f(function(){return function(){return $(function(c){return function(b){return new f(function(){if(a(b)instanceof x){var d=a(b).a,f=a(b).b,h=c;return Ra(d,f,h)}if(a(b)instanceof u)return d=a(b).a,h=c,N(Sa(g,d),Ja(h));if(a(b)instanceof t)return h=c,Ta(h);if(a(b)instanceof z)return f=a(b).a,h=c,W(N(Ua(f),Ja(h)),new y(h));k(["unhandled case in go",[c,b]])})}},d,U(b))}()})}}}function Ja(a){return function(b){return new f(function(){return new y(l(["user",
"Node",[]],m(["user","Node",[]],a).appendChild(m(["user","Node",[]],b))&&r||m(["user","Node",[]],b)))})}}function Q(g){return function(b){return new f(function(){var d=b;if(a(g)instanceof u)return X(d);d=b;return a(g)instanceof t?R(d):d=b})}}function q(a){return function(b){return new f(function(){return new x(a,b)})}}function qb(a){return new f(function(){var b=l,d=B(a);console&&console.log&&console.log(d);return new y(b(["unknown"],n))})}function rb(g){return function(b){return new f(function(){return a(ka)(Qa(g,
b))})}}function Y(a){return function(b){return new f(function(){return D(a,b)})}}function sb(g){return function(b){return function(d){return new f(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=b;return a(a(g)(e))(S(g,c,f))}k(["unhandled case in foldr",[g,b,d]])})}}}function tb(g){return function(b){return new f(function(){var d=b,c=a(g);if(c instanceof s){var e=c.c,c=c.d;return a(a(w)(e))(D(c,d))}d=b;if(a(g)===r)return d;k(["unhandled case in conc",[g,b]])})}}
function ub(g){return function(b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(w)(a(g)(c)))(da(g,d))}k(["unhandled case in map",[g,b]])})}}function G(g){return function(b){return function(d){return new f(function(){return a(a(g)(d))(b)})}}}function v(g){return function(b){return function(d){return new f(function(){return a(g)(a(b)(d))})}}}function C(a){return new f(function(){var b=JSON.stringify(m(["automatic"],a));return h(b)})}function a(a,
b){for(;a instanceof f;)a=a.l(b);return a}function f(a){this.i=!1;this.value=a}function y(a){this.value=a}function W(a,b){return N(a,function(){return b})}function N(g,b){return new f(function(){var d=a(g,!0);return a(b)(d.value)})}function m(g,b){var d=g[0],c=g[1],e;if("action"==d)e=function(){return m(c[0],a(b,!0).value)};else if("function"==d)e=function(){var d=b,e=c[c.length-1],g=c.length;if(1<g){for(var d=a(d,!0),f=0;f<g-1&&d instanceof Function;f++)d=a(d(l(c[f],arguments[f])),!0);g=e[1];return"action"==
e[0]?m(g[0],d.value):m(e,d)}k(Error("Nullary function?"))};else if("string"==d)e=B(b);else if("list"==d){d=[];for(b=a(b);b instanceof s;)d.push(m(c[0],b.c)),b=a(b.d);e=d}else if("tuple"==d){d=[];b=a(b);for(e=0;b instanceof s;)d.push(m(c[e++],b.c)),b=a(b.d);e=d}else if("defined"==d)b=a(b),e=b instanceof I?n:V(c[0],b.slot1);else if("nullable"==d)b=a(b),e=b instanceof H?r:V(c[0],b.slot1);else if("double"==d||"int"==d||"bool"==d)e=a(b);else{if("ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?
(b instanceof f&&(b=a(b)),e=V(g,b)):k(Error("Unhandled Fay->JS translation type: "+d))}return e}function B(g){var b="";for(g=a(g);g instanceof s;)b+=g.c,g=a(g.d);return b}function l(a,b){var d=a[0],c=a[1],e;if("action"==d)e=new y(l(c[0],b));else if("string"==d)e=h(b);else if("list"==d){var f=[],d=0;for(e=b.length;d<e;d++)f.push(l(c[0],b[d]));e=h(f)}else if("tuple"==d){f=[];d=0;for(e=b.length;d<e;d++)f.push(l(c[d],b[d]));e=h(f)}else if("defined"==d)e=b===n?new I:new M(l(c[0],b));else if("nullable"==
d)e=b===r?new H:new L(l(c[0],b));else if("int"==d)e=Math.round(b),e!==b&&k("Argument "+b+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b&&b.instance?(c=a[2],c="Nullable"===b.instance?new L(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new H:"Defined"===b.instance?new M(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new I:"Just"===b.instance?
new la(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Nothing"===b.instance?new ma:"Left"===b.instance?new na(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Right"===b.instance?new oa(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Ratio"===b.instance?new pa(b.slot1,b.slot2):"GT"===b.instance?new qa:"LT"===b.instance?new ra:"EQ"===b.instance?new sa:"Nullable"===b.instance?new L(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],
b.slot1)):"Null"===b.instance?new H:"Defined"===b.instance?new M(l(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new I:"Content"===b.instance?new z(l(["user","DString",[]],b.slot1)):"Element"===b.instance?new u(l(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new x(l(["user","DString",[]],b.slot1),l(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:"M"===b.instance?new ta(b.slot1,b.slot2):"L"===b.instance?new ua(b.slot1,b.slot2):
"H"===b.instance?new va(b.slot1):"V"===b.instance?new wa(b.slot1):"A"===b.instance?new xa(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6,b.slot7):"C"===b.instance?new ya(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6):"S"===b.instance?new za(b.slot1,b.slot2,b.slot3,b.slot4):"Q"===b.instance?new Aa(b.slot1,b.slot2,b.slot3,b.slot4):"T"===b.instance?new Ba(b.slot1,b.slot2):"Z"===b.instance?new Ca:"Translate"===b.instance?new Da(b.slot1,b.slot2):"Rotate"===b.instance?new Ea(b.slot1,b.slot2,b.slot3):
"Scale"===b.instance?new Fa(b.slot1):"Scale2d"===b.instance?new Ga(b.slot1,b.slot2):"Content"===b.instance?new z(l(["user","DString",[]],b.slot1)):"Element"===b.instance?new u(l(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new x(l(["user","DString",[]],b.slot1),l(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:"Content"===b.instance?new z(l(["user","DString",[]],b.slot1)):"Element"===b.instance?new u(l(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new x(l(["user",
"DString",[]],b.slot1),l(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:b):c=b,e=c):k(Error("Unhandled JS->Fay translation type: "+d))}return e}function s(a,b){this.c=a;this.d=b}function h(a){for(var b=r,d=a.length-1;0<=d;d--)b=new s(a[d],b);return b}function w(a){return function(b){return new s(a,b)}}function lb(g){return new f(function(){return a(g)*a(4)})}function X(g){return new f(function(){return a(g)+a(1)})}function R(g){return new f(function(){return a(g)-a(1)})}function ob(g){return new f(function(){return a(g)>
a(0)})}function cb(g){return new f(function(){return a(g)<a(0)})}function ab(g){return new f(function(){return a(g)>=a(0)})}f.prototype.l=function(a){return a?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var ka=new f(function(){return a(sb(tb))(r)}),F=new f(function(){return new t}),K=new f(function(){return r}),p=new f(function(){return G(w)}),O=new f(function(){return G(Y)}),vb=new f(function(){return new y(l(["user","Node",[]],document.documentElement))}),Ha=new f(function(){return q(h("attributeName"))}),
Z=new f(function(){return q(h("fill"))}),Ia=new f(function(){return q(h("repeatCount"))}),Ka=new f(function(){return q(h("stroke"))}),La=new f(function(){return q(h("values"))}),Ma=new f(function(){return E(h("animate"))}),Na=new f(function(){return E(h("circle"))}),aa=new f(function(){return E(h("rect"))}),Oa=new f(function(){return E(h("text"))}),wb=new f(function(){return h("http://www.w3.org/2000/svg")}),gb=new f(function(){return a(v(function(f){return a(a(p)(a(a(p)(K))(Na)))(f)}))(xb)}),yb=
new f(function(){return a(v(function(f){return a(v(function(b){return a(v(function(b){return a(a(O)(a(a(p)(K))(Ma)))(b)}))(b)}))(f)}))(mb)}),Ab=new f(function(){return a(v(La))(zb)}),Bb=new f(function(){return a(v(Ab))(ub(C))}),zb=new f(function(){return rb(h(";"))}),Cb=new f(function(){return pb(wb)}),hb=new f(function(){return a(v(q(h("cx"))))(C)}),ib=new f(function(){return a(v(q(h("cy"))))(C)}),nb=new f(function(){return a(v(q(h("dur"))))(C)}),Wa=new f(function(){return a(v(q(h("height"))))(C)}),
xb=new f(function(){return a(v(q(h("r"))))(C)}),Xa=new f(function(){return a(v(q(h("width"))))(C)}),ba=new f(function(){return a(v(q(h("x"))))(C)}),ca=new f(function(){return a(v(q(h("y"))))(C)}),q=function(a){return function(b){return new f(function(){return new x(a,b)})}},F=new f(function(){return new t}),K=new f(function(){return r}),p=new f(function(){return G(w)}),O=new f(function(){return G(Y)}),Q=function(g){return function(b){return new f(function(){var d=b;if(a(g)instanceof u)return X(d);
d=b;return a(g)instanceof t?R(d):d=b})}},Ha=new f(function(){return q(h("attributeName"))}),Z=new f(function(){return q(h("fill"))}),Ia=new f(function(){return q(h("repeatCount"))}),Ka=new f(function(){return q(h("stroke"))}),La=new f(function(){return q(h("values"))}),q=function(a){return function(b){return new f(function(){return new x(a,b)})}},F=new f(function(){return new t}),K=new f(function(){return r}),p=new f(function(){return G(w)}),O=new f(function(){return G(Y)}),Q=function(g){return function(b){return new f(function(){var d=
b;if(a(g)instanceof u)return X(d);d=b;return a(g)instanceof t?R(d):d=b})}},Ma=new f(function(){return E(h("animate"))}),Na=new f(function(){return E(h("circle"))}),aa=new f(function(){return E(h("rect"))}),Oa=new f(function(){return E(h("text"))}),Eb=new f(function(){return db(h("load"),Db)}),Db=new f(function(){var g=new f(function(){return ia(ha(a(a(p)(a(a(p)(ha(ia(a(a(p)(a(a(p)(a(a(O)(a(a(p)(eb(a(a(p)(a(a(p)(fb()))(a(Z)(h("blue")))))(a(Ka)(h("yellow"))),jb())))(a(Z)(h("red")))))(a(a(a(yb)(h("width")))(3))(4))))(a(Bb)(h([10,
270,300,10])))))(F),Oa),h("Some lovely text for the people!"))))(a(ba)(100))))(a(ca)(200)),h(" and some more")),F)});return W(ja(qb,kb(g)),W(N(vb,a(Cb)(g)),new y(r)))}),L=J("a"),H=function(){},M=J("a"),I=function(){},z=J("a"),u=J("a"),x=function(a,b){this.a=a;this.b=b},t=function(){},z=J("a"),u=J("a"),x=function(a,b){this.a=a;this.b=b},t=function(){};this.j=Eb;this.k=a};Pa.k(Pa.j);
