function k(E){throw E;}var n=void 0,r=null;function K(E){return function(Q){this[E]=Q}}
var Qa=new function(){function E(g,b){return new f(function(){var d=b,c=a(g);if(c instanceof s){var e=c.c,c=c.d;return a(a(x)(e))(E(c,d))}d=b;if(a(g)===r)return d;k(["unhandled case in conc",[g,b]])})}function Q(g,b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(x)(g))(a(a(x)(c))(Q(g,d)))}k(["unhandled case in prependToAll",[g,b]])})}function Ra(g,b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(x)(c))(Q(g,
d))}k(["unhandled case in intersperse",[g,b]])})}function Sa(a,b,d){return new f(function(){return new y(m(["user","Node",[]],l(["user","Node",[]],d).setAttributeNS(r,A(a),A(b))&&r||l(["user","Node",[]],d)))})}function Ta(a,b){return new f(function(){return new y(m(["user","Node",[]],document.createElementNS(A(a),A(b))))})}function Ua(a){return new f(function(){return new y(m(["user","Node",[]],l(["user","Node",[]],a).parentNode))})}function Va(a,b,d){return new f(function(){return new y(m(["user",
"Node",[]],(l(["user","Node",[]],d)[A(a)]=A(b))&&r||l(["user","Node",[]],d)))})}function Wa(a){return new f(function(){return new y(m(["user","Node",[]],document.createTextNode(A(a))))})}function aa(g,b,d){return new f(function(){if(a(d)===r){var c=b;return new y(c)}var e=a(d);if(e instanceof s){var c=e.c,f=e.d;return O(a(a(g)(b))(c),function(c){return aa(g,c,f)})}k(["unhandled case in foldM",[g,b,d]])})}function Xa(){return new f(function(){return a(a(p)(a(a(p)(a(a(p)(L))(ba)))(a(Ya)(50))))(a(Za)(10))})}
function $a(){return new f(function(){return a(a(p)(a(a(p)(Xa()))(a(ca)(20))))(a(da)(20))})}function ea(g,b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(x)(a(g)(c)))(ea(g,d))}k(["unhandled case in map",[g,b]])})}function ab(a){return new f(function(){return new B(a)})}function bb(g){return new f(function(){return function(){var b=new f(function(){return T(R,0,g)});return a(cb(b))?u(U(b,G),g):fa(h("Markup has more close elements than open"))}()})}
function T(g,b,d){return new f(function(){if(a(d)===r){var c=b;return c}c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=b;return a(a(g)(e))(T(g,c,f))}k(["unhandled case in foldr",[g,b,d]])})}function fa(a){return new f(function(){k(A(a))})}function db(a){return new f(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function V(g){return new f(function(){var b=a(g);if(b instanceof s)return u(V(b.d),h([b.c]));if(a(g)===r)return r;k(["unhandled case in reverse",[g]])})}function ga(g,b,d){return new f(function(){var c=
a(a(x)(b)),e;if(a(d)===r)e=r;else{var f=a(d);f instanceof s?(e=f.c,f=f.d,e=ga(g,a(a(g)(b))(e),f)):k(["unhandled case",d])}return c(e)})}function U(g,b){return new f(function(){return 0===a(g)?r:a(eb(g))?fa(h("replicate: negative length")):a(a(x)(b))(U(S(g),b))})}function u(a,b){return new f(function(){return E(a,b)})}function ha(g,b,d){return new f(function(){var c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=a(b);if(c instanceof s){var h=c.c,c=c.d;return a(a(x)(a(a(g)(h))(e)))(ha(g,c,f))}}return r})}
function F(a){return new f(function(){return new v(a)})}function fb(g,b){return new f(function(){return new y(m(["unknown"],window.addEventListener(A(g),l(["action",[["unknown"]]],b),a(!1))))})}function ia(g,b){return new f(function(){return a(a(p)(g))(ab(b))})}function ja(g,b){return new f(function(){if(a(b)instanceof t){var d=g;return bb(d)}d=g;return a(a(p)(a(a(p)(d))(G)))(b)})}function gb(g,b){return new f(function(){return a(a(P)(a(a(p)(g))(G)))(b)})}function hb(){return new f(function(){return a(a(p)(a(a(p)(a(ib)(40)))(a(jb)(100))))(a(kb)(100))})}
function lb(){return new f(function(){return $a()})}function ka(g,b){return new f(function(){return a(g)(b)})}function mb(g){return new f(function(){return function(){function b(c){return new f(function(){if(a(c)instanceof v){var b=a(c).a;return u(h("<"),u(b,h(">")))}if(a(c)instanceof z){var b=a(c).a,d=a(c).b;return u(b,u(h('="'),u(d,h('"'))))}if(a(c)instanceof C)return b=a(c).a,d=a(c).b,u(b,u(h('="'),u(d,h('"'))));if(a(c)instanceof B)return b=a(c).a,u(h('"'),u(b,h('"')));if(a(c)instanceof t)return h("<--");
k(["unhandled case in go",[c]])})}var d=new f(function(){return V(g)});return ka(la,ha(function(c){return function(d){return new f(function(){return u(U(nb(c)," "),u(a(b)(d),h("\n")))})}},new f(function(){return ga(H(R),0,d)}),d))}()})}function W(g,b){var d=a(b),c=g[2];if(d instanceof M){var e={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a);n!==c&&(e.slot1=c);return e}return d instanceof I?e={instance:"Null"}:d instanceof N?(e={instance:"Defined"},c=l(c&&c[0]?
c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof J?e={instance:"Undefined"}:d instanceof ma?(e={instance:"Just"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof na?e={instance:"Nothing"}:d instanceof oa?(e={instance:"Left"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof pa?(e={instance:"Right"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],
d.a),n!==c&&(e.slot1=c),e):d instanceof qa?(e={instance:"Ratio"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof ra?e={instance:"GT"}:d instanceof sa?e={instance:"LT"}:d instanceof ta?e={instance:"EQ"}:d instanceof M?(e={instance:"Nullable"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&(e.slot1=c),e):d instanceof I?e={instance:"Null"}:d instanceof N?(e={instance:"Defined"},c=l(c&&c[0]?c[0]:"automatic"===g[0]?["automatic"]:["unknown"],d.a),n!==c&&
(e.slot1=c),e):d instanceof J?e={instance:"Undefined"}:d instanceof B?(e={instance:"Content"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof v?(e={instance:"Element"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof z?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof C?(e={instance:"Property"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),
n!==c&&(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:d instanceof ua?(e={instance:"M"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof va?(e={instance:"L"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof wa?(e={instance:"H"},c=a(d.a),n!==c&&(e.slot1=c),e):d instanceof xa?(e={instance:"V"},c=a(d.a),n!==c&&(e.slot1=c),e):d instanceof ya?(e={instance:"A"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),
n!==c&&(e.slot4=c),c=a(d.g),n!==c&&(e.slot5=c),c=a(d.h),n!==c&&(e.slot6=c),d=a(d.m),n!==d&&(e.slot7=d),e):d instanceof za?(e={instance:"C"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),c=a(d.g),n!==c&&(e.slot5=c),c=a(d.h),n!==c&&(e.slot6=c),e):d instanceof Aa?(e={instance:"S"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),e):d instanceof Ba?(e={instance:"Q"},c=a(d.a),
n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),c=a(d.f),n!==c&&(e.slot4=c),e):d instanceof Ca?(e={instance:"T"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof Da?e={instance:"Z"}:d instanceof Ea?(e={instance:"Translate"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof Fa?(e={instance:"Rotate"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),c=a(d.e),n!==c&&(e.slot3=c),e):d instanceof Ga?(e={instance:"Scale"},c=a(d.a),
n!==c&&(e.slot1=c),e):d instanceof Ha?(e={instance:"Scale2d"},c=a(d.a),n!==c&&(e.slot1=c),c=a(d.b),n!==c&&(e.slot2=c),e):d instanceof B?(e={instance:"Content"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof v?(e={instance:"Element"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof z?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof C?(e={instance:"Property"},c=l(["user",
"DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:d instanceof B?(e={instance:"Content"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof v?(e={instance:"Element"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),e):d instanceof z?(e={instance:"Attribute"},c=l(["user","DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof C?(e={instance:"Property"},c=l(["user",
"DString",[]],d.a),n!==c&&(e.slot1=c),c=l(["user","DString",[]],d.b),n!==c&&(e.slot2=c),e):d instanceof t?e={instance:"Complete"}:b}function Ha(a,b){this.a=a;this.b=b}function Ga(a){this.a=a}function Fa(a,b,d){this.a=a;this.b=b;this.e=d}function Ea(a,b){this.a=a;this.b=b}function Da(){}function Ca(a,b){this.a=a;this.b=b}function Ba(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function Aa(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function za(a,b,d,c,e,f){this.a=a;this.b=b;this.e=d;this.f=c;this.g=
e;this.h=f}function ya(a,b,d,c,e,f,h){this.a=a;this.b=b;this.e=d;this.f=c;this.g=e;this.h=f;this.m=h}function xa(a){this.a=a}function wa(a){this.a=a}function va(a,b){this.a=a;this.b=b}function ua(a,b){this.a=a;this.b=b}function t(){}function C(a,b){this.a=a;this.b=b}function z(a,b){this.a=a;this.b=b}function v(a){this.a=a}function B(a){this.a=a}function ta(){}function sa(){}function ra(){}function qa(a,b){this.a=a;this.b=b}function pa(a){this.a=a}function oa(a){this.a=a}function na(){}function ma(a){this.a=
a}function J(){}function N(a){this.a=a}function I(){}function M(a){this.a=a}function ob(g){return function(b){return function(d){return new f(function(){return function(){return a(a(p)(a(a(p)(a(a(p)(L))(a(Ia)(g))))(a(pb)(b))))(a(Ja)(a(function(c){return new f(function(){return a(qb(c))?db(c):h("indefinite")})})(d)))}()})}}}function rb(g){return function(b){return function(d){return new f(function(){return function(){return aa(function(c){return function(b){return new f(function(){if(a(b)instanceof
z){var d=a(b).a,f=a(b).b,h=c;return Sa(d,f,h)}if(a(b)instanceof v)return d=a(b).a,h=c,O(Ta(g,d),Ka(h));if(a(b)instanceof t)return h=c,Ua(h);if(a(b)instanceof C)return d=a(b).a,f=a(b).b,h=c,Va(d,f,h);if(a(b)instanceof B)return f=a(b).a,h=c,X(O(Wa(f),Ka(h)),new y(h));k(["unhandled case in go",[c,b]])})}},d,V(b))}()})}}}function Ka(a){return function(b){return new f(function(){return new y(m(["user","Node",[]],l(["user","Node",[]],a).appendChild(l(["user","Node",[]],b))&&r||l(["user","Node",[]],b)))})}}
function R(g){return function(b){return new f(function(){var d=b;if(a(g)instanceof v)return Y(d);d=b;return a(g)instanceof t?S(d):d=b})}}function q(a){return function(b){return new f(function(){return new z(a,b)})}}function sb(a){return new f(function(){var b=m,d=A(a);console&&console.log&&console.log(d);return new y(b(["unknown"],n))})}function tb(g){return function(b){return new f(function(){return a(la)(Ra(g,b))})}}function Z(a){return function(b){return new f(function(){return E(a,b)})}}function ub(g){return function(b){return function(d){return new f(function(){if(a(d)===
r){var c=b;return c}c=a(d);if(c instanceof s){var e=c.c,f=c.d,c=b;return a(a(g)(e))(T(g,c,f))}k(["unhandled case in foldr",[g,b,d]])})}}}function vb(g){return function(b){return new f(function(){var d=b,c=a(g);if(c instanceof s){var e=c.c,c=c.d;return a(a(x)(e))(E(c,d))}d=b;if(a(g)===r)return d;k(["unhandled case in conc",[g,b]])})}}function wb(g){return function(b){return new f(function(){if(a(b)===r)return r;var d=a(b);if(d instanceof s){var c=d.c,d=d.d;return a(a(x)(a(g)(c)))(ea(g,d))}k(["unhandled case in map",
[g,b]])})}}function H(g){return function(b){return function(d){return new f(function(){return a(a(g)(d))(b)})}}}function w(g){return function(b){return function(d){return new f(function(){return a(g)(a(b)(d))})}}}function D(a){return new f(function(){var b=JSON.stringify(l(["automatic"],a));return h(b)})}function a(a,b){for(;a instanceof f;)a=a.l(b);return a}function f(a){this.i=!1;this.value=a}function y(a){this.value=a}function X(a,b){return O(a,function(){return b})}function O(g,b){return new f(function(){var d=
a(g,!0);return a(b)(d.value)})}function l(g,b){var d=g[0],c=g[1],e;if("action"==d)e=function(){return l(c[0],a(b,!0).value)};else if("function"==d)e=function(){var d=b,e=c[c.length-1],g=c.length;if(1<g){for(var d=a(d,!0),f=0;f<g-1&&d instanceof Function;f++)d=a(d(m(c[f],arguments[f])),!0);g=e[1];return"action"==e[0]?l(g[0],d.value):l(e,d)}k(Error("Nullary function?"))};else if("string"==d)e=A(b);else if("list"==d){d=[];for(b=a(b);b instanceof s;)d.push(l(c[0],b.c)),b=a(b.d);e=d}else if("tuple"==d){d=
[];b=a(b);for(e=0;b instanceof s;)d.push(l(c[e++],b.c)),b=a(b.d);e=d}else if("defined"==d)b=a(b),e=b instanceof J?n:W(c[0],b.slot1);else if("nullable"==d)b=a(b),e=b instanceof I?r:W(c[0],b.slot1);else if("double"==d||"int"==d||"bool"==d)e=a(b);else{if("ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b instanceof f&&(b=a(b)),e=W(g,b)):k(Error("Unhandled Fay->JS translation type: "+d))}return e}function A(g){var b="";for(g=a(g);g instanceof s;)b+=g.c,g=a(g.d);return b}function m(a,b){var d=
a[0],c=a[1],e;if("action"==d)e=new y(m(c[0],b));else if("string"==d)e=h(b);else if("list"==d){var f=[],d=0;for(e=b.length;d<e;d++)f.push(m(c[0],b[d]));e=h(f)}else if("tuple"==d){f=[];d=0;for(e=b.length;d<e;d++)f.push(m(c[d],b[d]));e=h(f)}else if("defined"==d)e=b===n?new J:new N(m(c[0],b));else if("nullable"==d)e=b===r?new I:new M(m(c[0],b));else if("int"==d)e=Math.round(b),e!==b&&k("Argument "+b+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return b;"automatic"==d||
"user"==d?(b&&b.instance?(c=a[2],c="Nullable"===b.instance?new M(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new I:"Defined"===b.instance?new N(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new J:"Just"===b.instance?new ma(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Nothing"===b.instance?new na:"Left"===b.instance?new oa(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],
b.slot1)):"Right"===b.instance?new pa(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Ratio"===b.instance?new qa(b.slot1,b.slot2):"GT"===b.instance?new ra:"LT"===b.instance?new sa:"EQ"===b.instance?new ta:"Nullable"===b.instance?new M(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new I:"Defined"===b.instance?new N(m(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new J:"Content"===b.instance?
new B(m(["user","DString",[]],b.slot1)):"Element"===b.instance?new v(m(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new z(m(["user","DString",[]],b.slot1),m(["user","DString",[]],b.slot2)):"Property"===b.instance?new C(m(["user","DString",[]],b.slot1),m(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:"M"===b.instance?new ua(b.slot1,b.slot2):"L"===b.instance?new va(b.slot1,b.slot2):"H"===b.instance?new wa(b.slot1):"V"===b.instance?new xa(b.slot1):"A"===b.instance?new ya(b.slot1,
b.slot2,b.slot3,b.slot4,b.slot5,b.slot6,b.slot7):"C"===b.instance?new za(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6):"S"===b.instance?new Aa(b.slot1,b.slot2,b.slot3,b.slot4):"Q"===b.instance?new Ba(b.slot1,b.slot2,b.slot3,b.slot4):"T"===b.instance?new Ca(b.slot1,b.slot2):"Z"===b.instance?new Da:"Translate"===b.instance?new Ea(b.slot1,b.slot2):"Rotate"===b.instance?new Fa(b.slot1,b.slot2,b.slot3):"Scale"===b.instance?new Ga(b.slot1):"Scale2d"===b.instance?new Ha(b.slot1,b.slot2):"Content"===b.instance?
new B(m(["user","DString",[]],b.slot1)):"Element"===b.instance?new v(m(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new z(m(["user","DString",[]],b.slot1),m(["user","DString",[]],b.slot2)):"Property"===b.instance?new C(m(["user","DString",[]],b.slot1),m(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:"Content"===b.instance?new B(m(["user","DString",[]],b.slot1)):"Element"===b.instance?new v(m(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new z(m(["user","DString",
[]],b.slot1),m(["user","DString",[]],b.slot2)):"Property"===b.instance?new C(m(["user","DString",[]],b.slot1),m(["user","DString",[]],b.slot2)):"Complete"===b.instance?new t:b):c=b,e=c):k(Error("Unhandled JS->Fay translation type: "+d))}return e}function s(a,b){this.c=a;this.d=b}function h(a){for(var b=r,d=a.length-1;0<=d;d--)b=new s(a[d],b);return b}function x(a){return function(b){return new s(a,b)}}function nb(g){return new f(function(){return a(g)*a(4)})}function Y(g){return new f(function(){return a(g)+
a(1)})}function S(g){return new f(function(){return a(g)-a(1)})}function qb(g){return new f(function(){return a(g)>a(0)})}function eb(g){return new f(function(){return a(g)<a(0)})}function cb(g){return new f(function(){return a(g)>=a(0)})}f.prototype.l=function(a){return a?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var la=new f(function(){return a(ub(vb))(r)}),G=new f(function(){return new t}),L=new f(function(){return r}),p=new f(function(){return H(x)}),P=new f(function(){return H(Z)}),
xb=new f(function(){return new y(m(["user","Node",[]],document.documentElement))}),Ia=new f(function(){return q(h("attributeName"))}),$=new f(function(){return q(h("fill"))}),Ja=new f(function(){return q(h("repeatCount"))}),La=new f(function(){return q(h("stroke"))}),Ma=new f(function(){return q(h("values"))}),Na=new f(function(){return F(h("animate"))}),Oa=new f(function(){return F(h("circle"))}),ba=new f(function(){return F(h("rect"))}),Pa=new f(function(){return F(h("text"))}),yb=new f(function(){return h("http://www.w3.org/2000/svg")}),
ib=new f(function(){return a(w(function(f){return a(a(p)(a(a(p)(L))(Oa)))(f)}))(zb)}),Ab=new f(function(){return a(w(function(f){return a(w(function(b){return a(w(function(b){return a(a(P)(a(a(p)(L))(Na)))(b)}))(b)}))(f)}))(ob)}),Cb=new f(function(){return a(w(Ma))(Bb)}),Db=new f(function(){return a(w(Cb))(wb(D))}),Bb=new f(function(){return tb(h(";"))}),Eb=new f(function(){return rb(yb)}),jb=new f(function(){return a(w(q(h("cx"))))(D)}),kb=new f(function(){return a(w(q(h("cy"))))(D)}),pb=new f(function(){return a(w(q(h("dur"))))(D)}),
Ya=new f(function(){return a(w(q(h("height"))))(D)}),zb=new f(function(){return a(w(q(h("r"))))(D)}),Za=new f(function(){return a(w(q(h("width"))))(D)}),ca=new f(function(){return a(w(q(h("x"))))(D)}),da=new f(function(){return a(w(q(h("y"))))(D)}),q=function(a){return function(b){return new f(function(){return new z(a,b)})}},G=new f(function(){return new t}),L=new f(function(){return r}),p=new f(function(){return H(x)}),P=new f(function(){return H(Z)}),R=function(g){return function(b){return new f(function(){var d=
b;if(a(g)instanceof v)return Y(d);d=b;return a(g)instanceof t?S(d):d=b})}},Ia=new f(function(){return q(h("attributeName"))}),$=new f(function(){return q(h("fill"))}),Ja=new f(function(){return q(h("repeatCount"))}),La=new f(function(){return q(h("stroke"))}),Ma=new f(function(){return q(h("values"))}),q=function(a){return function(b){return new f(function(){return new z(a,b)})}},G=new f(function(){return new t}),L=new f(function(){return r}),p=new f(function(){return H(x)}),P=new f(function(){return H(Z)}),
R=function(g){return function(b){return new f(function(){var d=b;if(a(g)instanceof v)return Y(d);d=b;return a(g)instanceof t?S(d):d=b})}},Na=new f(function(){return F(h("animate"))}),Oa=new f(function(){return F(h("circle"))}),ba=new f(function(){return F(h("rect"))}),Pa=new f(function(){return F(h("text"))}),Gb=new f(function(){return fb(h("load"),Fb)}),Fb=new f(function(){var g=new f(function(){return ja(ia(a(a(p)(a(a(p)(ia(ja(a(a(p)(a(a(p)(a(a(P)(a(a(p)(gb(a(a(p)(a(a(p)(hb()))(a($)(h("blue")))))(a(La)(h("yellow"))),
lb())))(a($)(h("red")))))(a(a(a(Ab)(h("width")))(3))(4))))(a(Db)(h([10,270,300,10])))))(G),Pa),h("Some lovely text for the people!"))))(a(ca)(100))))(a(da)(200)),h(" and some more")),G)});return X(ka(sb,mb(g)),X(O(xb,a(Eb)(g)),new y(r)))}),M=K("a"),I=function(){},N=K("a"),J=function(){},B=K("a"),v=K("a"),z=function(a,b){this.a=a;this.b=b},C=function(a,b){this.a=a;this.b=b},t=function(){},B=K("a"),v=K("a"),z=function(a,b){this.a=a;this.b=b},C=function(a,b){this.a=a;this.b=b},t=function(){};this.j=
Gb;this.k=a};Qa.k(Qa.j);
