function l(Q){throw Q;}var m=void 0,s=null;function aa(Q){return function(ba){this[Q]=ba}}
var zb=new function(){function Q(e){return new f(function(){if(a(e)===s)return L(s);var b=a(e);if(b instanceof q)return H(b.d,Q(b.c));l(["unhandled case in sequence_",[e]])})}function ba(e,b){return new f(function(){return a(a(v)(e))(ba(t(e,b),b))})}function ca(e,b){return new f(function(){var d=b,c=a(e);if(c instanceof q){var g=c.d,c=c.c;return a(a(v)(g))(ca(c,d))}d=b;if(a(e)===s)return d;l(["unhandled case in conc",[e,b]])})}function Ja(e,b){return new f(function(){if(a(b)===s)return s;var d=a(b);
if(d instanceof q){var c=d.d,d=d.c;return a(a(v)(e))(a(a(v)(c))(Ja(e,d)))}l(["unhandled case in prependToAll",[e,b]])})}function Ab(e,b){return new f(function(){if(a(b)===s)return s;var d=a(b);if(d instanceof q){var c=d.d,d=d.c;return a(a(v)(c))(Ja(e,d))}l(["unhandled case in intersperse",[e,b]])})}function Bb(e,b){var d=0;return new f(function(){for(;;){if(a(b)===s){var c=d;return c}c=a(b);if(c instanceof q){var g=c.d,f=c.c,c=d,h=e;e=h;d=a(a(h)(c))(g);b=f}else l(["unhandled case in foldl",[e,d,b]])}})}
function Cb(e){var b=0;return new f(function(){for(;;){var d=a(e);if(d instanceof q){var d=d.c,c=b;b=t(c,1);e=d}else return c=b}})}function Db(a,b,d){return new f(function(){return new w(p(["user","Node",[]],k(["user","Node",[]],d).setAttributeNS(s,z(a),z(b))&&s||k(["user","Node",[]],d)))})}function Eb(a,b){return new f(function(){return new w(p(["user","Node",[]],document.createElementNS(z(a),z(b))))})}function Fb(a){return new f(function(){return new w(p(["user","Node",[]],k(["user","Node",[]],
a).parentNode))})}function Gb(a){return new f(function(){return new w(p(["user","Node",[]],document.createTextNode(z(a))))})}function Ka(e,b,d){return new f(function(){if(a(d)===s){var c=b;return L(c)}var g=a(d);if(g instanceof q){var c=g.d,f=g.c;return A(a(a(e)(b))(c),function(a){return Ka(e,a,f)})}l(["unhandled case in foldM",[e,b,d]])})}function Hb(e){return new f(function(){if(a(e)instanceof X)return h("translate");if(a(e)instanceof da)return h("rotate");if(a(e)instanceof ea||a(e)instanceof fa)return h("scale");
l(["unhandled case in transformType",[e]])})}function Ib(e){return new f(function(){if(a(e)instanceof X){var b=a(e).a,d=a(e).b;return x(D(b),x(h(","),D(d)))}if(a(e)instanceof da){var b=a(e).a,d=a(e).b,c=a(e).e;return x(D(b),x(h(","),x(D(d),x(h(","),D(c)))))}if(a(e)instanceof ea)return b=a(e).a,D(b);if(a(e)instanceof fa)return b=a(e).a,d=a(e).b,x(D(b),x(h(","),D(d)));l(["unhandled case in transformVals",[e]])})}function Jb(a){return new f(function(){return Y(k(["automatic"],a).instance+" ")})}function La(e){return new f(function(){return a(Ma(a(u(oa))(e)))(s)})}
function Kb(e,b){return new f(function(){return Y(k(["automatic"],b)["slot"+a(e)]!=s&&k(["automatic"],b)["slot"+a(e)]+" "||"")})}function Lb(e){return new f(function(){return function(){var b=new f(function(){return ga(Na,0,e)});return a(Mb(b))?x(pa(b,J),e):ha(h("Markup has more close elements than open"))}()})}function ga(e,b,d){return new f(function(){if(a(d)===s){var c=b;return c}c=a(d);if(c instanceof q){var g=c.d,f=c.c,c=b;return a(a(e)(g))(ga(e,c,f))}l(["unhandled case in foldr",[e,b,d]])})}
function ha(a){return new f(function(){l(z(a))})}function D(a){return new f(function(){return Y(JSON.stringify(k(["automatic"],a)))})}function Oa(e){return new f(function(){var b=a(e);if(b instanceof q)return x(Oa(b.c),h([b.d]));if(a(e)===s)return s;l(["unhandled case in reverse",[e]])})}function pa(e,b){return new f(function(){return 0===a(e)?s:a(Pa(e))?ha(h("replicate: negative length")):a(a(v)(b))(pa(R(e,1),b))})}function x(a,b){return new f(function(){return ca(a,b)})}function Nb(e,b){return new f(function(){if(a(b)instanceof
B){var d=e;return Lb(d)}d=e;return a(a(n)(a(a(n)(d))(J)))(b)})}function qa(e,b){return new f(function(){return a(a(y)(a(a(n)(e))(J)))(b)})}function Qa(e,b){return new f(function(){return a(a(n)(a(a(n)(E))(a(Ob)(e))))(a(Pb)(b))})}function Z(a){return new f(function(){return new ra(a)})}function S(a){return new f(function(){return new sa(a)})}function ta(a){return new f(function(){return new F(a)})}function Qb(a,b){return new f(function(){return new X(a,b)})}function Rb(e){return new f(function(){return-a(e)})}
function Sb(e){return new f(function(){var b=Math.floor(a(e)*Math.random());return new w(b)})}function Tb(e){return new f(function(){return Math.round(a(e))})}function Ub(e){return new f(function(){return function(){function b(a){return new f(function(){return t(M(a,g),C)})}function d(a){return new f(function(){return R(I,a)})}var c=new f(function(){return Ra(Vb,Sa(e))}),g=new f(function(){return a(a(ia)(G))(t(M(c,2),1))}),I=new f(function(){return t(C,G)}),k=new f(function(){return a(a(ia)(G))(2)});
return ja(function(e){return function(c){return new f(function(){return h([$(a(b)(c),I),N(a(b)(c),a(d)(e)),N(t(g,a(b)(c)),a(d)(e)),ua(k,k,0,0,t(g,a(b)(c)),a(d)(e)),N(t(g,a(b)(c)),I),ka])})}},e,Wb())}()})}function Xb(e){return new f(function(){return function(){function b(a){return new f(function(){return t(M(k,Yb(a)),I)})}function d(a){return new f(function(){return t(M(k,Zb(a)),I)})}var c=new f(function(){return $b(e)}),g=new f(function(){return va(function(b){return M(M(a(a(ia)(b))(c),ac),2)},e)}),
I=new f(function(){return t(C,k)}),k=new f(function(){return a(a(ia)(G))(2)});return ja(function(e){return function(c){return new f(function(){return h([$(I,I),N(a(d)(e),a(b)(e)),N(a(d)(e),a(b)(e)),ua(k,k,0,0,a(d)(t(e,c)),a(b)(t(e,c))),N(a(d)(t(e,c)),a(b)(t(e,c))),ka])})}},new f(function(){return Ta(Ua,0,g)}),g)}()})}function Va(e,b,d,c){return new f(function(){var g=a(c);if(g instanceof q){var f=g.d,h=g.c,g=a(d);if(g instanceof q){var k=g.d,n=g.c,g=a(b);if(g instanceof q){var p=g.d,g=g.c;return a(a(v)(a(a(a(e)(p))(k))(f)))(Va(e,
g,n,h))}}}return s})}function Wa(a){return new f(function(){return new w(p(["user","Node",[]],document.getElementById(z(a))))})}function $b(e){return new f(function(){return a(e)===s?ha(h("sum: empty list")):Bb(Ua,e)})}function va(e,b){return new f(function(){if(a(b)===s)return s;var d=a(b);if(d instanceof q){var c=d.d,d=d.c;return a(a(v)(a(e)(c)))(va(e,d))}l(["unhandled case in map",[e,b]])})}function Ta(e,b,d){return new f(function(){var c=a(a(v)(b)),g;if(a(d)===s)g=s;else{var f=a(d);f instanceof
q?(g=f.d,f=f.c,g=Ta(e,a(a(e)(b))(g),f)):l(["unhandled case",d])}return c(g)})}function Zb(e){return new f(function(){return Math.sin(a(e))})}function Yb(e){return new f(function(){return Math.cos(a(e))})}function $(a,b){return new f(function(){return new wa(a,b)})}function ua(a,b,d,c,g,h){return new f(function(){return new xa(a,b,d,c,0,g,h)})}function N(a,b){return new f(function(){return new ya(a,b)})}function Ra(e,b){return new f(function(){return a(e)(b)})}function Sa(a){return new f(function(){return Cb(a)})}
function ja(e,b,d){return new f(function(){var c=a(d);if(c instanceof q){var g=c.d,f=c.c,c=a(b);if(c instanceof q){var h=c.d,c=c.c;return a(a(v)(a(a(e)(h))(g)))(ja(e,c,f))}}return s})}function Wb(){return new f(function(){return ba(1,R(3,1))})}function bc(a){return new f(function(){return new w(p(["list",[["user","Node",[]]]],document.getElementsByClassName(z(a))))})}function za(e,b){return new f(function(){var d=a(b);if(d instanceof q){var c=d.d,d=d.c;return H(a(e)(c),za(e,d))}if(a(b)===s)return L(s);
l(["unhandled case in mapM_",[e,b]])})}function Xa(e){return new f(function(){return A(bc(e),function(b){return A(a(a(cc)(dc))(b),function(e){return H(za(ec,b),H(a(a(a(fc)(Aa))(e))(b),za(gc,b)))})})})}function hc(e,b){return new f(function(){return new w(p(["unknown"],window.addEventListener(z(e),k(["action",[["unknown"]]],b),a(!1))))})}function Ba(e,b){var d=a(b),c=e[2];if(d instanceof T){var g={instance:"Nullable"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a);m!==c&&(g.slot1=
c);return g}return d instanceof O?g={instance:"Null"}:d instanceof U?(g={instance:"Defined"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=c),g):d instanceof P?g={instance:"Undefined"}:d instanceof Ya?(g={instance:"Just"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=c),g):d instanceof Za?g={instance:"Nothing"}:d instanceof $a?(g={instance:"Left"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=
c),g):d instanceof ab?(g={instance:"Right"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=c),g):d instanceof bb?(g={instance:"Ratio"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof cb?g={instance:"GT"}:d instanceof db?g={instance:"LT"}:d instanceof eb?g={instance:"EQ"}:d instanceof T?(g={instance:"Nullable"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=c),g):d instanceof O?g={instance:"Null"}:d instanceof
U?(g={instance:"Defined"},c=k(c&&c[0]?c[0]:"automatic"===e[0]?["automatic"]:["unknown"],d.a),m!==c&&(g.slot1=c),g):d instanceof P?g={instance:"Undefined"}:d instanceof V?(g={instance:"Content"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),g):d instanceof F?(g={instance:"Element"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),g):d instanceof K?(g={instance:"Attribute"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),c=k(["user","DString",[]],d.b),m!==c&&(g.slot2=c),g):d instanceof B?g={instance:"Complete"}:
d instanceof wa?(g={instance:"M"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof ya?(g={instance:"L"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof sa?(g={instance:"H"},c=a(d.a),m!==c&&(g.slot1=c),g):d instanceof ra?(g={instance:"V"},c=a(d.a),m!==c&&(g.slot1=c),g):d instanceof xa?(g={instance:"A"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),c=a(d.e),m!==c&&(g.slot3=c),c=a(d.f),m!==c&&(g.slot4=c),c=a(d.g),m!==c&&(g.slot5=c),c=a(d.h),m!==
c&&(g.slot6=c),d=a(d.m),m!==d&&(g.slot7=d),g):d instanceof fb?(g={instance:"C"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),c=a(d.e),m!==c&&(g.slot3=c),c=a(d.f),m!==c&&(g.slot4=c),c=a(d.g),m!==c&&(g.slot5=c),c=a(d.h),m!==c&&(g.slot6=c),g):d instanceof gb?(g={instance:"S"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),c=a(d.e),m!==c&&(g.slot3=c),c=a(d.f),m!==c&&(g.slot4=c),g):d instanceof hb?(g={instance:"Q"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),c=a(d.e),m!==
c&&(g.slot3=c),c=a(d.f),m!==c&&(g.slot4=c),g):d instanceof ib?(g={instance:"T"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof Ca?g={instance:"Z"}:d instanceof X?(g={instance:"Translate"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof da?(g={instance:"Rotate"},c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),c=a(d.e),m!==c&&(g.slot3=c),g):d instanceof ea?(g={instance:"Scale"},c=a(d.a),m!==c&&(g.slot1=c),g):d instanceof fa?(g={instance:"Scale2d"},
c=a(d.a),m!==c&&(g.slot1=c),c=a(d.b),m!==c&&(g.slot2=c),g):d instanceof V?(g={instance:"Content"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),g):d instanceof F?(g={instance:"Element"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),g):d instanceof K?(g={instance:"Attribute"},c=k(["user","DString",[]],d.a),m!==c&&(g.slot1=c),c=k(["user","DString",[]],d.b),m!==c&&(g.slot2=c),g):d instanceof B?g={instance:"Complete"}:b}function fa(a,b){this.a=a;this.b=b}function ea(a){this.a=a}function da(a,
b,d){this.a=a;this.b=b;this.e=d}function X(a,b){this.a=a;this.b=b}function Ca(){}function ib(a,b){this.a=a;this.b=b}function hb(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function gb(a,b,d,c){this.a=a;this.b=b;this.e=d;this.f=c}function fb(a,b,d,c,g,f){this.a=a;this.b=b;this.e=d;this.f=c;this.g=g;this.h=f}function xa(a,b,d,c,g,f,h){this.a=a;this.b=b;this.e=d;this.f=c;this.g=g;this.h=f;this.m=h}function ra(a){this.a=a}function sa(a){this.a=a}function ya(a,b){this.a=a;this.b=b}function wa(a,b){this.a=
a;this.b=b}function B(){}function K(a,b){this.a=a;this.b=b}function F(a){this.a=a}function V(a){this.a=a}function eb(){}function db(){}function cb(){}function bb(a,b){this.a=a;this.b=b}function ab(a){this.a=a}function $a(a){this.a=a}function Za(){}function Ya(a){this.a=a}function P(){}function U(a){this.a=a}function O(){}function T(a){this.a=a}function jb(a){return function(b){return function(d){return new f(function(){return new w(p(["unknown"],k(["user","Node",[]],d).addEventListener(z(a),k(["function",
[["user","Event",[]],["action",[["unknown"]]]]],b),s)))})}}}function ic(){return new f(function(){return Xa(h("B"))})}function jc(){return new f(function(){return Xa(h("P"))})}function kc(e){return new f(function(){return x(Jb(e),a(La(function(a){return Kb(a,e)}))(h([1,2,3,4,5,6,7,8])))})}function gc(a){return new f(function(){return new w(p(["user","Node",[]],k(["user","Node",[]],a).beginElement()||k(["user","Node",[]],a)))})}function lc(e){return function(b){return function(d){return new f(function(){return function(){return a(a(n)(a(a(n)(a(a(n)(E))(a(kb)(e))))(a(mc)(b))))(a(lb)(a(function(b){return new f(function(){return a(nc(b))?
D(b):h("indefinite")})})(d)))}()})}}}function oc(e){return function(b){return function(d){return new f(function(){return function(){return Ka(function(b){return function(d){return new f(function(){if(a(d)instanceof K){var f=a(d).a,h=a(d).b,k=b;return Db(f,h,k)}if(a(d)instanceof F)return f=a(d).a,k=b,A(Eb(e,f),Aa(k));if(a(d)instanceof B)return k=b,Fb(k);if(a(d)instanceof V)return h=a(d).a,k=b,H(A(Gb(h),Aa(k)),L(k));l(["unhandled case in go",[b,d]])})}},d,Oa(b))}()})}}}function pc(a){return new f(function(){return Y(String(z(a)).toLowerCase())})}
function dc(a){return new f(function(){return new w(p(["user","Node",[]],k(["user","Node",[]],a).parentNode))})}function ec(a){return new f(function(){return new w(p(["unknown"],k(["user","Node",[]],a).parentNode.removeChild(k(["user","Node",[]],a))))})}function Aa(a){return function(b){return new f(function(){return new w(p(["user","Node",[]],k(["user","Node",[]],a).appendChild(k(["user","Node",[]],b))&&s||k(["user","Node",[]],b)))})}}function Na(e){return function(b){return new f(function(){var d=
b;if(a(e)instanceof F)return t(d,1);d=b;return a(e)instanceof B?R(d,1):d=b})}}function r(a){return function(b){return new f(function(){return new K(a,b)})}}function mb(e){return function(b){return new f(function(){return a(nb)(Ab(e,b))})}}function qc(e){return function(b){return function(d){return new f(function(){var c=a(d);if(c instanceof q){var f=c.d,h=c.c,c=a(b);if(c instanceof q){var k=c.d,c=c.c;return a(a(v)(a(a(e)(k))(f)))(ja(e,c,h))}}return s})}}}function rc(e){return function(b){return new f(function(){return 0===
a(e)?s:a(Pa(e))?ha(h("replicate: negative length")):a(a(v)(b))(pa(R(e,1),b))})}}function oa(a){return function(b){return new f(function(){return ca(a,b)})}}function Ma(e){return function(b){return function(d){return new f(function(){if(a(d)===s){var c=b;return c}c=a(d);if(c instanceof q){var f=c.d,h=c.c,c=b;return a(a(e)(f))(ga(e,c,h))}l(["unhandled case in foldr",[e,b,d]])})}}}function sc(e){return function(b){return new f(function(){var d=b,c=a(e);if(c instanceof q){var f=c.d,c=c.c;return a(a(v)(f))(ca(c,
d))}d=b;if(a(e)===s)return d;l(["unhandled case in conc",[e,b]])})}}function ob(e){return function(b){return new f(function(){if(a(b)===s)return s;var d=a(b);if(d instanceof q){var c=d.d,d=d.c;return a(a(v)(a(e)(c)))(va(e,d))}l(["unhandled case in map",[e,b]])})}}function la(e){return function(b){return function(d){return new f(function(){return a(a(e)(d))(b)})}}}function u(e){return function(b){return function(d){return new f(function(){return a(e)(a(b)(d))})}}}function ma(a){return new f(function(){return Y(JSON.stringify(k(["automatic"],
a)))})}function Vb(e){return new f(function(){return a(e)})}function tc(e){return new f(function(){if(a(e)===s)return L(s);var b=a(e);if(b instanceof q)return H(b.d,Q(b.c));l(["unhandled case in sequence_",[e]])})}function pb(e){return new f(function(){return function(){return ga(function(b){return function(d){return new f(function(){return A(b,function(b){return A(d,function(d){return L(a(a(v)(b))(d))})})})}},L(s),e)}()})}function a(a,b){for(;a instanceof f;)a=a.l(b);return a}function f(a){this.i=
!1;this.value=a}function w(a){this.value=a}function H(a,b){return A(a,function(){return b})}function A(e,b){return new f(function(){var d=a(e,!0);return a(b)(d.value)})}function L(a){return new w(a)}function k(e,b){var d=e[0],c=e[1],g;if("action"==d)g=function(){return k(c[0],a(b,!0).value)};else if("function"==d)g=function(){var d=b,e=c[c.length-1],f=c.length;if(1<f){for(var d=a(d,!0),g=0;g<f-1&&d instanceof Function;g++)d=a(d(p(c[g],arguments[g])),!0);f=e[1];return"action"==e[0]?k(f[0],d.value):
k(e,d)}l(Error("Nullary function?"))};else if("string"==d)g=z(b);else if("list"==d){d=[];for(b=a(b);b instanceof q;)d.push(k(c[0],b.d)),b=a(b.c);g=d}else if("tuple"==d){d=[];b=a(b);for(g=0;b instanceof q;)d.push(k(c[g++],b.d)),b=a(b.c);g=d}else if("defined"==d)b=a(b),g=b instanceof P?m:Ba(c[0],b.slot1);else if("nullable"==d)b=a(b),g=b instanceof O?s:Ba(c[0],b.slot1);else if("double"==d||"int"==d||"bool"==d)g=a(b);else{if("ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b instanceof f&&(b=
a(b)),g=Ba(e,b)):l(Error("Unhandled Fay->JS translation type: "+d))}return g}function z(e){var b="";for(e=a(e);e instanceof q;)b+=e.d,e=a(e.c);return b}function Y(a){return h(a)}function p(a,b){var d=a[0],c=a[1],f;if("action"==d)f=new w(p(c[0],b));else if("string"==d)f=h(b);else if("list"==d){var k=[],d=0;for(f=b.length;d<f;d++)k.push(p(c[0],b[d]));f=h(k)}else if("tuple"==d){k=[];d=0;for(f=b.length;d<f;d++)k.push(p(c[d],b[d]));f=h(k)}else if("defined"==d)f=b===m?new P:new U(p(c[0],b));else if("nullable"==
d)f=b===s?new O:new T(p(c[0],b));else if("int"==d)f=Math.round(b),f!==b&&l("Argument "+b+" is not an integer!");else{if("double"==d||"bool"==d||"ptr"==d||"unknown"==d)return b;"automatic"==d||"user"==d?(b&&b.instance?(c=a[2],c="Nullable"===b.instance?new T(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Null"===b.instance?new O:"Defined"===b.instance?new U(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new P:"Just"===b.instance?
new Ya(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Nothing"===b.instance?new Za:"Left"===b.instance?new $a(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Right"===b.instance?new ab(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Ratio"===b.instance?new bb(b.slot1,b.slot2):"GT"===b.instance?new cb:"LT"===b.instance?new db:"EQ"===b.instance?new eb:"Nullable"===b.instance?new T(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],
b.slot1)):"Null"===b.instance?new O:"Defined"===b.instance?new U(p(c&&c[0]?c[0]:"automatic"===a[0]?["automatic"]:["unknown"],b.slot1)):"Undefined"===b.instance?new P:"Content"===b.instance?new V(p(["user","DString",[]],b.slot1)):"Element"===b.instance?new F(p(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new K(p(["user","DString",[]],b.slot1),p(["user","DString",[]],b.slot2)):"Complete"===b.instance?new B:"M"===b.instance?new wa(b.slot1,b.slot2):"L"===b.instance?new ya(b.slot1,b.slot2):
"H"===b.instance?new sa(b.slot1):"V"===b.instance?new ra(b.slot1):"A"===b.instance?new xa(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6,b.slot7):"C"===b.instance?new fb(b.slot1,b.slot2,b.slot3,b.slot4,b.slot5,b.slot6):"S"===b.instance?new gb(b.slot1,b.slot2,b.slot3,b.slot4):"Q"===b.instance?new hb(b.slot1,b.slot2,b.slot3,b.slot4):"T"===b.instance?new ib(b.slot1,b.slot2):"Z"===b.instance?new Ca:"Translate"===b.instance?new X(b.slot1,b.slot2):"Rotate"===b.instance?new da(b.slot1,b.slot2,b.slot3):
"Scale"===b.instance?new ea(b.slot1):"Scale2d"===b.instance?new fa(b.slot1,b.slot2):"Content"===b.instance?new V(p(["user","DString",[]],b.slot1)):"Element"===b.instance?new F(p(["user","DString",[]],b.slot1)):"Attribute"===b.instance?new K(p(["user","DString",[]],b.slot1),p(["user","DString",[]],b.slot2)):"Complete"===b.instance?new B:b):c=b,f=c):l(Error("Unhandled JS->Fay translation type: "+d))}return f}function q(a,b){this.d=a;this.c=b}function h(a){for(var b=s,d=a.length-1;0<=d;d--)b=new q(a[d],
b);return b}function v(a){return function(b){return new q(a,b)}}function M(e,b){return new f(function(){return a(e)*a(b)})}function Ua(e){return function(b){return new f(function(){return a(e)+a(b)})}}function t(e,b){return new f(function(){return a(e)+a(b)})}function R(e,b){return new f(function(){return a(e)-a(b)})}function ia(e){return function(b){return new f(function(){return a(e)/a(b)})}}function nc(e){return new f(function(){return a(e)>a(0)})}function Pa(e){return new f(function(){return a(e)<
a(0)})}function Mb(e){return new f(function(){return a(e)>=a(0)})}f.prototype.l=function(a){return a?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var ac=new f(function(){return Math.PI}),nb=new f(function(){return a(Ma(sc))(s)}),cc=new f(function(){return a(u(function(e){return a(u(pb))(e)}))(ob)}),fc=new f(function(){return a(u(function(e){return a(u(function(b){return a(u(tc))(b)}))(e)}))(qc)}),uc=new f(function(){return a(u(function(e){return a(u(pb))(e)}))(rc)}),
J=new f(function(){return new B}),E=new f(function(){return s}),n=new f(function(){return la(v)}),y=new f(function(){return la(oa)}),vc=new f(function(){return new w(p(["user","Node",[]],document.documentElement))}),kb=new f(function(){return r(h("attributeName"))}),qb=new f(function(){return r(h("begin"))}),Da=new f(function(){return r(h("d"))}),rb=new f(function(){return r(h("end"))}),W=new f(function(){return r(h("fill"))}),Ea=new f(function(){return r(h("id"))}),lb=new f(function(){return r(h("repeatCount"))}),
sb=new f(function(){return r(h("stroke"))}),tb=new f(function(){return r(h("stroke-width"))}),ub=new f(function(){return r(h("transform"))}),vb=new f(function(){return r(h("values"))}),wc=new f(function(){return ta(h("animate"))}),wb=new f(function(){return ta(h("path"))}),xc=new f(function(){return h("http://www.w3.org/2000/svg")}),ka=new f(function(){return new Ca}),na=new f(function(){return La(kc)}),yc=new f(function(){return a(u(pc))(na)}),zc=new f(function(){return a(u(Da))(na)}),Ac=new f(function(){return a(u(Da))(yc)}),
Bc=new f(function(){return a(u(function(e){return a(a(n)(a(a(n)(E))(wb)))(e)}))(zc)}),Fa=new f(function(){return a(u(function(e){return a(a(n)(a(a(n)(E))(wb)))(e)}))(Ac)}),Cc=new f(function(){return a(u(ub))(a(u(mb(h(","))))(ob(function(a){return new f(function(){return x(Hb(a),x(h("("),x(Ib(a),h(")"))))})})))}),Ga=new f(function(){return a(u(function(e){return a(u(function(b){return a(u(function(b){return a(a(y)(a(a(n)(E))(wc)))(b)}))(b)}))(e)}))(lc)}),Dc=new f(function(){return a(a(n)(a(a(n)(E))(a(qb)(h("indefinite")))))(a(rb)(h("indefinite")))}),
Fc=new f(function(){return a(u(vb))(Ec)}),Ec=new f(function(){return mb(h(";"))}),Gc=new f(function(){return oc(xc)}),Ha=new f(function(){return r(h("class"))}),mc=new f(function(){return a(u(r(h("dur"))))(ma)}),Ob=new f(function(){return a(u(r(h("from"))))(ma)}),Hc=new f(function(){return a(u(r(h("opacity"))))(ma)}),Pb=new f(function(){return a(u(r(h("to"))))(ma)}),r=function(a){return function(b){return new f(function(){return new K(a,b)})}},J=new f(function(){return new B}),E=new f(function(){return s}),
n=new f(function(){return la(v)}),y=new f(function(){return la(oa)}),Na=function(e){return function(b){return new f(function(){var d=b;if(a(e)instanceof F)return t(d,1);d=b;return a(e)instanceof B?R(d,1):d=b})}},kb=new f(function(){return r(h("attributeName"))}),qb=new f(function(){return r(h("begin"))}),Da=new f(function(){return r(h("d"))}),rb=new f(function(){return r(h("end"))}),W=new f(function(){return r(h("fill"))}),Ea=new f(function(){return r(h("id"))}),lb=new f(function(){return r(h("repeatCount"))}),
sb=new f(function(){return r(h("stroke"))}),tb=new f(function(){return r(h("stroke-width"))}),ub=new f(function(){return r(h("transform"))}),vb=new f(function(){return r(h("values"))}),Ic=new f(function(){function e(b){return function(c){return function(d){return new f(function(){return a(a(y)(a(a(n)(a(a(n)(a(a(n)(a(a(a(Ga)(h("d")))(k))(1)))(Ia)))(a(Ha)(b))))(a(Fc)(h([a(na)(c),a(na)(d)])))))(Dc)})}}}function b(b){return function(c){return function(d){return new f(function(){return Nb(qa(a(a(y)(a(a(n)(a(Bc)(b)))(a(W)(d))))(a(a(a(e)(h("B")))(b))(c)),
a(a(a(e)(h("P")))(c))(b)),J)})}}}var d=new f(function(){return a(a(n)(a(a(n)(a(a(n)(qa(a(a(n)(a(a(y)(a(a(n)(qa(a(a(n)(a(a(y)(a(a(n)(a(a(n)(a(a(y)(a(a(n)(a(a(y)(a(a(n)(a(a(n)(a(a(y)(a(a(n)(a(a(n)(a(Fa)(h([$(C,C),Z(G),S(G)]))))(a(W)(h("none")))))(a(Hc)(0))))(a(a(a(Ga)(h("opacity")))(k))(1))))(a(Ha)(h("B")))))(Ia)))(Qa(0,0.6))))(J)))(a(a(a(Ga)(h("opacity")))(k))(1))))(a(Ha)(h("P")))))(Ia)))(Qa(0.6,0))))(J),a(Fa)(h([$(t(t(C,G),20),t(C,40)),N(0,-20),ua(20,20,1,1,20,20),ka])))))(a(W)(h("plum")))))(xb)))(a(Ea)(h("pBtn"))),
a(Fa)(h([$(t(t(C,G),0),t(C,80)),S(10),Z(20),S(10),Z(-10),S(10),Z(10),S(10),Z(20),S(-40),ka])))))(a(W)(h("tan")))))(a(Ea)(h("bBtn")))))(J)}),c=new f(function(){return a(a(y)(a(a(n)(a(a(n)(E))(ta(h("g")))))(a(Cc)(h([Qb(g,g)])))))(xb)}),g=new f(function(){return M(Rb(C),1.25)}),k=2.5;return A(a(a(uc)(Sa(yb)))(Sb(Tb(G))),function(e){return function(){var g=new f(function(){return Ub(e)});return function(){var k=new f(function(){return Xb(e)});return function(){var e=new f(function(){return Ra(nb,Va(b,
k,g,yb))});return H(A(vc,a(Gc)(a(a(y)(a(a(y)(c))(e)))(d))),H(A(Wa(h("pBtn")),a(jb(h("click")))(jc)),A(Wa(h("bBtn")),a(jb(h("click")))(ic))))}()}()}()})}),C=new f(function(){return-200}),G=400,yb=new f(function(){return h([h("lightpink"),h("lightblue"),h("lightsalmon"),h("lightgreen"),h("khaki"),h("cyan")])}),xb=new f(function(){return a(a(n)(a(a(n)(E))(a(sb)(h("white")))))(a(tb)(h("4")))}),Ia=new f(function(){return a(W)(h("freeze"))}),Jc=new f(function(){return hc(h("load"),Ic)}),T=aa("a"),O=function(){},
U=aa("a"),P=function(){},V=aa("a"),F=aa("a"),K=function(a,b){this.a=a;this.b=b},B=function(){};this.j=Jc;this.k=a};zb.k(zb.j);
