function m(A){throw A;}var n=void 0,r=null;function G(A){return function(S){this[A]=S}}
var Aa=new function(){function A(b,a){return new f(function(){var c=a,d=e(b);if(d instanceof s){var g=d.b,d=d.c;return e(e(B)(g))(A(d,c))}c=a;if(e(b)===r)return c;m(["unhandled case in conc",[b,a]])})}function S(b,a,c){return new f(function(){return new w(k(["user","Node",[]],l(["user","Node",[]],c).setAttributeNS(r,z(b),z(a))&&r||l(["user","Node",[]],c)))})}function Ba(b,a){return new f(function(){return new w(k(["user","Node",[]],document.createElementNS(z(b),z(a))))})}function Ca(b){return new f(function(){return new w(k(["user",
"Node",[]],l(["user","Node",[]],b).parentNode))})}function Da(b){return new f(function(){return new w(k(["user","Node",[]],document.createTextNode(z(b))))})}function aa(b,a,c){return new f(function(){if(e(c)===r){var d=a;return new w(d)}var g=e(c);if(g instanceof s){var d=g.b,f=g.c;return H(e(e(b)(a))(d),function(a){return aa(b,a,f)})}m(["unhandled case in foldM",[b,a,c]])})}function Ea(b,a){return new f(function(){return M(e(e(q)(I))(b),a)})}function Fa(b){return new f(function(){return new x(b)})}
function Ga(b){return new f(function(){return function(){var a=new f(function(){return T(O,0,b)});return e(Ha(a))?y(U(a,C),b):ba(h("Markup has more close elements than open"))}()})}function t(b){return new f(function(){return new u(b)})}function T(b,a,c){return new f(function(){if(e(c)===r){var d=a;return d}d=e(c);if(d instanceof s){var g=d.b,f=d.c,d=a;return e(e(b)(g))(T(b,d,f))}m(["unhandled case in foldr",[b,a,c]])})}function ba(b){return new f(function(){m(z(b))})}function V(b){return new f(function(){var a=
e(b);if(a instanceof s)return y(V(a.c),h([a.b]));if(e(b)===r)return r;m(["unhandled case in reverse",[b]])})}function ca(b,a,c){return new f(function(){var d=e(e(B)(a)),g;if(e(c)===r)g=r;else{var f=e(c);f instanceof s?(g=f.b,f=f.c,g=ca(b,e(e(b)(a))(g),f)):m(["unhandled case",c])}return d(g)})}function U(b,a){return new f(function(){return 0===e(b)?r:e(Ia(b))?ba(h("replicate: negative length")):e(e(B)(a))(U(P(b),a))})}function y(b,a){return new f(function(){return A(b,a)})}function Ja(b,a){return new f(function(){return e(b)(a)})}
function da(b,a,c){return new f(function(){var d=e(c);if(d instanceof s){var g=d.b,f=d.c,d=e(a);if(d instanceof s){var h=d.b,d=d.c;return e(e(B)(e(e(b)(h))(g)))(da(b,d,f))}}return r})}function Ka(b,a){return new f(function(){return new w(k(["unknown"],window.addEventListener(z(b),l(["action",[["unknown"]]],a),e(!1))))})}function ea(b,a){return new f(function(){return e(e(N)(e(e(q)(b))(C)))(a)})}function Q(b,a){return new f(function(){if(e(a)instanceof p){var c=b;return Ga(c)}c=b;return e(e(q)(e(e(q)(c))(C)))(a)})}
function M(b,a){return new f(function(){return e(e(q)(b))(Fa(a))})}function fa(b){return new f(function(){return new w(k(["user","Node",[]],document.getElementById(z(b))))})}function ga(b){return new f(function(){var a=k,c=z(b);console&&console.log&&console.log(c);return new w(a(["unknown"],n))})}function ha(b){return new f(function(){return function(){function a(a){return new f(function(){if(e(a)instanceof u){var b=e(a).a;return y(h("<"),y(b,h(">")))}if(e(a)instanceof v){var b=e(a).a,c=e(a).d;return y(b,
y(h('="'),y(c,h('"'))))}if(e(a)instanceof x)return b=e(a).a,y(h('"'),y(b,h('"')));if(e(a)instanceof p)return h("<--");m(["unhandled case in go",[a]])})}var c=new f(function(){return V(b)});return Ja(La,da(function(b){return function(c){return new f(function(){return y(U(Ma(b)," "),y(e(a)(c),h("\n")))})}},new f(function(){return ca(D(O),0,c)}),c))}()})}function W(b,a){var c=e(a),d=b[2];if(c instanceof J){var g={instance:"Nullable"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a);
n!==d&&(g.slot1=d);return g}return c instanceof E?g={instance:"Null"}:c instanceof K?(g={instance:"Defined"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a),n!==d&&(g.slot1=d),g):c instanceof F?g={instance:"Undefined"}:c instanceof ia?(g={instance:"Just"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a),n!==d&&(g.slot1=d),g):c instanceof ja?g={instance:"Nothing"}:c instanceof ka?(g={instance:"Left"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],
c.a),n!==d&&(g.slot1=d),g):c instanceof la?(g={instance:"Right"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a),n!==d&&(g.slot1=d),g):c instanceof ma?(g={instance:"Ratio"},d=e(c.a),n!==d&&(g.slot1=d),c=e(c.d),n!==c&&(g.slot2=c),g):c instanceof na?g={instance:"GT"}:c instanceof oa?g={instance:"LT"}:c instanceof pa?g={instance:"EQ"}:c instanceof J?(g={instance:"Nullable"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a),n!==d&&(g.slot1=d),g):c instanceof E?g={instance:"Null"}:
c instanceof K?(g={instance:"Defined"},d=l(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.a),n!==d&&(g.slot1=d),g):c instanceof F?g={instance:"Undefined"}:c instanceof x?(g={instance:"Content"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof u?(g={instance:"Element"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof v?(g={instance:"Attribute"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),c=l(["user","DString",[]],c.d),n!==c&&(g.slot2=c),g):c instanceof
p?g={instance:"Complete"}:c instanceof x?(g={instance:"Content"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof u?(g={instance:"Element"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof v?(g={instance:"Attribute"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),c=l(["user","DString",[]],c.d),n!==c&&(g.slot2=c),g):c instanceof p?g={instance:"Complete"}:c instanceof x?(g={instance:"Content"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof u?(g=
{instance:"Element"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),g):c instanceof v?(g={instance:"Attribute"},d=l(["user","DString",[]],c.a),n!==d&&(g.slot1=d),c=l(["user","DString",[]],c.d),n!==c&&(g.slot2=c),g):c instanceof p?g={instance:"Complete"}:a}function p(){}function v(b,a){this.a=b;this.d=a}function u(b){this.a=b}function x(b){this.a=b}function pa(){}function oa(){}function na(){}function ma(b,a){this.a=b;this.d=a}function la(b){this.a=b}function ka(b){this.a=b}function ja(){}function ia(b){this.a=
b}function F(){}function K(b){this.a=b}function E(){}function J(b){this.a=b}function qa(b){return function(a){return function(c){return new f(function(){return e(e(q)(Ea(b,c)))(e(Na)(a))})}}}function ra(b){return function(a){return new f(function(){return M(e(e(q)(I))(b),a)})}}function Oa(b){return function(a){return function(c){return new f(function(){return function(){return aa(function(a){return function(c){return new f(function(){if(e(c)instanceof v){var f=e(c).a,h=e(c).d,k=a;return S(f,h,k)}if(e(c)instanceof
u)return f=e(c).a,k=a,H(Ba(b,f),sa(k));if(e(c)instanceof p)return k=a,Ca(k);if(e(c)instanceof x)return h=e(c).a,k=a,R(H(Da(h),sa(k)),new w(k));m(["unhandled case in go",[a,c]])})}},c,V(a))}()})}}}function sa(b){return function(a){return new f(function(){return new w(k(["user","Node",[]],l(["user","Node",[]],b).appendChild(l(["user","Node",[]],a))&&r||l(["user","Node",[]],a)))})}}function O(b){return function(a){return new f(function(){var c=a;if(e(b)instanceof u)return X(c);c=a;return e(b)instanceof
p?P(c):c=a})}}function L(b){return function(a){return new f(function(){return new v(b,a)})}}function Y(b){return function(a){return new f(function(){return A(b,a)})}}function Pa(b){return function(a){return function(c){return new f(function(){if(e(c)===r){var d=a;return d}d=e(c);if(d instanceof s){var g=d.b,f=d.c,d=a;return e(e(b)(g))(T(b,d,f))}m(["unhandled case in foldr",[b,a,c]])})}}}function Qa(b){return function(a){return new f(function(){var c=a,d=e(b);if(d instanceof s){var f=d.b,d=d.c;return e(e(B)(f))(A(d,
c))}c=a;if(e(b)===r)return c;m(["unhandled case in conc",[b,a]])})}}function D(b){return function(a){return function(c){return new f(function(){return e(e(b)(c))(a)})}}}function e(b,a){for(;b instanceof f;)b=b.h(a);return b}function f(b){this.e=!1;this.value=b}function w(b){this.value=b}function R(b,a){return H(b,function(){return a})}function H(b,a){return new f(function(){var c=e(b,!0);return e(a)(c.value)})}function l(b,a){var c=b[0],d=b[1],g;if("action"==c)g=function(){return l(d[0],e(a,!0).value)};
else if("function"==c)g=function(){var b=a,c=d[d.length-1],f=d.length;if(1<f){for(var b=e(b,!0),g=0;g<f-1&&b instanceof Function;g++)b=e(b(k(d[g],arguments[g])),!0);f=c[1];return"action"==c[0]?l(f[0],b.value):l(c,b)}m(Error("Nullary function?"))};else if("string"==c)g=z(a);else if("list"==c){c=[];for(a=e(a);a instanceof s;)c.push(l(d[0],a.b)),a=e(a.c);g=c}else if("tuple"==c){c=[];a=e(a);for(g=0;a instanceof s;)c.push(l(d[g++],a.b)),a=e(a.c);g=c}else if("defined"==c)a=e(a),g=a instanceof F?n:W(d[0],
a.slot1);else if("nullable"==c)a=e(a),g=a instanceof E?r:W(d[0],a.slot1);else if("double"==c||"int"==c||"bool"==c)g=e(a);else{if("ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a instanceof f&&(a=e(a)),g=W(b,a)):m(Error("Unhandled Fay->JS translation type: "+c))}return g}function z(b){var a="";for(b=e(b);b instanceof s;)a+=b.b,b=e(b.c);return a}function k(b,a){var c=b[0],d=b[1],e;if("action"==c)e=new w(k(d[0],a));else if("string"==c)e=h(a);else if("list"==c){var f=[],c=0;for(e=a.length;c<
e;c++)f.push(k(d[0],a[c]));e=h(f)}else if("tuple"==c){f=[];c=0;for(e=a.length;c<e;c++)f.push(k(d[c],a[c]));e=h(f)}else if("defined"==c)e=a===n?new F:new K(k(d[0],a));else if("nullable"==c)e=a===r?new E:new J(k(d[0],a));else if("int"==c)e=Math.round(a),e!==a&&m("Argument "+a+" is not an integer!");else{if("double"==c||"bool"==c||"ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a&&a.instance?(d=b[2],d="Nullable"===a.instance?new J(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],
a.slot1)):"Null"===a.instance?new E:"Defined"===a.instance?new K(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new F:"Just"===a.instance?new ia(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ja:"Left"===a.instance?new ka(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new la(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?
new ma(a.slot1,a.slot2):"GT"===a.instance?new na:"LT"===a.instance?new oa:"EQ"===a.instance?new pa:"Nullable"===a.instance?new J(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new E:"Defined"===a.instance?new K(k(d&&d[0]?d[0]:"automatic"===b[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new F:"Content"===a.instance?new x(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new u(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?
new v(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new p:"Content"===a.instance?new x(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new u(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new v(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new p:"Content"===a.instance?new x(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new u(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?
new v(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new p:a):d=a,e=d):m(Error("Unhandled JS->Fay translation type: "+c))}return e}function s(b,a){this.b=b;this.c=a}function h(b){for(var a=r,c=b.length-1;0<=c;c--)a=new s(b[c],a);return a}function B(b){return function(a){return new s(b,a)}}function Ma(b){return new f(function(){return e(b)*e(4)})}function X(b){return new f(function(){return e(b)+e(1)})}function P(b){return new f(function(){return e(b)-e(1)})}
function Ia(b){return new f(function(){return e(b)<e(0)})}function Ha(b){return new f(function(){return e(b)>=e(0)})}f.prototype.h=function(b){return b?this.value():this.e?this.value:(this.value=this.value(),this.e=!0,this.value)};var La=new f(function(){return e(Pa(Qa))(r)}),C=new f(function(){return new p}),I=new f(function(){return r}),q=new f(function(){return D(B)}),N=new f(function(){return D(Y)}),ta=new f(function(){return L(h("id"))}),ua=new f(function(){return t(h("b"))}),Z=new f(function(){return t(h("div"))}),
va=new f(function(){return t(h("h1"))}),wa=new f(function(){return t(h("h4"))}),xa=new f(function(){return t(h("i"))}),$=new f(function(){return t(h("p"))}),ya=new f(function(){return t(h("style"))}),Ra=new f(function(){return h("http://www.w3.org/1999/xhtml")}),Sa=new f(function(){return qa(Z)}),Ta=new f(function(){return qa($)}),Ua=new f(function(){return ra(xa)}),Va=new f(function(){return ra(ua)}),za=new f(function(){return Oa(Ra)}),Na=new f(function(){return L(h("class"))}),Wa=new f(function(){return L(h("type"))}),
L=function(b){return function(a){return new f(function(){return new v(b,a)})}},C=new f(function(){return new p}),I=new f(function(){return r}),q=new f(function(){return D(B)}),N=new f(function(){return D(Y)}),O=function(b){return function(a){return new f(function(){var c=a;if(e(b)instanceof u)return X(c);c=a;return e(b)instanceof p?P(c):c=a})}},ua=new f(function(){return t(h("b"))}),Z=new f(function(){return t(h("div"))}),va=new f(function(){return t(h("h1"))}),wa=new f(function(){return t(h("h4"))}),
xa=new f(function(){return t(h("i"))}),$=new f(function(){return t(h("p"))}),ya=new f(function(){return t(h("style"))}),L=function(b){return function(a){return new f(function(){return new v(b,a)})}},C=new f(function(){return new p}),I=new f(function(){return r}),q=new f(function(){return D(B)}),N=new f(function(){return D(Y)}),O=function(b){return function(a){return new f(function(){var c=a;if(e(b)instanceof u)return X(c);c=a;return e(b)instanceof p?P(c):c=a})}},ta=new f(function(){return L(h("id"))}),
Ya=new f(function(){return Ka(h("load"),Xa)}),Xa=new f(function(){var b=new f(function(){return Q(ea(ea(M(Q(M(Q(Q(e(e(N)(e(e(N)(e(e(q)(e(e(q)(e(e(q)(I))(Z)))(e(ta)(h("foo")))))($)))(e(Ua)(h("hello ")))))(e(Va)(h("there"))),C),va),h("someshit")),wa),h("othershit")),e(e(Sa)(h("classy")))(h("some lovely content in a div"))),e(e(Ta)(h("classy")))(h("and some in a classed p"))),C)}),a=new f(function(){return e(e(q)(M(e(e(q)(e(e(q)(I))(ya)))(e(Wa)(h("text/css"))),h(".classy {border: solid blue 2px;}"))))(C)});
return R(R(H(R(H(fa(h("BODY")),e(za)(b)),fa(h("HEAD"))),e(za)(a)),ga(ha(a))),ga(ha(b)))}),J=G("a"),E=function(){},K=G("a"),F=function(){},x=G("a"),u=G("a"),v=function(b,a){this.a=b;this.d=a},p=function(){},x=G("a"),u=G("a"),v=function(b,a){this.a=b;this.d=a},p=function(){};this.f=Ya;this.g=e};Aa.g(Aa.f);
