function m(B){throw B;}var n=void 0,r=null;function H(B){return function(T){this[B]=T}}
var Ba=new function(){function B(c,a){return new f(function(){var b=a,d=e(c);if(d instanceof s){var g=d.c,d=d.d;return e(e(C)(g))(B(d,b))}b=a;if(e(c)===r)return b;m(["unhandled case in conc",[c,a]])})}function T(c,a,b){return new f(function(){return new x(k(["user","Node",[]],l(["user","Node",[]],b).setAttributeNS(r,y(c),y(a))&&r||l(["user","Node",[]],b)))})}function Ca(c,a){return new f(function(){return new x(k(["user","Node",[]],document.createElementNS(y(c),y(a))))})}function Da(c){return new f(function(){return new x(k(["user",
"Node",[]],l(["user","Node",[]],c).parentNode))})}function Ea(c,a,b){return new f(function(){return new x(k(["user","Node",[]],(l(["user","Node",[]],b)[y(c)]=y(a))&&r||l(["user","Node",[]],b)))})}function Fa(c){return new f(function(){return new x(k(["user","Node",[]],document.createTextNode(y(c))))})}function ba(c,a,b){return new f(function(){if(e(b)===r){var d=a;return new x(d)}var g=e(b);if(g instanceof s){var d=g.c,f=g.d;return I(e(e(c)(a))(d),function(a){return ba(c,a,f)})}m(["unhandled case in foldM",
[c,a,b]])})}function Ga(c,a){return new f(function(){return N(e(e(q)(J))(c),a)})}function Ha(c){return new f(function(){return new z(c)})}function Ia(c){return new f(function(){return function(){var a=new f(function(){return U(P,0,c)});return e(Ja(a))?t(V(a,D),c):ca(h("Markup has more close elements than open"))}()})}function u(c){return new f(function(){return new v(c)})}function U(c,a,b){return new f(function(){if(e(b)===r){var d=a;return d}d=e(b);if(d instanceof s){var g=d.c,f=d.d,d=a;return e(e(c)(g))(U(c,
d,f))}m(["unhandled case in foldr",[c,a,b]])})}function ca(c){return new f(function(){m(y(c))})}function W(c){return new f(function(){var a=e(c);if(a instanceof s)return t(W(a.d),h([a.c]));if(e(c)===r)return r;m(["unhandled case in reverse",[c]])})}function da(c,a,b){return new f(function(){var d=e(e(C)(a)),g;if(e(b)===r)g=r;else{var f=e(b);f instanceof s?(g=f.c,f=f.d,g=da(c,e(e(c)(a))(g),f)):m(["unhandled case",b])}return d(g)})}function V(c,a){return new f(function(){return 0===e(c)?r:e(Ka(c))?
ca(h("replicate: negative length")):e(e(C)(a))(V(Q(c),a))})}function t(c,a){return new f(function(){return B(c,a)})}function La(c,a){return new f(function(){return e(c)(a)})}function ea(c,a,b){return new f(function(){var d=e(b);if(d instanceof s){var g=d.c,f=d.d,d=e(a);if(d instanceof s){var h=d.c,d=d.d;return e(e(C)(e(e(c)(h))(g)))(ea(c,d,f))}}return r})}function Ma(c,a){return new f(function(){return new x(k(["unknown"],window.addEventListener(y(c),l(["action",[["unknown"]]],a),e(!1))))})}function fa(c,
a){return new f(function(){return e(e(O)(e(e(q)(c))(D)))(a)})}function R(c,a){return new f(function(){if(e(a)instanceof p){var b=c;return Ia(b)}b=c;return e(e(q)(e(e(q)(b))(D)))(a)})}function N(c,a){return new f(function(){return e(e(q)(c))(Ha(a))})}function ga(c){return new f(function(){return new x(k(["user","Node",[]],document.getElementById(y(c))))})}function ha(c){return new f(function(){var a=k,b=y(c);console&&console.log&&console.log(b);return new x(a(["unknown"],n))})}function ia(c){return new f(function(){return function(){function a(a){return new f(function(){if(e(a)instanceof
v){var c=e(a).a;return t(h("<"),t(c,h(">")))}if(e(a)instanceof w){var c=e(a).a,b=e(a).b;return t(c,t(h('="'),t(b,h('"'))))}if(e(a)instanceof A)return c=e(a).a,b=e(a).b,t(c,t(h('="'),t(b,h('"'))));if(e(a)instanceof z)return c=e(a).a,t(h('"'),t(c,h('"')));if(e(a)instanceof p)return h("<--");m(["unhandled case in go",[a]])})}var b=new f(function(){return W(c)});return La(Na,ea(function(c){return function(b){return new f(function(){return t(V(Oa(c)," "),t(e(a)(b),h("\n")))})}},new f(function(){return da(E(P),
0,b)}),b))}()})}function X(c,a){var b=e(a),d=c[2];if(b instanceof K){var g={instance:"Nullable"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a);n!==d&&(g.slot1=d);return g}return b instanceof F?g={instance:"Null"}:b instanceof L?(g={instance:"Defined"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof G?g={instance:"Undefined"}:b instanceof ja?(g={instance:"Just"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],
b.a),n!==d&&(g.slot1=d),g):b instanceof ka?g={instance:"Nothing"}:b instanceof la?(g={instance:"Left"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof ma?(g={instance:"Right"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof na?(g={instance:"Ratio"},d=e(b.a),n!==d&&(g.slot1=d),b=e(b.b),n!==b&&(g.slot2=b),g):b instanceof oa?g={instance:"GT"}:b instanceof pa?g={instance:"LT"}:b instanceof qa?g=
{instance:"EQ"}:b instanceof K?(g={instance:"Nullable"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof F?g={instance:"Null"}:b instanceof L?(g={instance:"Defined"},d=l(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof G?g={instance:"Undefined"}:b instanceof z?(g={instance:"Content"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof v?(g={instance:"Element"},d=l(["user","DString",
[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Attribute"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof A?(g={instance:"Property"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof p?g={instance:"Complete"}:b instanceof z?(g={instance:"Content"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof v?(g={instance:"Element"},d=l(["user","DString",
[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Attribute"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof A?(g={instance:"Property"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof p?g={instance:"Complete"}:b instanceof z?(g={instance:"Content"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof v?(g={instance:"Element"},d=l(["user","DString",
[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Attribute"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof A?(g={instance:"Property"},d=l(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=l(["user","DString",[]],b.b),n!==b&&(g.slot2=b),g):b instanceof p?g={instance:"Complete"}:a}function p(){}function A(c,a){this.a=c;this.b=a}function w(c,a){this.a=c;this.b=a}function v(c){this.a=c}function z(c){this.a=c}function qa(){}
function pa(){}function oa(){}function na(c,a){this.a=c;this.b=a}function ma(c){this.a=c}function la(c){this.a=c}function ka(){}function ja(c){this.a=c}function G(){}function L(c){this.a=c}function F(){}function K(c){this.a=c}function ra(c){return function(a){return function(b){return new f(function(){return e(e(q)(Ga(c,b)))(e(Pa)(a))})}}}function sa(c){return function(a){return new f(function(){return N(e(e(q)(J))(c),a)})}}function Qa(c){return function(a){return function(b){return new f(function(){return function(){return ba(function(a){return function(b){return new f(function(){if(e(b)instanceof
w){var f=e(b).a,h=e(b).b,k=a;return T(f,h,k)}if(e(b)instanceof v)return f=e(b).a,k=a,I(Ca(c,f),ta(k));if(e(b)instanceof p)return k=a,Da(k);if(e(b)instanceof A)return f=e(b).a,h=e(b).b,k=a,Ea(f,h,k);if(e(b)instanceof z)return h=e(b).a,k=a,S(I(Fa(h),ta(k)),new x(k));m(["unhandled case in go",[a,b]])})}},b,W(a))}()})}}}function ta(c){return function(a){return new f(function(){return new x(k(["user","Node",[]],l(["user","Node",[]],c).appendChild(l(["user","Node",[]],a))&&r||l(["user","Node",[]],a)))})}}
function P(c){return function(a){return new f(function(){var b=a;if(e(c)instanceof v)return Y(b);b=a;return e(c)instanceof p?Q(b):b=a})}}function M(c){return function(a){return new f(function(){return new w(c,a)})}}function Z(c){return function(a){return new f(function(){return B(c,a)})}}function Ra(c){return function(a){return function(b){return new f(function(){if(e(b)===r){var d=a;return d}d=e(b);if(d instanceof s){var g=d.c,f=d.d,d=a;return e(e(c)(g))(U(c,d,f))}m(["unhandled case in foldr",[c,
a,b]])})}}}function Sa(c){return function(a){return new f(function(){var b=a,d=e(c);if(d instanceof s){var g=d.c,d=d.d;return e(e(C)(g))(B(d,b))}b=a;if(e(c)===r)return b;m(["unhandled case in conc",[c,a]])})}}function E(c){return function(a){return function(b){return new f(function(){return e(e(c)(b))(a)})}}}function e(c,a){for(;c instanceof f;)c=c.h(a);return c}function f(c){this.e=!1;this.value=c}function x(c){this.value=c}function S(c,a){return I(c,function(){return a})}function I(c,a){return new f(function(){var b=
e(c,!0);return e(a)(b.value)})}function l(c,a){var b=c[0],d=c[1],g;if("action"==b)g=function(){return l(d[0],e(a,!0).value)};else if("function"==b)g=function(){var b=a,c=d[d.length-1],g=d.length;if(1<g){for(var b=e(b,!0),f=0;f<g-1&&b instanceof Function;f++)b=e(b(k(d[f],arguments[f])),!0);g=c[1];return"action"==c[0]?l(g[0],b.value):l(c,b)}m(Error("Nullary function?"))};else if("string"==b)g=y(a);else if("list"==b){b=[];for(a=e(a);a instanceof s;)b.push(l(d[0],a.c)),a=e(a.d);g=b}else if("tuple"==b){b=
[];a=e(a);for(g=0;a instanceof s;)b.push(l(d[g++],a.c)),a=e(a.d);g=b}else if("defined"==b)a=e(a),g=a instanceof G?n:X(d[0],a.slot1);else if("nullable"==b)a=e(a),g=a instanceof F?r:X(d[0],a.slot1);else if("double"==b||"int"==b||"bool"==b)g=e(a);else{if("ptr"==b||"unknown"==b)return a;"automatic"==b||"user"==b?(a instanceof f&&(a=e(a)),g=X(c,a)):m(Error("Unhandled Fay->JS translation type: "+b))}return g}function y(c){var a="";for(c=e(c);c instanceof s;)a+=c.c,c=e(c.d);return a}function k(c,a){var b=
c[0],d=c[1],e;if("action"==b)e=new x(k(d[0],a));else if("string"==b)e=h(a);else if("list"==b){var f=[],b=0;for(e=a.length;b<e;b++)f.push(k(d[0],a[b]));e=h(f)}else if("tuple"==b){f=[];b=0;for(e=a.length;b<e;b++)f.push(k(d[b],a[b]));e=h(f)}else if("defined"==b)e=a===n?new G:new L(k(d[0],a));else if("nullable"==b)e=a===r?new F:new K(k(d[0],a));else if("int"==b)e=Math.round(a),e!==a&&m("Argument "+a+" is not an integer!");else{if("double"==b||"bool"==b||"ptr"==b||"unknown"==b)return a;"automatic"==b||
"user"==b?(a&&a.instance?(d=c[2],d="Nullable"===a.instance?new K(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new F:"Defined"===a.instance?new L(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new G:"Just"===a.instance?new ja(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ka:"Left"===a.instance?new la(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],
a.slot1)):"Right"===a.instance?new ma(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new na(a.slot1,a.slot2):"GT"===a.instance?new oa:"LT"===a.instance?new pa:"EQ"===a.instance?new qa:"Nullable"===a.instance?new K(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new F:"Defined"===a.instance?new L(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new G:"Content"===a.instance?
new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new v(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new w(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new A(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new p:"Content"===a.instance?new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new v(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new w(k(["user","DString",
[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new A(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new p:"Content"===a.instance?new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new v(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new w(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new A(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===
a.instance?new p:a):d=a,e=d):m(Error("Unhandled JS->Fay translation type: "+b))}return e}function s(c,a){this.c=c;this.d=a}function h(c){for(var a=r,b=c.length-1;0<=b;b--)a=new s(c[b],a);return a}function C(c){return function(a){return new s(c,a)}}function Oa(c){return new f(function(){return e(c)*e(4)})}function Y(c){return new f(function(){return e(c)+e(1)})}function Q(c){return new f(function(){return e(c)-e(1)})}function Ka(c){return new f(function(){return e(c)<e(0)})}function Ja(c){return new f(function(){return e(c)>=
e(0)})}f.prototype.h=function(c){return c?this.value():this.e?this.value:(this.value=this.value(),this.e=!0,this.value)};var Na=new f(function(){return e(Ra(Sa))(r)}),D=new f(function(){return new p}),J=new f(function(){return r}),q=new f(function(){return E(C)}),O=new f(function(){return E(Z)}),ua=new f(function(){return M(h("id"))}),va=new f(function(){return u(h("b"))}),$=new f(function(){return u(h("div"))}),wa=new f(function(){return u(h("h1"))}),xa=new f(function(){return u(h("h4"))}),ya=new f(function(){return u(h("i"))}),
aa=new f(function(){return u(h("p"))}),za=new f(function(){return u(h("style"))}),Ta=new f(function(){return h("http://www.w3.org/1999/xhtml")}),Ua=new f(function(){return ra($)}),Va=new f(function(){return ra(aa)}),Wa=new f(function(){return sa(ya)}),Xa=new f(function(){return sa(va)}),Aa=new f(function(){return Qa(Ta)}),Pa=new f(function(){return M(h("class"))}),Ya=new f(function(){return M(h("type"))}),M=function(c){return function(a){return new f(function(){return new w(c,a)})}},D=new f(function(){return new p}),
J=new f(function(){return r}),q=new f(function(){return E(C)}),O=new f(function(){return E(Z)}),P=function(c){return function(a){return new f(function(){var b=a;if(e(c)instanceof v)return Y(b);b=a;return e(c)instanceof p?Q(b):b=a})}},va=new f(function(){return u(h("b"))}),$=new f(function(){return u(h("div"))}),wa=new f(function(){return u(h("h1"))}),xa=new f(function(){return u(h("h4"))}),ya=new f(function(){return u(h("i"))}),aa=new f(function(){return u(h("p"))}),za=new f(function(){return u(h("style"))}),
M=function(c){return function(a){return new f(function(){return new w(c,a)})}},D=new f(function(){return new p}),J=new f(function(){return r}),q=new f(function(){return E(C)}),O=new f(function(){return E(Z)}),P=function(c){return function(a){return new f(function(){var b=a;if(e(c)instanceof v)return Y(b);b=a;return e(c)instanceof p?Q(b):b=a})}},ua=new f(function(){return M(h("id"))}),$a=new f(function(){return Ma(h("load"),Za)}),Za=new f(function(){var c=new f(function(){return R(fa(fa(N(R(N(R(R(e(e(O)(e(e(O)(e(e(q)(e(e(q)(e(e(q)(J))($)))(e(ua)(h("foo")))))(aa)))(e(Wa)(h("hello ")))))(e(Xa)(h("there"))),
D),wa),h("someshit")),xa),h("othershit")),e(e(Ua)(h("classy")))(h("some lovely content in a div"))),e(e(Va)(h("classy")))(h("and some in a classed p"))),D)}),a=new f(function(){return e(e(q)(N(e(e(q)(e(e(q)(J))(za)))(e(Ya)(h("text/css"))),h(".classy {border: solid blue 2px;}"))))(D)});return S(S(I(S(I(ga(h("BODY")),e(Aa)(c)),ga(h("HEAD"))),e(Aa)(a)),ha(ia(a))),ha(ia(c)))}),K=H("a"),F=function(){},L=H("a"),G=function(){},z=H("a"),v=H("a"),w=function(c,a){this.a=c;this.b=a},A=function(c,a){this.a=c;
this.b=a},p=function(){},z=H("a"),v=H("a"),w=function(c,a){this.a=c;this.b=a},A=function(c,a){this.a=c;this.b=a},p=function(){};this.f=$a;this.g=e};Ba.g(Ba.f);
