function h(x){throw x;}var n=void 0,p=null;function K(x){return function(L){this[x]=L}}
var Ia=new function(){function x(d,a){return new g(function(){var c=a,b=e(d);if(b instanceof q){var f=b.c,b=b.d;return e(e(y)(f))(x(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}function L(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof q){var b=c.c,c=c.d;return e(e(y)(d))(e(e(y)(b))(L(d,c)))}h(["unhandled case in prependToAll",[d,a]])})}function Ja(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof q){var b=c.c,c=c.d;return e(e(y)(b))(L(d,
c))}h(["unhandled case in intersperse",[d,a]])})}function Ka(d,a,c){return new g(function(){return new r(k(["user","Node",[]],l(["user","Node",[]],c).setAttributeNS(p,v(d),v(a))&&p||l(["user","Node",[]],c)))})}function La(d,a){return new g(function(){return new r(k(["user","Node",[]],document.createElementNS(v(d),v(a))))})}function Ma(d){return new g(function(){return new r(k(["user","Node",[]],l(["user","Node",[]],d).parentNode))})}function Na(d,a,c){return new g(function(){return new r(k(["user",
"Node",[]],(l(["user","Node",[]],c)[v(d)]=v(a))&&p||l(["user","Node",[]],c)))})}function Oa(d){return new g(function(){return new r(k(["user","Node",[]],document.createTextNode(v(d))))})}function Y(d,a,c){return new g(function(){if(e(c)===p){var b=a;return new r(b)}var f=e(c);if(f instanceof q){var b=f.c,g=f.d;return I(e(e(d)(a))(b),function(a){return Y(d,a,g)})}h(["unhandled case in foldM",[d,a,c]])})}function Pa(d){return new g(function(){return M(l(["automatic"],d).instance+" ")})}function Z(d){return new g(function(){return e($(e(z(R))(d)))(p)})}
function Qa(d,a){return new g(function(){return M(l(["automatic"],a)["slot"+e(d)]!=p&&l(["automatic"],a)["slot"+e(d)]+" "||"")})}function Ra(d){return new g(function(){return function(){var a=new g(function(){return S(aa,0,d)});return e(Sa(a))?T(ba(a,N),d):ca(m("Markup has more close elements than open"))}()})}function da(d){return new g(function(){return new w(d)})}function S(d,a,c){return new g(function(){if(e(c)===p){var b=a;return b}b=e(c);if(b instanceof q){var f=b.c,g=b.d,b=a;return e(e(d)(f))(S(d,
b,g))}h(["unhandled case in foldr",[d,a,c]])})}function ca(d){return new g(function(){h(v(d))})}function Ta(d){return new g(function(){return M(JSON.stringify(l(["automatic"],d)))})}function ea(d){return new g(function(){var a=e(d);if(a instanceof q)return T(ea(a.d),m([a.c]));if(e(d)===p)return p;h(["unhandled case in reverse",[d]])})}function ba(d,a){return new g(function(){return 0===e(d)?p:e(Ua(d))?ca(m("replicate: negative length")):e(e(y)(a))(ba(U(d),a))})}function T(d,a){return new g(function(){return x(d,
a)})}function Va(d,a){return new g(function(){return new r(k(["unknown"],window.addEventListener(v(d),l(["action",[["unknown"]]],a),e(!1))))})}function Wa(d,a){return new g(function(){if(e(a)instanceof t){var c=d;return Ra(c)}c=d;return e(e(u)(e(e(u)(c))(N)))(a)})}function fa(d,a){return new g(function(){return new V(d,a)})}function A(d,a,c,b){return new g(function(){return new W(d,a,c,b)})}function X(d,a){var c=e(a),b=d[2];if(c instanceof E){var f={instance:"Nullable"},b=l(b&&b[0]?b[0]:"automatic"===
d[0]?["automatic"]:["unknown"],c.a);n!==b&&(f.slot1=b);return f}return c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:c instanceof ga?(f={instance:"Just"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof ha?f={instance:"Nothing"}:c instanceof ia?(f={instance:"Left"},b=l(b&&b[0]?b[0]:"automatic"===
d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof ja?(f={instance:"Right"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof ka?(f={instance:"Ratio"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof la?f={instance:"GT"}:c instanceof ma?f={instance:"LT"}:c instanceof na?f={instance:"EQ"}:c instanceof E?(f={instance:"Nullable"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=
b),f):c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:c instanceof G?(f={instance:"Content"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof w?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",
[]],c.b),n!==b&&(f.slot2=b),f):c instanceof H?(f={instance:"Property"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof t?f={instance:"Complete"}:c instanceof V?(f={instance:"M"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof oa?(f={instance:"L"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof pa?(f={instance:"H"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof qa?(f={instance:"V"},b=e(c.a),
n!==b&&(f.slot1=b),f):c instanceof ra?(f={instance:"A"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),c=e(c.m),n!==c&&(f.slot7=c),f):c instanceof sa?(f={instance:"C"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),f):c instanceof ta?(f={instance:"S"},b=e(c.a),
n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof W?(f={instance:"Q"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof ua?(f={instance:"T"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof va?f={instance:"Z"}:c instanceof wa?(f={instance:"Translate"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof xa?(f={instance:"Rotate"},
b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),f):c instanceof ya?(f={instance:"Scale"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof za?(f={instance:"Scale2d"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof G?(f={instance:"Content"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof w?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},b=l(["user","DString",
[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof H?(f={instance:"Property"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof t?f={instance:"Complete"}:a}function za(d,a){this.a=d;this.b=a}function ya(d){this.a=d}function xa(d,a,c){this.a=d;this.b=a;this.e=c}function wa(d,a){this.a=d;this.b=a}function va(){}function ua(d,a){this.a=d;this.b=a}function W(d,a,c,b){this.a=d;this.b=a;this.e=c;
this.f=b}function ta(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function sa(d,a,c,b,f,e){this.a=d;this.b=a;this.e=c;this.f=b;this.g=f;this.h=e}function ra(d,a,c,b,f,e,g){this.a=d;this.b=a;this.e=c;this.f=b;this.g=f;this.h=e;this.m=g}function qa(d){this.a=d}function pa(d){this.a=d}function oa(d,a){this.a=d;this.b=a}function V(d,a){this.a=d;this.b=a}function t(){}function H(d,a){this.a=d;this.b=a}function B(d,a){this.a=d;this.b=a}function w(d){this.a=d}function G(d){this.a=d}function na(){}function ma(){}
function la(){}function ka(d,a){this.a=d;this.b=a}function ja(d){this.a=d}function ia(d){this.a=d}function ha(){}function ga(d){this.a=d}function D(){}function F(d){this.a=d}function C(){}function E(d){this.a=d}function Xa(d){return new g(function(){return T(Pa(d),e(Z(function(a){return Qa(a,d)}))(m([1,2,3,4,5,6,7,8])))})}function Ya(d){return function(a){return function(c){return new g(function(){return function(){return e(e(u)(e(e(u)(e(e(u)(J))(e(Aa)(d))))(e(Za)(a))))(e(Ba)(e(function(a){return new g(function(){return e($a(a))?
Ta(a):m("indefinite")})})(c)))}()})}}}function ab(d){return function(a){return function(c){return new g(function(){return function(){return Y(function(a){return function(c){return new g(function(){if(e(c)instanceof B){var g=e(c).a,l=e(c).b,k=a;return Ka(g,l,k)}if(e(c)instanceof w)return g=e(c).a,k=a,I(La(d,g),Ca(k));if(e(c)instanceof t)return k=a,Ma(k);if(e(c)instanceof H)return g=e(c).a,l=e(c).b,k=a,Na(g,l,k);if(e(c)instanceof G)return l=e(c).a,k=a,Da(I(Oa(l),Ca(k)),new r(k));h(["unhandled case in go",
[a,c]])})}},c,ea(a))}()})}}}function Ca(d){return function(a){return new g(function(){return new r(k(["user","Node",[]],l(["user","Node",[]],d).appendChild(l(["user","Node",[]],a))&&p||l(["user","Node",[]],a)))})}}function aa(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof w)return Ea(c);c=a;return e(d)instanceof t?U(c):c=a})}}function s(d){return function(a){return new g(function(){return new B(d,a)})}}function bb(d){return function(a){return new g(function(){return e(cb)(Ja(d,
a))})}}function R(d){return function(a){return new g(function(){return x(d,a)})}}function $(d){return function(a){return function(c){return new g(function(){if(e(c)===p){var b=a;return b}b=e(c);if(b instanceof q){var f=b.c,g=b.d,b=a;return e(e(d)(f))(S(d,b,g))}h(["unhandled case in foldr",[d,a,c]])})}}}function db(d){return function(a){return new g(function(){var c=a,b=e(d);if(b instanceof q){var f=b.c,b=b.d;return e(e(y)(f))(x(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}}
function O(d){return function(a){return function(c){return new g(function(){return e(e(d)(c))(a)})}}}function z(d){return function(a){return function(c){return new g(function(){return e(d)(e(a)(c))})}}}function eb(d){return new g(function(){return M(JSON.stringify(l(["automatic"],d)))})}function e(d,a){for(;d instanceof g;)d=d.l(a);return d}function g(d){this.i=!1;this.value=d}function r(d){this.value=d}function Da(d,a){return I(d,function(){return a})}function I(d,a){return new g(function(){var c=
e(d,!0);return e(a)(c.value)})}function l(d,a){var c=d[0],b=d[1],f;if("action"==c)f=function(){return l(b[0],e(a,!0).value)};else if("function"==c)f=function(){var c=a,d=b[b.length-1],f=b.length;if(1<f){for(var c=e(c,!0),g=0;g<f-1&&c instanceof Function;g++)c=e(c(k(b[g],arguments[g])),!0);f=d[1];return"action"==d[0]?l(f[0],c.value):l(d,c)}h(Error("Nullary function?"))};else if("string"==c)f=v(a);else if("list"==c){c=[];for(a=e(a);a instanceof q;)c.push(l(b[0],a.c)),a=e(a.d);f=c}else if("tuple"==c){c=
[];a=e(a);for(f=0;a instanceof q;)c.push(l(b[f++],a.c)),a=e(a.d);f=c}else if("defined"==c)a=e(a),f=a instanceof D?n:X(b[0],a.slot1);else if("nullable"==c)a=e(a),f=a instanceof C?p:X(b[0],a.slot1);else if("double"==c||"int"==c||"bool"==c)f=e(a);else{if("ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a instanceof g&&(a=e(a)),f=X(d,a)):h(Error("Unhandled Fay->JS translation type: "+c))}return f}function v(d){var a="";for(d=e(d);d instanceof q;)a+=d.c,d=e(d.d);return a}function M(d){return m(d)}
function k(d,a){var c=d[0],b=d[1],e;if("action"==c)e=new r(k(b[0],a));else if("string"==c)e=m(a);else if("list"==c){var g=[],c=0;for(e=a.length;c<e;c++)g.push(k(b[0],a[c]));e=m(g)}else if("tuple"==c){g=[];c=0;for(e=a.length;c<e;c++)g.push(k(b[c],a[c]));e=m(g)}else if("defined"==c)e=a===n?new D:new F(k(b[0],a));else if("nullable"==c)e=a===p?new C:new E(k(b[0],a));else if("int"==c)e=Math.round(a),e!==a&&h("Argument "+a+" is not an integer!");else{if("double"==c||"bool"==c||"ptr"==c||"unknown"==c)return a;
"automatic"==c||"user"==c?(a&&a.instance?(b=d[2],b="Nullable"===a.instance?new E(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Just"===a.instance?new ga(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ha:"Left"===a.instance?new ia(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:
["unknown"],a.slot1)):"Right"===a.instance?new ja(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new ka(a.slot1,a.slot2):"GT"===a.instance?new la:"LT"===a.instance?new ma:"EQ"===a.instance?new na:"Nullable"===a.instance?new E(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Content"===
a.instance?new G(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new w(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new B(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new H(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new t:"M"===a.instance?new V(a.slot1,a.slot2):"L"===a.instance?new oa(a.slot1,a.slot2):"H"===a.instance?new pa(a.slot1):"V"===a.instance?new qa(a.slot1):"A"===a.instance?
new ra(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6,a.slot7):"C"===a.instance?new sa(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6):"S"===a.instance?new ta(a.slot1,a.slot2,a.slot3,a.slot4):"Q"===a.instance?new W(a.slot1,a.slot2,a.slot3,a.slot4):"T"===a.instance?new ua(a.slot1,a.slot2):"Z"===a.instance?new va:"Translate"===a.instance?new wa(a.slot1,a.slot2):"Rotate"===a.instance?new xa(a.slot1,a.slot2,a.slot3):"Scale"===a.instance?new ya(a.slot1):"Scale2d"===a.instance?new za(a.slot1,a.slot2):
"Content"===a.instance?new G(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new w(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new B(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new H(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new t:a):b=a,e=b):h(Error("Unhandled JS->Fay translation type: "+c))}return e}function q(d,a){this.c=d;this.d=a}function m(d){for(var a=p,c=d.length-1;0<=c;c--)a=
new q(d[c],a);return a}function y(d){return function(a){return new q(d,a)}}function Ea(d){return new g(function(){return e(d)+e(1)})}function U(d){return new g(function(){return e(d)-e(1)})}function $a(d){return new g(function(){return e(d)>e(0)})}function Ua(d){return new g(function(){return e(d)<e(0)})}function Sa(d){return new g(function(){return e(d)>=e(0)})}g.prototype.l=function(d){return d?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var cb=new g(function(){return e($(db))(p)}),
N=new g(function(){return new t}),J=new g(function(){return p}),u=new g(function(){return O(y)}),P=new g(function(){return O(R)}),fb=new g(function(){return new r(k(["user","Node",[]],document.documentElement))}),Aa=new g(function(){return s(m("attributeName"))}),Fa=new g(function(){return s(m("d"))}),Ga=new g(function(){return s(m("fill"))}),Ba=new g(function(){return s(m("repeatCount"))}),Ha=new g(function(){return s(m("values"))}),gb=new g(function(){return da(m("animate"))}),hb=new g(function(){return da(m("path"))}),
ib=new g(function(){return m("http://www.w3.org/2000/svg")}),Q=new g(function(){return Z(Xa)}),jb=new g(function(){return e(z(Fa))(Q)}),kb=new g(function(){return e(z(function(d){return e(e(u)(e(e(u)(J))(hb)))(d)}))(jb)}),lb=new g(function(){return e(z(function(d){return e(z(function(a){return e(z(function(a){return e(e(P)(e(e(u)(J))(gb)))(a)}))(a)}))(d)}))(Ya)}),nb=new g(function(){return e(z(Ha))(mb)}),mb=new g(function(){return bb(m(";"))}),ob=new g(function(){return ab(ib)}),Za=new g(function(){return e(z(s(m("dur"))))(eb)}),
s=function(d){return function(a){return new g(function(){return new B(d,a)})}},N=new g(function(){return new t}),J=new g(function(){return p}),u=new g(function(){return O(y)}),P=new g(function(){return O(R)}),aa=function(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof w)return Ea(c);c=a;return e(d)instanceof t?U(c):c=a})}},Aa=new g(function(){return s(m("attributeName"))}),Fa=new g(function(){return s(m("d"))}),Ga=new g(function(){return s(m("fill"))}),Ba=new g(function(){return s(m("repeatCount"))}),
Ha=new g(function(){return s(m("values"))}),qb=new g(function(){return Va(m("load"),pb)}),pb=new g(function(){var d=new g(function(){return Wa(e(e(u)(e(e(P)(e(e(u)(e(e(P)(J))(e(kb)(a))))(e(Ga)(m("cyan")))))(e(e(e(lb)(m("d")))(5.5))(9))))(e(nb)(m([e(Q)(a),e(Q)(c),e(Q)(a)]))),N)}),a=new g(function(){return m([fa(200,200),A(510,10,320,200),A(510,510,320,320),A(10,510,200,320),A(10,10,200,200)])}),c=new g(function(){return m([fa(10,10),A(125,75,190,10),A(125,125,190,190),A(75,125,10,190),A(75,75,10,10)])});
return Da(I(fb,e(ob)(d)),new r(p))}),E=K("a"),C=function(){},F=K("a"),D=function(){},G=K("a"),w=K("a"),B=function(d,a){this.a=d;this.b=a},H=function(d,a){this.a=d;this.b=a},t=function(){};this.j=qb;this.k=e};Ia.k(Ia.j);
