var h=void 0,n=null,ya=new function(){function Q(d,a){return new g(function(){return e(e(v)(d))(Q(R(d,a),a))})}function G(d,a){return new g(function(){var c=a,b=e(d);if(b instanceof r){var f=b.c,b=b.d;return e(e(v)(f))(G(b,c))}c=a;if(e(d)===n)return c;throw["unhandled case in conc",[d,a]];})}function S(d,a,c){return new g(function(){if(e(c)===n){var b=a;return b}b=e(c);if(b instanceof r){var f=b.c,g=b.d,b=a;return e(e(d)(f))(S(d,b,g))}throw["unhandled case in foldr",[d,a,c]];})}function za(d,a,c){return new g(function(){return new p(l(["user",
"Node",[]],k(["user","Node",[]],c).setAttributeNS(n,s(d),s(a))&&n||k(["user","Node",[]],c)))})}function Aa(d,a){return new g(function(){return new p(l(["user","Node",[]],document.createElementNS(s(d),s(a))))})}function Ba(d){return new g(function(){return new p(l(["user","Node",[]],k(["user","Node",[]],d).parentNode))})}function Ca(d,a,c){return new g(function(){return new p(l(["user","Node",[]],(k(["user","Node",[]],c)[s(d)]=s(a))&&n||k(["user","Node",[]],c)))})}function Da(d){return new g(function(){return new p(l(["user",
"Node",[]],document.createTextNode(s(d))))})}function T(d){return new g(function(){var a=e(d);if(a instanceof r)return H(T(a.d),m([a.c]));if(e(d)===n)return n;throw["unhandled case in reverse",[d]];})}function Ea(d){return new g(function(){return new E(d)})}function U(d,a,c){return new g(function(){var b=e(c);if(b instanceof r){var f=b.c,g=b.d,b=e(a);if(b instanceof r){var k=b.c,b=b.d;return e(e(v)(e(e(d)(k))(f)))(U(d,b,g))}}return n})}function Fa(d){return new g(function(){return e(e(t)(e(e(t)(B))(e(Ga)(d))))(e(Ha)(0))})}
function Ia(d,a){return new g(function(){return new C(d,a)})}function D(d){return new g(function(){var a=JSON.stringify(k(["automatic"],d));return m(a)})}function Ja(d,a){return new g(function(){return e(d)(a)})}function I(d,a){return new g(function(){if(e(a)===n)return n;var c=e(a);if(c instanceof r){var b=c.c,c=c.d;return e(e(v)(e(d)(b)))(I(d,c))}throw["unhandled case in map",[d,a]];})}function Ka(d){return new g(function(){return Q(0,La(d))})}function Ma(d){return new g(function(){var a=k(["user",
"Node",[]],d).getTotalLength();return new p(a)})}function Na(d,a){return new g(function(){return e(e(J)(e(e(t)(e(e(J)(e(e(t)(e(e(t)(B))(e(Oa)(D(a)))))(e(Pa)(H(D(a),H(m(","),D(a)))))))(e(e(e(Qa)(m("stroke-dashoffset")))(0.5))(d))))(e(Ra)(m("freeze")))))(Fa(a))})}function Sa(d){return new g(function(){return new p(l(["user","Node",[]],k(["user","Node",[]],d).lastChild))})}function H(d,a){return new g(function(){return G(d,a)})}function V(d,a,c){return new g(function(){if(e(c)===n){var b=a;return new p(b)}var f=
e(c);if(f instanceof r){var b=f.c,g=f.d;return u(e(e(d)(a))(b),function(b){return V(d,b,g)})}throw["unhandled case in foldM",[d,a,c]];})}function Ta(d,a){return new g(function(){return new p(l(["unknown"],window.addEventListener(s(d),k(["action",[["unknown"]]],a),e(!1))))})}function Ua(d){return new g(function(){return function(){return Ja(Va,I(function(a){return new g(function(){return e(e(t)(B))(Ia(d,D(a)))})},Ka(R(0,0.5))))}()})}function K(d,a){var c=e(a),b=d[2];if(c instanceof z){var f={instance:"Nullable"},
b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a);h!==b&&(f.slot1=b);return f}return c instanceof x?f={instance:"Null"}:c instanceof A?(f={instance:"Defined"},b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof y?f={instance:"Undefined"}:c instanceof W?(f={instance:"Just"},b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof X?f={instance:"Nothing"}:c instanceof Y?(f={instance:"Left"},
b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof Z?(f={instance:"Right"},b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof $?(f={instance:"Ratio"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),f):c instanceof aa?f={instance:"GT"}:c instanceof ba?f={instance:"LT"}:c instanceof ca?f={instance:"EQ"}:c instanceof z?(f={instance:"Nullable"},b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:
["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof x?f={instance:"Null"}:c instanceof A?(f={instance:"Defined"},b=k(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),h!==b&&(f.slot1=b),f):c instanceof y?f={instance:"Undefined"}:c instanceof L?(f={instance:"Content"},b=k(["user","DString",[]],c.a),h!==b&&(f.slot1=b),f):c instanceof E?(f={instance:"Element"},b=k(["user","DString",[]],c.a),h!==b&&(f.slot1=b),f):c instanceof C?(f={instance:"Attribute"},b=k(["user","DString",[]],c.a),h!==
b&&(f.slot1=b),b=k(["user","DString",[]],c.b),h!==b&&(f.slot2=b),f):c instanceof M?(f={instance:"Property"},b=k(["user","DString",[]],c.a),h!==b&&(f.slot1=b),b=k(["user","DString",[]],c.b),h!==b&&(f.slot2=b),f):c instanceof N?f={instance:"Complete"}:c instanceof da?(f={instance:"M"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),f):c instanceof ea?(f={instance:"L"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),f):c instanceof fa?(f={instance:"H"},b=e(c.a),h!==b&&(f.slot1=b),f):
c instanceof ga?(f={instance:"V"},b=e(c.a),h!==b&&(f.slot1=b),f):c instanceof ha?(f={instance:"A"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),b=e(c.e),h!==b&&(f.slot3=b),b=e(c.f),h!==b&&(f.slot4=b),b=e(c.g),h!==b&&(f.slot5=b),b=e(c.h),h!==b&&(f.slot6=b),c=e(c.m),h!==c&&(f.slot7=c),f):c instanceof ia?(f={instance:"C"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),b=e(c.e),h!==b&&(f.slot3=b),b=e(c.f),h!==b&&(f.slot4=b),b=e(c.g),h!==b&&(f.slot5=b),b=e(c.h),h!==b&&(f.slot6=b),f):
c instanceof ja?(f={instance:"S"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),b=e(c.e),h!==b&&(f.slot3=b),b=e(c.f),h!==b&&(f.slot4=b),f):c instanceof ka?(f={instance:"Q"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),b=e(c.e),h!==b&&(f.slot3=b),b=e(c.f),h!==b&&(f.slot4=b),f):c instanceof la?(f={instance:"T"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),f):c instanceof ma?f={instance:"Z"}:c instanceof na?(f={instance:"Translate"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),
h!==b&&(f.slot2=b),f):c instanceof oa?(f={instance:"Rotate"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),b=e(c.e),h!==b&&(f.slot3=b),f):c instanceof pa?(f={instance:"Scale"},b=e(c.a),h!==b&&(f.slot1=b),f):c instanceof qa?(f={instance:"Scale2d"},b=e(c.a),h!==b&&(f.slot1=b),b=e(c.b),h!==b&&(f.slot2=b),f):a}function qa(d,a){this.a=d;this.b=a}function pa(d){this.a=d}function oa(d,a,c){this.a=d;this.b=a;this.e=c}function na(d,a){this.a=d;this.b=a}function ma(){}function la(d,a){this.a=d;this.b=
a}function ka(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function ja(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function ia(d,a,c,b,e,g){this.a=d;this.b=a;this.e=c;this.f=b;this.g=e;this.h=g}function ha(d,a,c,b,e,g,k){this.a=d;this.b=a;this.e=c;this.f=b;this.g=e;this.h=g;this.m=k}function ga(d){this.a=d}function fa(d){this.a=d}function ea(d,a){this.a=d;this.b=a}function da(d,a){this.a=d;this.b=a}function N(){}function M(d,a){this.a=d;this.b=a}function C(d,a){this.a=d;this.b=a}function E(d){this.a=
d}function L(d){this.a=d}function ca(){}function ba(){}function aa(){}function $(d,a){this.a=d;this.b=a}function Z(d){this.a=d}function Y(d){this.a=d}function X(){}function W(d){this.a=d}function y(){}function A(d){this.a=d}function x(){}function z(d){this.a=d}function Wa(){return function(d){return function(a){return new g(function(){return u(Ma(a),function(c){return O(e(e(ra)(Na(d,c)))(a),Sa(a))})})}}}function Xa(d){return function(a){return function(c){return new g(function(){return function(){return e(e(t)(e(e(t)(e(e(t)(B))(e(Ya)(d))))(e(Za)(a))))(e($a)(e(function(b){return new g(function(){return e(ab(b))?
D(b):m("indefinite")})})(c)))}()})}}}function bb(d){return function(a){return function(c){return new g(function(){return function(){return V(function(b){return function(a){return new g(function(){if(e(a)instanceof C){var c=e(a).a,g=e(a).b,k=b;return za(c,g,k)}if(e(a)instanceof E)return c=e(a).a,k=b,u(Aa(d,c),sa(k));if(e(a)instanceof N)return k=b,Ba(k);if(e(a)instanceof M)return c=e(a).a,g=e(a).b,k=b,Ca(c,g,k);if(e(a)instanceof L)return g=e(a).a,k=b,O(u(Da(g),sa(k)),new p(k));throw["unhandled case in go",
[b,a]];})}},c,T(a))}()})}}}function cb(d){return function(a){return new g(function(){return new p(l(["list",[["user","Node",[]]]],k(["user","Node",[]],a).getElementsByTagName(s(d))))})}}function sa(d){return function(a){return new g(function(){return new p(l(["user","Node",[]],k(["user","Node",[]],d).appendChild(k(["user","Node",[]],a))&&n||k(["user","Node",[]],a)))})}}function w(d){return function(a){return new g(function(){return new C(d,a)})}}function ta(d){return function(a){return function(c){return new g(function(){var b=
e(c);if(b instanceof r){var f=b.c,g=b.d,b=e(a);if(b instanceof r){var k=b.c,b=b.d;return e(e(v)(e(e(d)(k))(f)))(U(d,b,g))}}return n})}}}function db(d){return function(a){return new g(function(){return G(d,a)})}}function ua(d){return function(a){return new g(function(){if(e(a)===n)return n;var c=e(a);if(c instanceof r){var b=c.c,c=c.d;return e(e(v)(e(d)(b)))(I(d,c))}throw["unhandled case in map",[d,a]];})}}function va(d){return function(a){return function(c){return new g(function(){return e(e(d)(c))(a)})}}}
function q(d){return function(a){return function(c){return new g(function(){return e(d)(e(a)(c))})}}}function P(d){return new g(function(){var a=JSON.stringify(k(["automatic"],d));return m(a)})}function F(d){return new g(function(){return function(){return S(function(a){return function(c){return new g(function(){return u(a,function(b){return u(c,function(a){a=e(e(v)(b))(a);return new p(a)})})})}},new p(n),d)}()})}function e(d,a){for(;d instanceof g;)d=d.l(a);return d}function g(d){this.i=!1;this.value=
d}function p(d){this.value=d}function O(d,a){return u(d,function(){return a})}function u(d,a){return new g(function(){var c=e(d,!0);return e(a)(c.value)})}function k(d,a){var c=d[0],b=d[1];if("action"==c)c=function(){return k(b[0],e(a,!0).value)};else if("function"==c)c=function(){var c=a,d=b[b.length-1],f=b.length;if(1<f){for(var c=e(c,!0),g=0;g<f-1&&c instanceof Function;g++)c=e(c(l(b[g],arguments[g])),!0);f=d[1];return"action"==d[0]?k(f[0],c.value):k(d,c)}throw Error("Nullary function?");};else if("string"==
c)c=s(a);else if("list"==c){c=[];for(a=e(a);a instanceof r;)c.push(k(b[0],a.c)),a=e(a.d)}else if("tuple"==c){c=[];a=e(a);for(var f=0;a instanceof r;)c.push(k(b[f++],a.c)),a=e(a.d)}else if("defined"==c)a=e(a),c=a instanceof y?h:K(b[0],a.slot1);else if("nullable"==c)a=e(a),c=a instanceof x?n:K(b[0],a.slot1);else if("double"==c||"int"==c||"bool"==c)c=e(a);else{if("ptr"==c||"unknown"==c)return a;if("automatic"==c||"user"==c)a instanceof g&&(a=e(a)),c=K(d,a);else throw Error("Unhandled Fay->JS translation type: "+
c);}return c}function s(d){var a="";for(d=e(d);d instanceof r;)a+=d.c,d=e(d.d);return a}function l(d,a){var c=d[0],b=d[1];if("action"==c)b=new p(l(b[0],a));else if("string"==c)b=m(a);else if("list"==c){for(var e=[],c=0,g=a.length;c<g;c++)e.push(l(b[0],a[c]));b=m(e)}else if("tuple"==c){e=[];c=0;for(g=a.length;c<g;c++)e.push(l(b[c],a[c]));b=m(e)}else if("defined"==c)b=a===h?new y:new A(l(b[0],a));else if("nullable"==c)b=a===n?new x:new z(l(b[0],a));else if("int"==c){if(b=Math.round(a),b!==a)throw"Argument "+
a+" is not an integer!";}else{if("double"==c||"bool"==c||"ptr"==c||"unknown"==c)return a;if("automatic"==c||"user"==c)a&&a.instance?(b=d[2],b="Nullable"===a.instance?new z(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new x:"Defined"===a.instance?new A(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new y:"Just"===a.instance?new W(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===
a.instance?new X:"Left"===a.instance?new Y(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new Z(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new $(a.slot1,a.slot2):"GT"===a.instance?new aa:"LT"===a.instance?new ba:"EQ"===a.instance?new ca:"Nullable"===a.instance?new z(l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new x:"Defined"===a.instance?new A(l(b&&b[0]?b[0]:"automatic"===
d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new y:"Content"===a.instance?new L(l(["user","DString",[]],a.slot1)):"Element"===a.instance?new E(l(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new C(l(["user","DString",[]],a.slot1),l(["user","DString",[]],a.slot2)):"Property"===a.instance?new M(l(["user","DString",[]],a.slot1),l(["user","DString",[]],a.slot2)):"Complete"===a.instance?new N:"M"===a.instance?new da(a.slot1,a.slot2):"L"===a.instance?new ea(a.slot1,a.slot2):
"H"===a.instance?new fa(a.slot1):"V"===a.instance?new ga(a.slot1):"A"===a.instance?new ha(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6,a.slot7):"C"===a.instance?new ia(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6):"S"===a.instance?new ja(a.slot1,a.slot2,a.slot3,a.slot4):"Q"===a.instance?new ka(a.slot1,a.slot2,a.slot3,a.slot4):"T"===a.instance?new la(a.slot1,a.slot2):"Z"===a.instance?new ma:"Translate"===a.instance?new na(a.slot1,a.slot2):"Rotate"===a.instance?new oa(a.slot1,a.slot2,a.slot3):
"Scale"===a.instance?new pa(a.slot1):"Scale2d"===a.instance?new qa(a.slot1,a.slot2):a):b=a;else throw Error("Unhandled JS->Fay translation type: "+c);}return b}function r(d,a){this.c=d;this.d=a}function m(d){for(var a=n,c=d.length-1;0<=c;c--)a=new r(d[c],a);return a}function v(d){return function(a){return new r(d,a)}}function R(d,a){return new g(function(){return e(d)+e(a)})}function La(d){return new g(function(){return e(d)-e(0)})}function ab(d){return new g(function(){return e(d)>e(0)})}g.prototype.l=
function(d){return d?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var wa=new g(function(){return e(q(function(d){return e(q(F))(d)}))(ua)}),xa=new g(function(){return e(q(function(d){return e(q(function(a){return e(q(F))(a)}))(d)}))(ta)}),B=new g(function(){return n}),t=new g(function(){return va(v)}),J=new g(function(){return va(db)}),eb=new g(function(){return new p(l(["user","Node",[]],document.documentElement))}),Ya=new g(function(){return w(m("attributeName"))}),
Ra=new g(function(){return w(m("fill"))}),$a=new g(function(){return w(m("repeatCount"))}),Pa=new g(function(){return w(m("stroke-dasharray"))}),Oa=new g(function(){return w(m("stroke-dashoffset"))}),fb=new g(function(){return Ea(m("animate"))}),gb=new g(function(){return m("http://www.w3.org/2000/svg")}),Qa=new g(function(){return e(q(function(d){return e(q(function(a){return e(q(function(a){return e(e(J)(e(e(t)(B))(fb)))(a)}))(a)}))(d)}))(Xa)}),ra=new g(function(){return bb(gb)}),Va=new g(function(){return e(xa)(ra)}),
Za=new g(function(){return e(q(w(m("dur"))))(P)}),Ga=new g(function(){return e(q(w(m("from"))))(P)}),Ha=new g(function(){return e(q(w(m("to"))))(P)}),wa=new g(function(){return e(q(function(d){return e(q(F))(d)}))(ua)}),xa=new g(function(){return e(q(function(d){return e(q(function(a){return e(q(F))(a)}))(d)}))(ta)}),ib=new g(function(){return Ta(m("load"),hb)}),hb=new g(function(){return O(u(u(u(eb,cb(m("path"))),e(wa)(e(Wa())(1))),Ua(m("begin"))),new p(n))}),z=function(d){this.a=d},x=function(){},
A=function(d){this.a=d},y=function(){};this.j=ib;this.k=e};ya.k(ya.j);
