function l(D){throw D;}var n=void 0,q=null;function E(D){return function(L){this[D]=L}}
var ua=new function(){function D(c){return new f(function(){if(e(c)===q)return new r(q);var a=e(c);if(a instanceof p)return S(a.c,D(a.b));l(["unhandled case in sequence_",[c]])})}function L(c,a){return new f(function(){var b=a,d=e(c);if(d instanceof p){var g=d.c,d=d.b;return e(e(y)(g))(L(d,b))}b=a;if(e(c)===q)return b;l(["unhandled case in conc",[c,a]])})}function va(c,a,b){return new f(function(){for(;;){if(e(b)===q){var d=a;return d}d=e(b);if(d instanceof p){var g=d.c,f=d.b,d=a,h=c;c=h;a=e(e(h)(d))(g);
b=f}else l(["unhandled case in foldl",[c,a,b]])}})}function wa(c,a,b){return new f(function(){return new r(k(["user","Node",[]],h(["user","Node",[]],b).setAttributeNS(q,v(c),v(a))&&q||h(["user","Node",[]],b)))})}function xa(c,a){return new f(function(){return new r(k(["user","Node",[]],document.createElementNS(v(c),v(a))))})}function ya(c){return new f(function(){return new r(k(["user","Node",[]],h(["user","Node",[]],c).parentNode))})}function za(c,a,b){return new f(function(){return new r(k(["user",
"Node",[]],(h(["user","Node",[]],b)[v(c)]=v(a))&&q||h(["user","Node",[]],b)))})}function Aa(c){return new f(function(){return new r(k(["user","Node",[]],document.createTextNode(v(c))))})}function Z(c,a,b){return new f(function(){if(e(b)===q){var d=a;return new r(d)}var g=e(b);if(g instanceof p){var d=g.c,f=g.b;return F(e(e(c)(a))(d),function(a){return Z(c,a,f)})}l(["unhandled case in foldM",[c,a,b]])})}function G(c){return new f(function(){return new w(c)})}function $(c,a,b){return new f(function(){if(e(b)===
q){var d=a;return d}d=e(b);if(d instanceof p){var g=d.c,f=d.b,d=a;return e(e(c)(g))($(c,d,f))}l(["unhandled case in foldr",[c,a,b]])})}function T(c){return new f(function(){l(v(c))})}function U(c){return new f(function(){var a=JSON.stringify(h(["automatic"],c));return m(a)})}function aa(c){return new f(function(){var a=e(c);if(a instanceof p)return A(aa(a.b),m([a.c]));if(e(c)===q)return q;l(["unhandled case in reverse",[c]])})}function ba(c,a,b){return new f(function(){var d=e(b);if(d instanceof p){var g=
d.c,f=d.b,d=e(a);if(d instanceof p){var h=d.c,d=d.b;return e(e(y)(e(e(c)(h))(g)))(ba(c,d,f))}}return q})}function ca(c,a){return new f(function(){if(0===e(c)||e(a)===q)return q;var b=e(a);if(b instanceof p){var d=b.c,b=b.b;return e(da(c))?T(m("take: negative length")):e(e(y)(d))(ca(ea(c),b))}l(["unhandled case in take",[c,a]])})}function fa(c,a){return new f(function(){var b=a;if(0===e(c))return b;if(e(a)===q)return q;b=e(a);if(b instanceof p)return b=b.b,e(da(c))?T(m("drop: negative length")):fa(ea(c),
b);l(["unhandled case in drop",[c,a]])})}function V(c){return new f(function(){return e(Ba(e(O(P))(c)))(q)})}function A(c,a){return new f(function(){return L(c,a)})}function ga(c,a){return new f(function(){var b=e(a);if(b instanceof p)return va(c,b.c,b.b);if(e(a)===q)return T(m("foldl1: empty list"));l(["unhandled case in foldl1",[c,a]])})}function Q(c,a){return new f(function(){if(e(a)===q)return q;var b=e(a);if(b instanceof p){var d=b.c,b=b.b;return e(e(y)(e(c)(d)))(Q(c,b))}l(["unhandled case in map",
[c,a]])})}function Ca(c,a){return new f(function(){return new r(k(["unknown"],window.addEventListener(v(c),h(["action",[["unknown"]]],a),e(!1))))})}function W(c,a){var b=e(a),d=c[2];if(b instanceof H){var g={instance:"Nullable"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a);n!==d&&(g.slot1=d);return g}return b instanceof B?g={instance:"Null"}:b instanceof I?(g={instance:"Defined"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof
C?g={instance:"Undefined"}:b instanceof ha?(g={instance:"Just"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof ia?g={instance:"Nothing"}:b instanceof ja?(g={instance:"Left"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof ka?(g={instance:"Right"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof la?(g={instance:"Ratio"},d=e(b.a),n!==d&&(g.slot1=
d),b=e(b.d),n!==b&&(g.slot2=b),g):b instanceof ma?g={instance:"GT"}:b instanceof na?g={instance:"LT"}:b instanceof oa?g={instance:"EQ"}:b instanceof H?(g={instance:"Nullable"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof B?g={instance:"Null"}:b instanceof I?(g={instance:"Defined"},d=h(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],b.a),n!==d&&(g.slot1=d),g):b instanceof C?g={instance:"Undefined"}:b instanceof z?(g={instance:"Content"},
d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Element"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof s?(g={instance:"Attribute"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof t?(g={instance:"Property"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof u?g={instance:"Complete"}:b instanceof z?(g={instance:"Content"},
d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Element"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof s?(g={instance:"Attribute"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof t?(g={instance:"Property"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof u?g={instance:"Complete"}:b instanceof z?(g={instance:"Content"},
d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof w?(g={instance:"Element"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),g):b instanceof s?(g={instance:"Attribute"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof t?(g={instance:"Property"},d=h(["user","DString",[]],b.a),n!==d&&(g.slot1=d),b=h(["user","DString",[]],b.d),n!==b&&(g.slot2=b),g):b instanceof u?g={instance:"Complete"}:a}function u(){}function t(c,a){this.a=
c;this.d=a}function s(c,a){this.a=c;this.d=a}function w(c){this.a=c}function z(c){this.a=c}function oa(){}function na(){}function ma(){}function la(c,a){this.a=c;this.d=a}function ka(c){this.a=c}function ja(c){this.a=c}function ia(){}function ha(c){this.a=c}function C(){}function I(c){this.a=c}function B(){}function H(c){this.a=c}function Da(c){return function(a){return function(b){return new f(function(){return function(){return Z(function(a){return function(b){return new f(function(){if(e(b)instanceof
s){var f=e(b).a,h=e(b).d,k=a;return wa(f,h,k)}if(e(b)instanceof w)return f=e(b).a,k=a,F(xa(c,f),pa(k));if(e(b)instanceof u)return k=a,ya(k);if(e(b)instanceof t)return f=e(b).a,h=e(b).d,k=a,za(f,h,k);if(e(b)instanceof z)return h=e(b).a,k=a,S(F(Aa(h),pa(k)),new r(k));l(["unhandled case in go",[a,b]])})}},b,aa(a))}()})}}}function Ea(c){return new f(function(){for(var a=e(c),b=0;a!==q&&4>b;b++)a=e(a.b);if(3==b){var a=X(0,e(c)),b=X(1,e(c)),d=X(2,e(c));return A(m("rgb("),A(U(a),A(m(","),A(U(b),A(m(","),
A(U(d),m(")")))))))}l(["unhandled case in rgb",[c]])})}function Fa(c){return function(a){return new f(function(){return new r(k(["list",[["user","Node",[]]]],h(["user","Node",[]],a).getElementsByTagName(v(c))))})}}function pa(c){return function(a){return new f(function(){return new r(k(["user","Node",[]],h(["user","Node",[]],c).appendChild(h(["user","Node",[]],a))&&q||h(["user","Node",[]],a)))})}}function Y(c){return function(a){return new f(function(){return new t(c,a)})}}function R(c){return function(a){return new f(function(){return new s(c,
a)})}}function Ga(c){return function(a){return function(b){return new f(function(){var d=e(b);if(d instanceof p){var g=d.c,f=d.b,d=e(a);if(d instanceof p){var h=d.c,d=d.b;return e(e(y)(e(e(c)(h))(g)))(ba(c,d,f))}}return q})}}}function P(c){return function(a){return new f(function(){return L(c,a)})}}function Ba(c){return function(a){return function(b){return new f(function(){if(e(b)===q){var d=a;return d}d=e(b);if(d instanceof p){var g=d.c,f=d.b,d=a;return e(e(c)(g))($(c,d,f))}l(["unhandled case in foldr",
[c,a,b]])})}}}function J(c){return function(a){return function(b){return new f(function(){return e(e(c)(b))(a)})}}}function O(c){return function(a){return function(b){return new f(function(){return e(c)(e(a)(b))})}}}function Ha(c){return new f(function(){if(e(c)===q)return new r(q);var a=e(c);if(a instanceof p)return S(a.c,D(a.b));l(["unhandled case in sequence_",[c]])})}function e(c,a){for(;c instanceof f;)c=c.h(a);return c}function f(c){this.e=!1;this.value=c}function r(c){this.value=c}function S(c,
a){return F(c,function(){return a})}function F(c,a){return new f(function(){var b=e(c,!0);return e(a)(b.value)})}function h(c,a){var b=c[0],d=c[1],g;if("action"==b)g=function(){return h(d[0],e(a,!0).value)};else if("function"==b)g=function(){var b=a,c=d[d.length-1],g=d.length;if(1<g){for(var b=e(b,!0),f=0;f<g-1&&b instanceof Function;f++)b=e(b(k(d[f],arguments[f])),!0);g=c[1];return"action"==c[0]?h(g[0],b.value):h(c,b)}l(Error("Nullary function?"))};else if("string"==b)g=v(a);else if("list"==b){b=
[];for(a=e(a);a instanceof p;)b.push(h(d[0],a.c)),a=e(a.b);g=b}else if("tuple"==b){b=[];a=e(a);for(g=0;a instanceof p;)b.push(h(d[g++],a.c)),a=e(a.b);g=b}else if("defined"==b)a=e(a),g=a instanceof C?n:W(d[0],a.slot1);else if("nullable"==b)a=e(a),g=a instanceof B?q:W(d[0],a.slot1);else if("double"==b||"int"==b||"bool"==b)g=e(a);else{if("ptr"==b||"unknown"==b)return a;"automatic"==b||"user"==b?(a instanceof f&&(a=e(a)),g=W(c,a)):l(Error("Unhandled Fay->JS translation type: "+b))}return g}function v(c){var a=
"";for(c=e(c);c instanceof p;)a+=c.c,c=e(c.b);return a}function k(c,a){var b=c[0],d=c[1],e;if("action"==b)e=new r(k(d[0],a));else if("string"==b)e=m(a);else if("list"==b){var f=[],b=0;for(e=a.length;b<e;b++)f.push(k(d[0],a[b]));e=m(f)}else if("tuple"==b){f=[];b=0;for(e=a.length;b<e;b++)f.push(k(d[b],a[b]));e=m(f)}else if("defined"==b)e=a===n?new C:new I(k(d[0],a));else if("nullable"==b)e=a===q?new B:new H(k(d[0],a));else if("int"==b)e=Math.round(a),e!==a&&l("Argument "+a+" is not an integer!");else{if("double"==
b||"bool"==b||"ptr"==b||"unknown"==b)return a;"automatic"==b||"user"==b?(a&&a.instance?(d=c[2],d="Nullable"===a.instance?new H(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new B:"Defined"===a.instance?new I(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new C:"Just"===a.instance?new ha(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ia:"Left"===a.instance?new ja(k(d&&
d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new ka(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new la(a.slot1,a.slot2):"GT"===a.instance?new ma:"LT"===a.instance?new na:"EQ"===a.instance?new oa:"Nullable"===a.instance?new H(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new B:"Defined"===a.instance?new I(k(d&&d[0]?d[0]:"automatic"===c[0]?["automatic"]:["unknown"],a.slot1)):
"Undefined"===a.instance?new C:"Content"===a.instance?new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new w(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new s(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new t(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:"Content"===a.instance?new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new w(k(["user","DString",[]],a.slot1)):
"Attribute"===a.instance?new s(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new t(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:"Content"===a.instance?new z(k(["user","DString",[]],a.slot1)):"Element"===a.instance?new w(k(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new s(k(["user","DString",[]],a.slot1),k(["user","DString",[]],a.slot2)):"Property"===a.instance?new t(k(["user","DString",[]],
a.slot1),k(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:a):d=a,e=d):l(Error("Unhandled JS->Fay translation type: "+b))}return e}function p(c,a){this.c=c;this.b=a}function m(c){for(var a=q,b=c.length-1;0<=b;b--)a=new p(c[b],a);return a}function y(c){return function(a){return new p(c,a)}}function X(c,a){for(var b=0;b<c;b++)a=e(a.b);return a.c}function ea(c){return new f(function(){return e(c)-e(1)})}function da(c){return new f(function(){return e(c)<e(0)})}f.prototype.h=function(c){return c?
this.value():this.e?this.value:(this.value=this.value(),this.e=!0,this.value)};var Ia=new f(function(){return e(O(function(c){return e(O(function(a){return e(O(Ha))(a)}))(c)}))(Ga)}),M=new f(function(){return new u}),N=new f(function(){return q}),x=new f(function(){return J(y)}),K=new f(function(){return J(P)}),Ja=new f(function(){return new r(k(["user","Node",[]],document.documentElement))}),qa=new f(function(){return R(m("style"))}),ra=new f(function(){return G(m("table"))}),sa=new f(function(){return G(m("td"))}),
ta=new f(function(){return G(m("tr"))}),Ka=new f(function(){return m("http://www.w3.org/1999/xhtml")}),La=new f(function(){return Da(Ka)}),Ma=new f(function(){return Y(m("innerHTML"))}),R=function(c){return function(a){return new f(function(){return new s(c,a)})}},Y=function(c){return function(a){return new f(function(){return new t(c,a)})}},M=new f(function(){return new u}),N=new f(function(){return q}),x=new f(function(){return J(y)}),K=new f(function(){return J(P)}),ra=new f(function(){return G(m("table"))}),
sa=new f(function(){return G(m("td"))}),ta=new f(function(){return G(m("tr"))}),R=function(c){return function(a){return new f(function(){return new s(c,a)})}},Y=function(c){return function(a){return new f(function(){return new t(c,a)})}},M=new f(function(){return new u}),N=new f(function(){return q}),x=new f(function(){return J(y)}),K=new f(function(){return J(P)}),qa=new f(function(){return R(m("style"))}),Na=new f(function(){function c(a){return new f(function(){return e(a)===q?q:e(e(y)(Q(Ea,ca(24,
a))))(e(c)(fa(24,a)))})}var a=new f(function(){return m([0,51,102,153,204,255])});return e(c)(function(){return e(V(function(b){return new f(function(){return function(){return e(V(function(c){return new f(function(){return function(){return e(V(function(a){return new f(function(){return m([m([b,c,a])])})}))(a)}()})}))(a)}()})}))(a)}())}),Oa=new f(function(){function c(a){return new f(function(){return e(qa)(A(m("height:20px;width:20px;background-color:"),a))})}function a(a){return new f(function(){return e(e(x)(e(e(x)(e(e(x)(e(e(x)(N))(sa)))(e(c)(a))))(e(Ma)(m("&#955;")))))(M)})}
return e(e(x)(e(e(K)(e(e(x)(N))(ra)))(ga(K,Q(function(b){return new f(function(){return e(e(x)(e(e(K)(e(e(x)(N))(ta)))(ga(K,Q(a,b)))))(M)})},Na)))))(M)}),Pa=new f(function(){return F(F(Ja,Fa(m("body"))),e(e(Ia)(La))(m([Oa])))}),Qa=new f(function(){return Ca(m("load"),Pa)}),H=E("a"),B=function(){},I=E("a"),C=function(){},z=E("a"),w=E("a"),s=function(c,a){this.a=c;this.d=a},t=function(c,a){this.a=c;this.d=a},u=function(){},z=E("a"),w=E("a"),s=function(c,a){this.a=c;this.d=a},t=function(c,a){this.a=
c;this.d=a},u=function(){};this.f=Qa;this.g=e};ua.g(ua.f);
