function h(A){throw A;}var n=void 0,p=null;function Q(A){return function(R){this[A]=R}}
var Ja=new function(){function A(d,a){return new g(function(){var c=a,b=e(d);if(b instanceof s){var f=b.c,b=b.d;return e(e(x)(f))(A(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}function R(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(x)(d))(e(e(x)(b))(R(d,c)))}h(["unhandled case in prependToAll",[d,a]])})}function Ka(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(x)(b))(R(d,
c))}h(["unhandled case in intersperse",[d,a]])})}function La(d,a,c){return new g(function(){return new t(m(["user","Node",[]],l(["user","Node",[]],c).setAttributeNS(p,v(d),v(a))&&p||l(["user","Node",[]],c)))})}function Ma(d,a){return new g(function(){return new t(m(["user","Node",[]],document.createElementNS(v(d),v(a))))})}function Na(d){return new g(function(){return new t(m(["user","Node",[]],l(["user","Node",[]],d).parentNode))})}function Oa(d,a,c){return new g(function(){return new t(m(["user",
"Node",[]],(l(["user","Node",[]],c)[v(d)]=v(a))&&p||l(["user","Node",[]],c)))})}function Pa(d){return new g(function(){return new t(m(["user","Node",[]],document.createTextNode(v(d))))})}function ba(d,a,c){return new g(function(){if(e(c)===p){var b=a;return new t(b)}var f=e(c);if(f instanceof s){var b=f.c,g=f.d;return J(e(e(d)(a))(b),function(a){return ba(d,a,g)})}h(["unhandled case in foldM",[d,a,c]])})}function Qa(){return new g(function(){return e(e(q)(e(e(q)(e(e(q)(K))(Ra)))(e(Sa)(10))))(e(Ta)(15))})}
function Ua(d,a,c){return new g(function(){return function(){return e(e(q)(e(e(q)(e(e(q)(K))(e(ca)(d))))(e(Va)(a))))(e(da)(e(function(a){return new g(function(){return e(Wa(a))?y(a):k("indefinite")})})(c)))}()})}function Xa(d){return new g(function(){if(e(d)===p)return V(k("head: empty list"));var a=e(d);if(a instanceof s)return a.c;h(["unhandled case in head",[d]])})}function ea(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(x)(e(d)(b)))(ea(d,
c))}h(["unhandled case in map",[d,a]])})}function Ya(d){return new g(function(){return function(){var a=new g(function(){return W(fa,0,d)});return e(Za(a))?w(ga(a,L),d):V(k("Markup has more close elements than open"))}()})}function ha(d){return new g(function(){return new z(d)})}function W(d,a,c){return new g(function(){if(e(c)===p){var b=a;return b}b=e(c);if(b instanceof s){var f=b.c,g=b.d,b=a;return e(e(d)(f))(W(d,b,g))}h(["unhandled case in foldr",[d,a,c]])})}function V(d){return new g(function(){h(v(d))})}
function y(d){return new g(function(){var a=JSON.stringify(l(["automatic"],d));return k(a)})}function ia(d){return new g(function(){var a=e(d);if(a instanceof s)return w(ia(a.d),k([a.c]));if(e(d)===p)return p;h(["unhandled case in reverse",[d]])})}function ga(d,a){return new g(function(){return 0===e(d)?p:e($a(d))?V(k("replicate: negative length")):e(e(x)(a))(ga(X(d),a))})}function w(d,a){return new g(function(){return A(d,a)})}function ab(d,a){return new g(function(){return e(d)(a)})}function bb(d,
a){return new g(function(){return new t(m(["unknown"],window.addEventListener(v(d),l(["action",[["unknown"]]],a),e(!1))))})}function cb(d,a){return new g(function(){if(e(a)instanceof u){var c=d;return Ya(c)}c=d;return e(e(q)(e(e(q)(c))(L)))(a)})}function db(d,a){return new g(function(){return e(e(M)(e(e(q)(d))(L)))(a)})}function eb(){return new g(function(){return e(e(q)(e(e(q)(Qa()))(e(fb)(10))))(e(gb)(10))})}function Y(d,a){return new g(function(){return new N(d,a)})}function ja(d,a,c){return new g(function(){return e(e(q)(e(e(q)(e(e(M)(e(e(q)(K))(hb)))(Ua(k("transform"),
d,a))))(e(e(ka)(k("type")))(ab(ib,Xa(c))))))(e(jb)(ea(kb,c)))})}function Z(d){return new g(function(){return new O(d,100,100)})}function $(d,a){var c=e(a),b=d[2];if(c instanceof E){var f={instance:"Nullable"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a);n!==b&&(f.slot1=b);return f}return c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:
c instanceof la?(f={instance:"Just"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof ma?f={instance:"Nothing"}:c instanceof na?(f={instance:"Left"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof oa?(f={instance:"Right"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof pa?(f={instance:"Ratio"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=
b),f):c instanceof qa?f={instance:"GT"}:c instanceof ra?f={instance:"LT"}:c instanceof sa?f={instance:"EQ"}:c instanceof E?(f={instance:"Nullable"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:c instanceof G?(f={instance:"Content"},b=l(["user","DString",
[]],c.a),n!==b&&(f.slot1=b),f):c instanceof z?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof H?(f={instance:"Property"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof u?f={instance:"Complete"}:c instanceof ta?(f={instance:"M"},b=e(c.a),n!==b&&(f.slot1=
b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof ua?(f={instance:"L"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof va?(f={instance:"H"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof wa?(f={instance:"V"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof xa?(f={instance:"A"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),c=e(c.m),n!==c&&(f.slot7=c),f):c instanceof
ya?(f={instance:"C"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),f):c instanceof za?(f={instance:"S"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof Aa?(f={instance:"Q"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof
Ba?(f={instance:"T"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof Ca?f={instance:"Z"}:c instanceof S?(f={instance:"Translate"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof O?(f={instance:"Rotate"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),f):c instanceof T?(f={instance:"Scale"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof N?(f={instance:"Scale2d"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),
f):c instanceof G?(f={instance:"Content"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof z?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof H?(f={instance:"Property"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof u?f={instance:"Complete"}:
a}function N(d,a){this.a=d;this.b=a}function T(d){this.a=d}function O(d,a,c){this.a=d;this.b=a;this.e=c}function S(d,a){this.a=d;this.b=a}function Ca(){}function Ba(d,a){this.a=d;this.b=a}function Aa(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function za(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function ya(d,a,c,b,e,g){this.a=d;this.b=a;this.e=c;this.f=b;this.g=e;this.h=g}function xa(d,a,c,b,e,g,k){this.a=d;this.b=a;this.e=c;this.f=b;this.g=e;this.h=g;this.m=k}function wa(d){this.a=d}function va(d){this.a=
d}function ua(d,a){this.a=d;this.b=a}function ta(d,a){this.a=d;this.b=a}function u(){}function H(d,a){this.a=d;this.b=a}function B(d,a){this.a=d;this.b=a}function z(d){this.a=d}function G(d){this.a=d}function sa(){}function ra(){}function qa(){}function pa(d,a){this.a=d;this.b=a}function oa(d){this.a=d}function na(d){this.a=d}function ma(){}function la(d){this.a=d}function D(){}function F(d){this.a=d}function C(){}function E(d){this.a=d}function kb(d){return new g(function(){if(e(d)instanceof S){var a=
e(d).a,c=e(d).b;return w(y(a),w(k(","),y(c)))}if(e(d)instanceof O){var a=e(d).a,c=e(d).b,b=e(d).e;return w(y(a),w(k(","),w(y(c),w(k(","),y(b)))))}if(e(d)instanceof T)return a=e(d).a,y(a);if(e(d)instanceof N)return a=e(d).a,c=e(d).b,w(y(a),w(k(","),y(c)));h(["unhandled case in transformVals",[d]])})}function ib(d){return new g(function(){if(e(d)instanceof S)return k("translate");if(e(d)instanceof O)return k("rotate");if(e(d)instanceof T||e(d)instanceof N)return k("scale");h(["unhandled case in transformType",
[d]])})}function lb(d){return function(a){return function(c){return new g(function(){return function(){return ba(function(a){return function(c){return new g(function(){if(e(c)instanceof B){var g=e(c).a,k=e(c).b,l=a;return La(g,k,l)}if(e(c)instanceof z)return g=e(c).a,l=a,J(Ma(d,g),Da(l));if(e(c)instanceof u)return l=a,Na(l);if(e(c)instanceof H)return g=e(c).a,k=e(c).b,l=a,Oa(g,k,l);if(e(c)instanceof G)return k=e(c).a,l=a,Ea(J(Pa(k),Da(l)),new t(l));h(["unhandled case in go",[a,c]])})}},c,ia(a))}()})}}}
function Da(d){return function(a){return new g(function(){return new t(m(["user","Node",[]],l(["user","Node",[]],d).appendChild(l(["user","Node",[]],a))&&p||l(["user","Node",[]],a)))})}}function fa(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof z)return Fa(c);c=a;return e(d)instanceof u?X(c):c=a})}}function r(d){return function(a){return new g(function(){return new B(d,a)})}}function mb(d){return function(a){return new g(function(){return e(nb)(Ka(d,a))})}}function Ga(d){return function(a){return new g(function(){return A(d,
a)})}}function ob(d){return function(a){return function(c){return new g(function(){if(e(c)===p){var b=a;return b}b=e(c);if(b instanceof s){var f=b.c,g=b.d,b=a;return e(e(d)(f))(W(d,b,g))}h(["unhandled case in foldr",[d,a,c]])})}}}function pb(d){return function(a){return new g(function(){var c=a,b=e(d);if(b instanceof s){var f=b.c,b=b.d;return e(e(x)(f))(A(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}}function U(d){return function(a){return function(c){return new g(function(){return e(e(d)(c))(a)})}}}
function I(d){return function(a){return function(c){return new g(function(){return e(d)(e(a)(c))})}}}function P(d){return new g(function(){var a=JSON.stringify(l(["automatic"],d));return k(a)})}function e(d,a){for(;d instanceof g;)d=d.l(a);return d}function g(d){this.i=!1;this.value=d}function t(d){this.value=d}function Ea(d,a){return J(d,function(){return a})}function J(d,a){return new g(function(){var c=e(d,!0);return e(a)(c.value)})}function l(d,a){var c=d[0],b=d[1],f;if("action"==c)f=function(){return l(b[0],
e(a,!0).value)};else if("function"==c)f=function(){var c=a,d=b[b.length-1],f=b.length;if(1<f){for(var c=e(c,!0),g=0;g<f-1&&c instanceof Function;g++)c=e(c(m(b[g],arguments[g])),!0);f=d[1];return"action"==d[0]?l(f[0],c.value):l(d,c)}h(Error("Nullary function?"))};else if("string"==c)f=v(a);else if("list"==c){c=[];for(a=e(a);a instanceof s;)c.push(l(b[0],a.c)),a=e(a.d);f=c}else if("tuple"==c){c=[];a=e(a);for(f=0;a instanceof s;)c.push(l(b[f++],a.c)),a=e(a.d);f=c}else if("defined"==c)a=e(a),f=a instanceof
D?n:$(b[0],a.slot1);else if("nullable"==c)a=e(a),f=a instanceof C?p:$(b[0],a.slot1);else if("double"==c||"int"==c||"bool"==c)f=e(a);else{if("ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a instanceof g&&(a=e(a)),f=$(d,a)):h(Error("Unhandled Fay->JS translation type: "+c))}return f}function v(d){var a="";for(d=e(d);d instanceof s;)a+=d.c,d=e(d.d);return a}function m(d,a){var c=d[0],b=d[1],e;if("action"==c)e=new t(m(b[0],a));else if("string"==c)e=k(a);else if("list"==c){var g=[],c=0;for(e=
a.length;c<e;c++)g.push(m(b[0],a[c]));e=k(g)}else if("tuple"==c){g=[];c=0;for(e=a.length;c<e;c++)g.push(m(b[c],a[c]));e=k(g)}else if("defined"==c)e=a===n?new D:new F(m(b[0],a));else if("nullable"==c)e=a===p?new C:new E(m(b[0],a));else if("int"==c)e=Math.round(a),e!==a&&h("Argument "+a+" is not an integer!");else{if("double"==c||"bool"==c||"ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a&&a.instance?(b=d[2],b="Nullable"===a.instance?new E(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:
["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Just"===a.instance?new la(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new ma:"Left"===a.instance?new na(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new oa(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===
a.instance?new pa(a.slot1,a.slot2):"GT"===a.instance?new qa:"LT"===a.instance?new ra:"EQ"===a.instance?new sa:"Nullable"===a.instance?new E(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Content"===a.instance?new G(m(["user","DString",[]],a.slot1)):"Element"===a.instance?new z(m(["user","DString",[]],a.slot1)):"Attribute"===
a.instance?new B(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):"Property"===a.instance?new H(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:"M"===a.instance?new ta(a.slot1,a.slot2):"L"===a.instance?new ua(a.slot1,a.slot2):"H"===a.instance?new va(a.slot1):"V"===a.instance?new wa(a.slot1):"A"===a.instance?new xa(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6,a.slot7):"C"===a.instance?new ya(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,
a.slot6):"S"===a.instance?new za(a.slot1,a.slot2,a.slot3,a.slot4):"Q"===a.instance?new Aa(a.slot1,a.slot2,a.slot3,a.slot4):"T"===a.instance?new Ba(a.slot1,a.slot2):"Z"===a.instance?new Ca:"Translate"===a.instance?new S(a.slot1,a.slot2):"Rotate"===a.instance?new O(a.slot1,a.slot2,a.slot3):"Scale"===a.instance?new T(a.slot1):"Scale2d"===a.instance?new N(a.slot1,a.slot2):"Content"===a.instance?new G(m(["user","DString",[]],a.slot1)):"Element"===a.instance?new z(m(["user","DString",[]],a.slot1)):"Attribute"===
a.instance?new B(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):"Property"===a.instance?new H(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:a):b=a,e=b):h(Error("Unhandled JS->Fay translation type: "+c))}return e}function s(d,a){this.c=d;this.d=a}function k(d){for(var a=p,c=d.length-1;0<=c;c--)a=new s(d[c],a);return a}function x(d){return function(a){return new s(d,a)}}function Fa(d){return new g(function(){return e(d)+e(1)})}function X(d){return new g(function(){return e(d)-
e(1)})}function Wa(d){return new g(function(){return e(d)>e(0)})}function $a(d){return new g(function(){return e(d)<e(0)})}function Za(d){return new g(function(){return e(d)>=e(0)})}g.prototype.l=function(d){return d?this.value():this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var nb=new g(function(){return e(ob(pb))(p)}),L=new g(function(){return new u}),K=new g(function(){return p}),q=new g(function(){return U(x)}),M=new g(function(){return U(Ga)}),ka=new g(function(){return r}),
qb=new g(function(){return new t(m(["user","Node",[]],document.documentElement))}),aa=new g(function(){return r(k("additive"))}),ca=new g(function(){return r(k("attributeName"))}),Ha=new g(function(){return r(k("fill"))}),da=new g(function(){return r(k("repeatCount"))}),Ia=new g(function(){return r(k("values"))}),hb=new g(function(){return ha(k("animateTransform"))}),Ra=new g(function(){return ha(k("rect"))}),rb=new g(function(){return k("http://www.w3.org/2000/svg")}),jb=new g(function(){return e(I(Ia))(sb)}),
sb=new g(function(){return mb(k(";"))}),tb=new g(function(){return lb(rb)}),Va=new g(function(){return e(I(r(k("dur"))))(P)}),Sa=new g(function(){return e(I(r(k("height"))))(P)}),Ta=new g(function(){return e(I(r(k("width"))))(P)}),fb=new g(function(){return e(I(r(k("x"))))(P)}),gb=new g(function(){return e(I(r(k("y"))))(P)}),r=function(d){return function(a){return new g(function(){return new B(d,a)})}},L=new g(function(){return new u}),K=new g(function(){return p}),q=new g(function(){return U(x)}),
M=new g(function(){return U(Ga)}),ka=new g(function(){return r}),fa=function(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof z)return Fa(c);c=a;return e(d)instanceof u?X(c):c=a})}},aa=new g(function(){return r(k("additive"))}),ca=new g(function(){return r(k("attributeName"))}),Ha=new g(function(){return r(k("fill"))}),da=new g(function(){return r(k("repeatCount"))}),Ia=new g(function(){return r(k("values"))}),vb=new g(function(){return bb(k("load"),ub)}),ub=new g(function(){return Ea(J(qb,
e(tb)(cb(e(e(q)(db(e(e(q)(e(e(M)(e(e(q)(e(e(M)(K))(eb())))(e(Ha)(k("green")))))(ja(4,7,k([Y(1,1),Y(2,3),Y(1,1)])))))(e(aa)(k("sum"))),ja(3.5,8,k([Z(0),Z(270),Z(0)])))))(e(aa)(k("sum"))),L))),new t(p))}),E=Q("a"),C=function(){},F=Q("a"),D=function(){},G=Q("a"),z=Q("a"),B=function(d,a){this.a=d;this.b=a},H=function(d,a){this.a=d;this.b=a},u=function(){};this.j=vb;this.k=e};Ja.k(Ja.j);
