function h(z){throw z;}var n=void 0,p=null;function P(z){return function(Q){this[z]=Q}}
var Ia=new function(){function z(d,a){return new g(function(){var c=a,b=e(d);if(b instanceof s){var f=b.c,b=b.d;return e(e(w)(f))(z(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}function Q(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(w)(d))(e(e(w)(b))(Q(d,c)))}h(["unhandled case in prependToAll",[d,a]])})}function Ja(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(w)(b))(Q(d,
c))}h(["unhandled case in intersperse",[d,a]])})}function Ka(d,a,c){return new g(function(){return new t(m(["user","Node",[]],l(["user","Node",[]],c).setAttributeNS(p,A(d),A(a))&&p||l(["user","Node",[]],c)))})}function La(d,a){return new g(function(){return new t(m(["user","Node",[]],document.createElementNS(A(d),A(a))))})}function Ma(d){return new g(function(){return new t(m(["user","Node",[]],l(["user","Node",[]],d).parentNode))})}function Na(d){return new g(function(){return new t(m(["user","Node",
[]],document.createTextNode(A(d))))})}function aa(d,a,c){return new g(function(){if(e(c)===p){var b=a;return new t(b)}var f=e(c);if(f instanceof s){var b=f.c,g=f.d;return I(e(e(d)(a))(b),function(a){return aa(d,a,g)})}h(["unhandled case in foldM",[d,a,c]])})}function Oa(){return new g(function(){return e(e(q)(e(e(q)(e(e(q)(J))(Pa)))(e(Qa)(10))))(e(Ra)(15))})}function Sa(d,a,c){return new g(function(){return function(){return e(e(q)(e(e(q)(e(e(q)(J))(e(ba)(d))))(e(Ta)(a))))(e(ca)(e(function(a){return new g(function(){return e(Ua(a))?
x(a):k("indefinite")})})(c)))}()})}function Va(d){return new g(function(){if(e(d)===p)return U(k("head: empty list"));var a=e(d);if(a instanceof s)return a.c;h(["unhandled case in head",[d]])})}function da(d,a){return new g(function(){if(e(a)===p)return p;var c=e(a);if(c instanceof s){var b=c.c,c=c.d;return e(e(w)(e(d)(b)))(da(d,c))}h(["unhandled case in map",[d,a]])})}function Wa(d){return new g(function(){return function(){var a=new g(function(){return V(ea,0,d)});return e(Xa(a))?v(fa(a,K),d):U(k("Markup has more close elements than open"))}()})}
function ga(d){return new g(function(){return new y(d)})}function V(d,a,c){return new g(function(){if(e(c)===p){var b=a;return b}b=e(c);if(b instanceof s){var f=b.c,g=b.d,b=a;return e(e(d)(f))(V(d,b,g))}h(["unhandled case in foldr",[d,a,c]])})}function U(d){return new g(function(){h(A(d))})}function x(d){return new g(function(){var a=JSON.stringify(l(["automatic"],d));return k(a)})}function ha(d){return new g(function(){var a=e(d);if(a instanceof s)return v(ha(a.d),k([a.c]));if(e(d)===p)return p;
h(["unhandled case in reverse",[d]])})}function fa(d,a){return new g(function(){return 0===e(d)?p:e(Ya(d))?U(k("replicate: negative length")):e(e(w)(a))(fa(W(d),a))})}function v(d,a){return new g(function(){return z(d,a)})}function Za(d,a){return new g(function(){return e(d)(a)})}function $a(d,a){return new g(function(){return new t(m(["unknown"],window.addEventListener(A(d),l(["action",[["unknown"]]],a),e(!1))))})}function ab(d,a){return new g(function(){if(e(a)instanceof u){var c=d;return Wa(c)}c=
d;return e(e(q)(e(e(q)(c))(K)))(a)})}function bb(d,a){return new g(function(){return e(e(L)(e(e(q)(d))(K)))(a)})}function cb(){return new g(function(){return e(e(q)(e(e(q)(Oa()))(e(db)(10))))(e(eb)(10))})}function X(d,a){return new g(function(){return new M(d,a)})}function ia(d,a,c){return new g(function(){return e(e(q)(e(e(q)(e(e(L)(e(e(q)(J))(fb)))(Sa(k("transform"),d,a))))(e(e(ja)(k("type")))(Za(gb,Va(c))))))(e(hb)(da(ib,c)))})}function Y(d){return new g(function(){return new N(d,100,100)})}function Z(d,
a){var c=e(a),b=d[2];if(c instanceof E){var f={instance:"Nullable"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a);n!==b&&(f.slot1=b);return f}return c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:c instanceof ka?(f={instance:"Just"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof
la?f={instance:"Nothing"}:c instanceof ma?(f={instance:"Left"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof na?(f={instance:"Right"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof oa?(f={instance:"Ratio"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof pa?f={instance:"GT"}:c instanceof qa?f={instance:"LT"}:c instanceof ra?f={instance:"EQ"}:c instanceof E?(f={instance:"Nullable"},
b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof C?f={instance:"Null"}:c instanceof F?(f={instance:"Defined"},b=l(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],c.a),n!==b&&(f.slot1=b),f):c instanceof D?f={instance:"Undefined"}:c instanceof G?(f={instance:"Content"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof y?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},
b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],c.b),n!==b&&(f.slot2=b),f):c instanceof u?f={instance:"Complete"}:c instanceof sa?(f={instance:"M"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof ta?(f={instance:"L"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof ua?(f={instance:"H"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof va?(f={instance:"V"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof wa?(f={instance:"A"},b=e(c.a),
n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),c=e(c.m),n!==c&&(f.slot7=c),f):c instanceof xa?(f={instance:"C"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),b=e(c.g),n!==b&&(f.slot5=b),b=e(c.h),n!==b&&(f.slot6=b),f):c instanceof ya?(f={instance:"S"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&
(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof za?(f={instance:"Q"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),b=e(c.e),n!==b&&(f.slot3=b),b=e(c.f),n!==b&&(f.slot4=b),f):c instanceof Aa?(f={instance:"T"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof Ba?f={instance:"Z"}:c instanceof R?(f={instance:"Translate"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof N?(f={instance:"Rotate"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=
b),b=e(c.e),n!==b&&(f.slot3=b),f):c instanceof S?(f={instance:"Scale"},b=e(c.a),n!==b&&(f.slot1=b),f):c instanceof M?(f={instance:"Scale2d"},b=e(c.a),n!==b&&(f.slot1=b),b=e(c.b),n!==b&&(f.slot2=b),f):c instanceof G?(f={instance:"Content"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof y?(f={instance:"Element"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),f):c instanceof B?(f={instance:"Attribute"},b=l(["user","DString",[]],c.a),n!==b&&(f.slot1=b),b=l(["user","DString",[]],
c.b),n!==b&&(f.slot2=b),f):c instanceof u?f={instance:"Complete"}:a}function M(d,a){this.a=d;this.b=a}function S(d){this.a=d}function N(d,a,c){this.a=d;this.b=a;this.e=c}function R(d,a){this.a=d;this.b=a}function Ba(){}function Aa(d,a){this.a=d;this.b=a}function za(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function ya(d,a,c,b){this.a=d;this.b=a;this.e=c;this.f=b}function xa(d,a,c,b,e,g){this.a=d;this.b=a;this.e=c;this.f=b;this.g=e;this.h=g}function wa(d,a,c,b,e,g,k){this.a=d;this.b=a;this.e=c;
this.f=b;this.g=e;this.h=g;this.m=k}function va(d){this.a=d}function ua(d){this.a=d}function ta(d,a){this.a=d;this.b=a}function sa(d,a){this.a=d;this.b=a}function u(){}function B(d,a){this.a=d;this.b=a}function y(d){this.a=d}function G(d){this.a=d}function ra(){}function qa(){}function pa(){}function oa(d,a){this.a=d;this.b=a}function na(d){this.a=d}function ma(d){this.a=d}function la(){}function ka(d){this.a=d}function D(){}function F(d){this.a=d}function C(){}function E(d){this.a=d}function ib(d){return new g(function(){if(e(d)instanceof
R){var a=e(d).a,c=e(d).b;return v(x(a),v(k(","),x(c)))}if(e(d)instanceof N){var a=e(d).a,c=e(d).b,b=e(d).e;return v(x(a),v(k(","),v(x(c),v(k(","),x(b)))))}if(e(d)instanceof S)return a=e(d).a,x(a);if(e(d)instanceof M)return a=e(d).a,c=e(d).b,v(x(a),v(k(","),x(c)));h(["unhandled case in transformVals",[d]])})}function gb(d){return new g(function(){if(e(d)instanceof R)return k("translate");if(e(d)instanceof N)return k("rotate");if(e(d)instanceof S||e(d)instanceof M)return k("scale");h(["unhandled case in transformType",
[d]])})}function jb(d){return function(a){return function(c){return new g(function(){return function(){return aa(function(a){return function(c){return new g(function(){if(e(c)instanceof B){var g=e(c).a,k=e(c).b,l=a;return Ka(g,k,l)}if(e(c)instanceof y)return g=e(c).a,l=a,I(La(d,g),Ca(l));if(e(c)instanceof u)return l=a,Ma(l);if(e(c)instanceof G)return k=e(c).a,l=a,Da(I(Na(k),Ca(l)),new t(l));h(["unhandled case in go",[a,c]])})}},c,ha(a))}()})}}}function Ca(d){return function(a){return new g(function(){return new t(m(["user",
"Node",[]],l(["user","Node",[]],d).appendChild(l(["user","Node",[]],a))&&p||l(["user","Node",[]],a)))})}}function ea(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof y)return Ea(c);c=a;return e(d)instanceof u?W(c):c=a})}}function r(d){return function(a){return new g(function(){return new B(d,a)})}}function kb(d){return function(a){return new g(function(){return e(lb)(Ja(d,a))})}}function Fa(d){return function(a){return new g(function(){return z(d,a)})}}function mb(d){return function(a){return function(c){return new g(function(){if(e(c)===
p){var b=a;return b}b=e(c);if(b instanceof s){var f=b.c,g=b.d,b=a;return e(e(d)(f))(V(d,b,g))}h(["unhandled case in foldr",[d,a,c]])})}}}function nb(d){return function(a){return new g(function(){var c=a,b=e(d);if(b instanceof s){var f=b.c,b=b.d;return e(e(w)(f))(z(b,c))}c=a;if(e(d)===p)return c;h(["unhandled case in conc",[d,a]])})}}function T(d){return function(a){return function(c){return new g(function(){return e(e(d)(c))(a)})}}}function H(d){return function(a){return function(c){return new g(function(){return e(d)(e(a)(c))})}}}
function O(d){return new g(function(){var a=JSON.stringify(l(["automatic"],d));return k(a)})}function e(d,a){for(;d instanceof g;)d=d.l(a);return d}function g(d){this.i=!1;this.value=d}function t(d){this.value=d}function Da(d,a){return I(d,function(){return a})}function I(d,a){return new g(function(){var c=e(d,!0);return e(a)(c.value)})}function l(d,a){var c=d[0],b=d[1],f;if("action"==c)f=function(){return l(b[0],e(a,!0).value)};else if("function"==c)f=function(){var c=a,d=b[b.length-1],f=b.length;
if(1<f){for(var c=e(c,!0),g=0;g<f-1&&c instanceof Function;g++)c=e(c(m(b[g],arguments[g])),!0);f=d[1];return"action"==d[0]?l(f[0],c.value):l(d,c)}h(Error("Nullary function?"))};else if("string"==c)f=A(a);else if("list"==c){c=[];for(a=e(a);a instanceof s;)c.push(l(b[0],a.c)),a=e(a.d);f=c}else if("tuple"==c){c=[];a=e(a);for(f=0;a instanceof s;)c.push(l(b[f++],a.c)),a=e(a.d);f=c}else if("defined"==c)a=e(a),f=a instanceof D?n:Z(b[0],a.slot1);else if("nullable"==c)a=e(a),f=a instanceof C?p:Z(b[0],a.slot1);
else if("double"==c||"int"==c||"bool"==c)f=e(a);else{if("ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a instanceof g&&(a=e(a)),f=Z(d,a)):h(Error("Unhandled Fay->JS translation type: "+c))}return f}function A(d){var a="";for(d=e(d);d instanceof s;)a+=d.c,d=e(d.d);return a}function m(d,a){var c=d[0],b=d[1],e;if("action"==c)e=new t(m(b[0],a));else if("string"==c)e=k(a);else if("list"==c){var g=[],c=0;for(e=a.length;c<e;c++)g.push(m(b[0],a[c]));e=k(g)}else if("tuple"==c){g=[];c=0;for(e=a.length;c<
e;c++)g.push(m(b[c],a[c]));e=k(g)}else if("defined"==c)e=a===n?new D:new F(m(b[0],a));else if("nullable"==c)e=a===p?new C:new E(m(b[0],a));else if("int"==c)e=Math.round(a),e!==a&&h("Argument "+a+" is not an integer!");else{if("double"==c||"bool"==c||"ptr"==c||"unknown"==c)return a;"automatic"==c||"user"==c?(a&&a.instance?(b=d[2],b="Nullable"===a.instance?new E(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(m(b&&b[0]?b[0]:
"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Just"===a.instance?new ka(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Nothing"===a.instance?new la:"Left"===a.instance?new ma(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Right"===a.instance?new na(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Ratio"===a.instance?new oa(a.slot1,a.slot2):"GT"===a.instance?new pa:"LT"===a.instance?new qa:
"EQ"===a.instance?new ra:"Nullable"===a.instance?new E(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Null"===a.instance?new C:"Defined"===a.instance?new F(m(b&&b[0]?b[0]:"automatic"===d[0]?["automatic"]:["unknown"],a.slot1)):"Undefined"===a.instance?new D:"Content"===a.instance?new G(m(["user","DString",[]],a.slot1)):"Element"===a.instance?new y(m(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new B(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):
"Complete"===a.instance?new u:"M"===a.instance?new sa(a.slot1,a.slot2):"L"===a.instance?new ta(a.slot1,a.slot2):"H"===a.instance?new ua(a.slot1):"V"===a.instance?new va(a.slot1):"A"===a.instance?new wa(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6,a.slot7):"C"===a.instance?new xa(a.slot1,a.slot2,a.slot3,a.slot4,a.slot5,a.slot6):"S"===a.instance?new ya(a.slot1,a.slot2,a.slot3,a.slot4):"Q"===a.instance?new za(a.slot1,a.slot2,a.slot3,a.slot4):"T"===a.instance?new Aa(a.slot1,a.slot2):"Z"===a.instance?
new Ba:"Translate"===a.instance?new R(a.slot1,a.slot2):"Rotate"===a.instance?new N(a.slot1,a.slot2,a.slot3):"Scale"===a.instance?new S(a.slot1):"Scale2d"===a.instance?new M(a.slot1,a.slot2):"Content"===a.instance?new G(m(["user","DString",[]],a.slot1)):"Element"===a.instance?new y(m(["user","DString",[]],a.slot1)):"Attribute"===a.instance?new B(m(["user","DString",[]],a.slot1),m(["user","DString",[]],a.slot2)):"Complete"===a.instance?new u:a):b=a,e=b):h(Error("Unhandled JS->Fay translation type: "+
c))}return e}function s(d,a){this.c=d;this.d=a}function k(d){for(var a=p,c=d.length-1;0<=c;c--)a=new s(d[c],a);return a}function w(d){return function(a){return new s(d,a)}}function Ea(d){return new g(function(){return e(d)+e(1)})}function W(d){return new g(function(){return e(d)-e(1)})}function Ua(d){return new g(function(){return e(d)>e(0)})}function Ya(d){return new g(function(){return e(d)<e(0)})}function Xa(d){return new g(function(){return e(d)>=e(0)})}g.prototype.l=function(d){return d?this.value():
this.i?this.value:(this.value=this.value(),this.i=!0,this.value)};var lb=new g(function(){return e(mb(nb))(p)}),K=new g(function(){return new u}),J=new g(function(){return p}),q=new g(function(){return T(w)}),L=new g(function(){return T(Fa)}),ja=new g(function(){return r}),ob=new g(function(){return new t(m(["user","Node",[]],document.documentElement))}),$=new g(function(){return r(k("additive"))}),ba=new g(function(){return r(k("attributeName"))}),Ga=new g(function(){return r(k("fill"))}),ca=new g(function(){return r(k("repeatCount"))}),
Ha=new g(function(){return r(k("values"))}),fb=new g(function(){return ga(k("animateTransform"))}),Pa=new g(function(){return ga(k("rect"))}),pb=new g(function(){return k("http://www.w3.org/2000/svg")}),hb=new g(function(){return e(H(Ha))(qb)}),qb=new g(function(){return kb(k(";"))}),rb=new g(function(){return jb(pb)}),Ta=new g(function(){return e(H(r(k("dur"))))(O)}),Qa=new g(function(){return e(H(r(k("height"))))(O)}),Ra=new g(function(){return e(H(r(k("width"))))(O)}),db=new g(function(){return e(H(r(k("x"))))(O)}),
eb=new g(function(){return e(H(r(k("y"))))(O)}),r=function(d){return function(a){return new g(function(){return new B(d,a)})}},K=new g(function(){return new u}),J=new g(function(){return p}),q=new g(function(){return T(w)}),L=new g(function(){return T(Fa)}),ja=new g(function(){return r}),ea=function(d){return function(a){return new g(function(){var c=a;if(e(d)instanceof y)return Ea(c);c=a;return e(d)instanceof u?W(c):c=a})}},$=new g(function(){return r(k("additive"))}),ba=new g(function(){return r(k("attributeName"))}),
Ga=new g(function(){return r(k("fill"))}),ca=new g(function(){return r(k("repeatCount"))}),Ha=new g(function(){return r(k("values"))}),tb=new g(function(){return $a(k("load"),sb)}),sb=new g(function(){return Da(I(ob,e(rb)(ab(e(e(q)(bb(e(e(q)(e(e(L)(e(e(q)(e(e(L)(J))(cb())))(e(Ga)(k("green")))))(ia(4,7,k([X(1,1),X(2,3),X(1,1)])))))(e($)(k("sum"))),ia(3.5,8,k([Y(0),Y(270),Y(0)])))))(e($)(k("sum"))),K))),new t(p))}),E=P("a"),C=function(){},F=P("a"),D=function(){},G=P("a"),y=P("a"),B=function(d,a){this.a=
d;this.b=a},u=function(){};this.j=tb;this.k=e};Ia.k(Ia.j);
